### ISSUE TITLE
unable to open targets.txt.xml

### ISSUE THREAD

**Issue by garethgtt** [1N3/Sn1per#103]
If i point sniper at a targets file with a list of IPs i get lots of errors regarding unable to open targets.txt.xml then once the sniper script finishes it fails to create any report - this is on Kali- latest build
command i uses was sniper /root/targets.txt

I, [2017-10-25T12:50:16.739105 #6697]  INFO -- : Using nmap scan output file logs/nmap_output_2017-10-25_12-50-16.xml
 + -- ----------------------------=[Skipping Full NMap Port Scan]=------------ -- +
 + -- ----------------------------=[Running Brute Force]=--------------------- -- +
 __________                __         ____  ___
 \______   \_______ __ ___/  |_  ____ \   \/  /
  |    |  _/\_  __ \  |  \   __\/ __ \ \     / 
  |    |   \ |  | \/  |  /|  | \  ___/ /     \ 
  |______  / |__|  |____/ |__|  \___  >___/\  \ 
         \/                         \/      \_/

 + -- --=[BruteX v1.7 by 1N3
 + -- --=[http://crowdshield.com

################################### Running Port Scan ##############################
Failed to open XML output file /usr/share/brutex/loot/nmap-/root/targets.txt.xml for writing

**Comment by 1N3** [comment]
Hi, 

The correct command to scan multiple hosts is via the 'airstrike' and 'nuke' modes only. This is done via 'sniper /root/targets.txt airstrike/nuke' command. The normal sniper mode is to scan a single host only.
