### ISSUE TITLE
Tries to update each time I run sniper

### ISSUE THREAD

**Issue by mother2110** [1N3/Sn1per#104]
Each time I run sniper it ask to update. I have updated several times.
name@archer /usr/share/sniper/loot $ sudo -H sniper /usr/share/sniper/loot/mantis.txt airstrike
 + -- --=[Sn1per 2.7 is available to download... Do you want to update? (y or n)

Any idea? I am running this on Ubuntu Mate 16.04

Thanks

**Comment by mother2110** [comment]
just reinstalled and it is working ... Thanks

**Comment by 1N3** [comment]
cool, glad you got it..
