### ISSUE TITLE
Sn1per and wpscan

### ISSUE THREAD

**Issue by pentester123** [1N3/Sn1per#105]
I think it would be a great idea to integrate wpscan with sniper

**Comment by 1N3** [comment]
Hi, wpscan is already integrated with sniper via the 'web' mode. To test, run 'sniper target.com web'.

**Comment by pentester123** [comment]
I found what I believe might be a bug with that command. It seems to be looping doing the same scanners again and again.

**Comment by 1N3** [comment]
it should run wpscan once if port 80 is open and again if port 443 is open... alternatively, you could just run sniper <target> webportonly 80 to just do a webscan on port 80/tcp. Let me know if that makes sense or if I'm missing something.
