### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SaberSecurity** [1N3/Sn1per#106]
Sniper is asking for workspace everytime it runs, can it be skipped and move to metasploit step.

**Comment by 1N3** [comment]
Hey, thanks for the heads up... I did notice this myself and will be putting in a fix for this in the near future. I'll leave this open for the time being.

**Comment by SaberSecurity** [comment]
Hey, Thanks for the quick reply. 
Sniper is really a fantastic tool, I really like the way it works. 
Looking forward for the fix.

**Comment by menzow** [comment]
@SaberSecurity what is the perceived advantage of moving this to the metasploit step?

I think it should be possible to have uninterrupted runs so sniper can be used in a automated toolchain. This can be achieved by passing (optional) configurations through the command line. 

Example:
`sniper example.com report --workspace=example.com`

**Comment by SaberSecurity** [comment]
Tool is automated in an efficient way, but creating workspace for every attack is making the user to sit all they way till tye complete process ends. 
Thought that if workspace step is automated/skipped it will better for the user. 

Thanks a lot for giving the (optional) switch. (y)

**Comment by 1N3** [comment]
I removed the automatic loot command at the end of the scans in v2.9 which is now available. I definitely want to incorporate a legit a command switch parser with the options suggested by @menzow but that will take a bit more time. Hopefully that works for you in the meantime.
