### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by smziaurrashid** [1N3/Sn1per#109]
1. Subdomain Checker:
   a) Brute subdomain from predefined list & shows HTTP Status Code (recommend tools: knockpy, recon-ng etc.)
   b) Finding subdomain from website html source code.

2. Directory Listing/Traversal Checker
3. Publicaly accessible configuration, backup, git file checker
4. Advance XSS Checker

**Comment by 1N3** [comment]
We're working on adding more web app checks but the best way to check for all OWASP Top 10 vulns is to run 'webscan' mode.
