### ISSUE TITLE
Rake not installed in default Kali

### ISSUE THREAD

**Issue by Derek000** [1N3/Sn1per#11]
Hi,

I noticed that rake not installed by default in Kali.

Can we add the below to the install of provide a check/message?
       gem install rake 

---------------- error -------------------
/usr/bin/ruby2.1 -rubygems /usr/share/rubygems-integration/all/gems/rake-10.3.2/bin/rake RUBYARCHDIR=/var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/unf-0.2.0.beta2 RUBYLIBDIR=/var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/unf-0.2.0.beta2
/usr/bin/ruby2.1: No such file or directory -- /usr/share/rubygems-integration/all/gems/rake-10.3.2/bin/rake (LoadError)

rake failed, exit code 1

-----------------------------------
Thanks again for the work.

**Comment by 1N3** [comment]
thanks for the heads up. Changes have been checked in for v1.4d!
