### ISSUE TITLE
Sniper Update

### ISSUE THREAD

**Issue by gbiagomba** [1N3/Sn1per#110]
Hello,

After updating sniper successfully to version 2.9, i tried running the command again and this time it gave me the output:
+ -- --=[Checking for updates...
 + -- --=[Sn1per  is available to download...Do you want to update? (y or n)
![image](https://user-images.githubusercontent.com/5851606/33677420-b6e14910-da86-11e7-890d-686bfbc7819f.png)

Is it suppose to do that?

**Comment by gbiagomba** [comment]
So I tried running sniper update again and it installs a bunch of stuff but doesn't recognize that the update was done. So when I enter sniper update again I get the above prompt.

**Comment by gbiagomba** [comment]
I just tried running the install script and it still doesn't recognize that version 2.9 is installed

**Comment by gbiagomba** [comment]
I saw the uninstall issue and followed it, so I ran the following commands
rm -Rf /usr/share/sniper/
rm -f /usr/bin/sniper

Then I tried downloading it from git and installing it, and I still get the same error

**Comment by gbiagomba** [comment]
It turns out when I did a git pull in Sn1per it didnt update the files. I removed the git file and re-downloaded it. I uninstalled it and reinstalled it and it now works under 2,9. But the update function in version 2.8 wouldnt let it update to 2.9...just an fyi

**Comment by 1N3** [comment]
Thanks for the heads up... I believe this was an issue that was fixed with 2.9. Glad to hear that it's working now.
