### ISSUE TITLE
Sniper SITREP & SUPPORT

### ISSUE THREAD

**Issue by gbiagomba** [1N3/Sn1per#111]
Hello,

This is not an "issue" per say more of an enhancement but it would be cool to see the two (2) flags in the title be added to sniper. 

If the user enters sniper sitrep, they would see what version they are running and all the functions the version can do. So all the dependencies and programs it calls and their versions.

If the user enters sniper support, they would see a help output. Showing them how to use the program. I know you have "-h" I think but this would be kinda cool to see.

**Comment by 1N3** [comment]
I have similar plans to implement dependency checking in future versions of sniper, so I'll leave this open in the meantime. I can easily add the 'support' command to the next version though.
