### ISSUE TITLE
Sniper overwrite my existing Firefox

### ISSUE THREAD

**Issue by cegi** [1N3/Sn1per#112]
The install script install Firefox and overwrite the existing one, so i go from Firefox 57 quantum to Firefox 52.5.0, is it necessary that the script install Firefox ? If you can do something about that, would be great thanks.

**Comment by 1N3** [comment]
Hey Cegi, Firefox is used to view workspaces in sniper and launch google hacking queries. This is done via apt-get install firefox so depending on which distribution you're running, it may not have the latest version of firefox available unless to have optional repos enabled via /etc/apt/sources.list. I can try to find alternative solutions for this but I'm not sure how to get around this at this time. Perhaps additional checks for already installed packages would help, but that will require quite a few code changes to implement fully.

**Comment by 1N3** [comment]
Closing this out for now until a more permanent solution is found. Until then, review install.sh and remove apt-get install firefox to avoid this if you are running newer versions of firefox.
