### ISSUE TITLE
project gathering

### ISSUE THREAD

**Issue by pentester123** [1N3/Sn1per#113]
in sniper 2.9 whenever I did a project at the end it would ask me for a name so it could gather everything that sniper did. Now in 3.0 it no longer asks me to do this same process. could this feature be put back in?

**Comment by 1N3** [comment]
Hi, This feature is still present but manually done via the 'sniper loot' command. I did this to allow more automation and streamlined function without user intervention. Let me know if that works.

**Comment by pentester123** [comment]
@1N3 it did not work

**Comment by 1N3** [comment]
@pentester123 you ran the 'sniper loot' command? What was the output? I've just tested this on the latest version and it prompts me where to save the files. Let me know if that is not the case.

**Comment by pentester123** [comment]
@1N3 No it does not work for me would it be possible to have one that will auto take everything from the current project that has it do and put everything into 1 older than I name?

Like what it did back in 2.9.

**Comment by gbiagomba** [comment]
@pentester123 can you share the output of when you run sn1per loot? because I used it today and it worked fine for me. So maybe if we see output we can better understand what may have gone wrong.

**Comment by gbiagomba** [comment]
@1N3 I think it might be safe to close this now since @pentester123 has not responded in over a month

**Comment by 1N3** [comment]
agreed.
