### ISSUE TITLE
Missing packages in install for Kali

### ISSUE THREAD

**Issue by HacKanCuBa** [1N3/Sn1per#114]
Running a standard Sn1per session gives, at some point, the following errors:

```
/usr/share/sniper/sniper: line 1982: rpcinfo: command not found
/usr/share/sniper/sniper: line 1983: showmount: command not found
```

This is due to the required packages missing in **Kali**. It's solved by `apt install rpcbind nfs-common`, which should be included in the install.sh script.

I'm running latest version of Kali: `Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali2 (2018-01-11) x86_64 GNU/Linux`

**Comment by HacKanCuBa** [comment]
Check the PR #115

**Comment by 1N3** [comment]
Cool, thanks for the heads up and fix here.
