### ISSUE TITLE
Importing Nmap XML files into Metasploit 

### ISSUE THREAD

**Issue by mother2110** [1N3/Sn1per#116]
When the job finishes and it tried to import nmap xml it fails with...

Failed to connect to the database: could not connect to server: connection refused

Any ideas?

Thanks

**Comment by mother2110** [comment]
+ -- --=[Enter a name for the workspace:
Lot781
 + -- --=[Generating reports...
 + -- --=[Removing blank web screenshots...
 + -- --=[Starting Metasploit service...
 + -- --=[Importing NMap XML files into Metasploit...
[-] Failed to connect to the database: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

                                                  

Unable to handle kernel NULL pointer dereference at virtual address 0xd34db33f
EFLAGS: 00010046
eax: 00000001 ebx: f77c8c00 ecx: 00000000 edx: f77f0001
esi: 803bf014 edi: 8023c755 ebp: 80237f84 esp: 80237f60
ds: 0018   es: 0018  ss: 0018

**Comment by 1N3** [comment]
I believe you need to start the MSF DB: `msfdb start`

**Comment by mother2110** [comment]
Thanks. I will give that a go.

**Comment by mother2110** [comment]
Sorry. It worked. Thanks

**Comment by 1N3** [comment]
Cool, glad to hear. I will be putting in a check/fix for this to make sure the DB is started after running the 'loot' command.
