### ISSUE TITLE
targets.txt

### ISSUE THREAD

**Issue by gbiagomba** [1N3/Sn1per#119]
Hello,

This is not really an issue more of an enhancement. But I noticed that  when using sniper we have to "hardwire" or specify the path of the targets file. I can go "sniper targets nuke" and it knows targets is in the pwd (path working dir). The work around for me has been $9pwd)/targets but I think this is something the application should do by default without me having to specify or due. 

If you can add that in a future release that would be great!

**Comment by 1N3** [comment]
I'll take a look at this... I believe I already have code to do this but for some reason, it never made it into the public release.

**Comment by gbiagomba** [comment]
Ah!

**Comment by 1N3** [comment]
This is getting fixed in the next release.

**Comment by 1N3** [comment]
This should also be fixed in v4.0. Closing out for now.
