### ISSUE TITLE
Checking for existing links before reinstall

### ISSUE THREAD

**Issue by Derek000** [1N3/Sn1per#12]
To reduce noise when reinstalling (assuming the previous old primary directory has been deleted), it may be good to remove existing links in /usr/bin/ created by the old install before creating the new ones. This is especially true if you are installing Sn1per into a different directory.

ln: failed to create symbolic link ‘/usr/bin/xsstracer’: File exists
ln: failed to create symbolic link ‘/usr/bin/findsploit’: File exists
ln: failed to create symbolic link ‘/usr/bin/copysploit’: File exists
ln: failed to create symbolic link ‘/usr/bin/compilesploit’: File exists
ln: failed to create symbolic link ‘/usr/bin/massbleed’: File exists
ln: failed to create symbolic link ‘/usr/bin/brutex’: File exists

Note: I has already manually removed /usr/bin/sniper and /usr/bin/goohack before installing. S these should also be included.

I also saw the below error when reinstalling. I assume this is because one of the packages creates a loot directory, but there is a mkdir loot later in the script that causes the below.
mkdir: cannot create directory ‘loot’: File exists

Thanks again

**Comment by 1N3** [comment]
Thanks! this is fixed in 1.4e.
