### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by gbiagomba** [1N3/Sn1per#120]
Hello,

I noticed the reporting feature only supports *.txt, I was wondering if it would be possible to add html reports, RTF/Docx and/or PDF. This way the ouput format (font, colors, etc)  isnt lost when converting over to a report output.

**Comment by 1N3** [comment]
This is something I've wanted to add for a while, but currently, sniper only supports txt and html output via the 'sniper report/loot' commands. Adding PDF support is rather easy but RTF/Docx support I'm not sure about. I'll leave this open in the meantime but this is definitely something I would like to see in future releases.

**Comment by gbiagomba** [comment]
Thank you, at least PDF would be good, because I can send that to "technical managers"

**Comment by Cheban1996** [comment]
How It's making

**Comment by gbiagomba** [comment]
@Cheban1996 come again?

**Comment by 1N3** [comment]
In terms of reporting, we've added a ton of features to the Professional version of Sn1per which is available here: https://xerosecurity.com. I would check that out to see if it meets your needs for this.

**Comment by gbiagomba** [comment]
@1N3 I will talk to management to see if we can acquire a pro version.
