### ISSUE TITLE
Missing NSE script smbv2-enabled  (Nmap 7.6)

### ISSUE THREAD

**Issue by Kaicastledine** [1N3/Sn1per#123]
Hello,

Sn1per errors when running Nuke on target.

![image](https://user-images.githubusercontent.com/11678433/36149163-a45d45d0-10b6-11e8-8c46-e4926051e1d5.png)

smbv2-enabled.nse is not present in nmap current version (7.6) as it has replaced by smb-protocols.nse

**Comment by 1N3** [comment]
Thanks for the heads up... I'll look into fixing this in the next release.

**Comment by Kaicastledine** [comment]
No worries :)

**Comment by 1N3** [comment]
This is fixed in v4.0 which is now in the master branch.
