### ISSUE TITLE
sniper -f targets -m nuke -w J0hn

### ISSUE THREAD

**Issue by gbiagomba** [1N3/Sn1per#126]
Hello,

I ran the noted command and I got the below error, I thought I should bring it to your attention. 

![image](https://user-images.githubusercontent.com/5851606/37055155-f4c2a2c4-214e-11e8-9e7c-b8f9ca1449dd.png)

**Comment by 1N3** [comment]
thanks for the heads up. I fixed this in v4.1 which is now in the master branch. To fix, I'd do another git clone and re-run install.sh.

**Comment by gbiagomba** [comment]
Thank you!

**Comment by gbiagomba** [comment]
So I just tried to update it and version 4.0 is still in master not 4.1

**Comment by 1N3** [comment]
whoops.. my bad! You will need to do a manual git clone https://github.com/1N3/Sn1per and re-run install.sh. I won't be pushing 4.1 until I have more fixes/updates to include.

**Comment by 1N3** [comment]
Just upload v4.1. You *should* be able to upgrade using sniper -u now.
