### ISSUE TITLE
Sniper Nuke

### ISSUE THREAD

**Issue by gbiagomba** [1N3/Sn1per#127]
Hello,

Is there a way we can run a nuke on one target without having to specify a list of machines? Currently i create a target file with just one IP but it would be great if I could specify one one machine or a CIDR notation to  scan. The same should apply to the airstrike mode and I would like to be able to use a file list with the scan "modes" (e.g., brute force, OSINT, etc) assuming it doesn't already support this.

**Comment by 1N3** [comment]
hey, in sniper v4, single target scans can use the following with all modules enabled:

```sniper -t target_ip --osint --bruteforce --recon --fullportonly -w workspace_alias```

Nuke and airstrike are specifically for scanning multiple hosts where nuke basically runs all scan options on all hosts and airstrike is basically a stealthier/light scan of all hosts. I can look into adding specific options for each mode but alternatively, you could also create a file with the sniper specific flags/modes you want to run via a bash script to accomplish this. 

```
#!/bin/bash
sniper -t target.com --osint --bruteforce --recon --fullportonly -w target
sniper -f targets.txt -m nuke
...
...
```

**Comment by gbiagomba** [comment]
Got it, thank you
