### ISSUE TITLE
blackarch

### ISSUE THREAD

**Issue by ReK2Fernandez** [1N3/Sn1per#130]
https://github.com/1N3/Sn1per/pull/93  <---- left it there..
Hey was busy with a new job head of cybersecurity so all of the sudem got super busy with more responsabilities but now that most things got iron out on my day job I can come back to help with blackarch integration where needed. cheers let me know if I should **not** make any changes thanks.
@jmchia @gutsal-arsen @ifly53e @iambrosie

**Comment by 1N3** [comment]
Hey, congrats with the new role. Feel free to send any pull requests for any blackarch integration you want to include (assuming it doesn't affect existing Kali functionality/integration, etc. of course. I'm definitely open to having support for other OS's is people are willing to contribute the code to make it happen.
