### ISSUE TITLE
error running sn1per

### ISSUE THREAD

**Issue by ppazos** [1N3/Sn1per#132]
I installed sn1per in a new kali vm

On the install process I received several  errors: could not get lock /var/lib/dpkg/lock

When running sniper I got

/usr/bin/sniper: line 220: syntax error near unexpected token '<<<' 

failed merge?

**Comment by gbiagomba** [comment]
For the lock command, it sounds like either 
A. Something else was being installed simultaneously (e.g., apt was running independent of this install doing something else) 
B. If you are not running the install script as root, it could be a permissions thing. 

As for the token error, am not entirely sure...looking at his code everything looks fine but than again I could be wrong so I will direct that to @1N3 

Out of curiosity, can you share what version of sniper your running and screen output?

**Comment by ppazos** [comment]
Hey @gbiagomba 

I installed a clean & new Kali downloaded yesterday.
The Sn1per install was running as root.

The same for Sn1per, I downloaded the latest version from master yesterday by git clone https://github.com/1N3/Sn1per.git

You can see here, there was an issue with some merge
https://github.com/1N3/Sn1per/blob/799ead64bbba8b075ca4964fe0e8593ad440da57/sniper#L220-L224

**Comment by ppazos** [comment]
The change was from about 12 hours ago, bad luck for me https://github.com/1N3/Sn1per/blame/799ead64bbba8b075ca4964fe0e8593ad440da57/sniper#L220-L224

**Comment by 1N3** [comment]
Sorry, this was a bad merge.. It should be fixed in 4.3 which is now available.

**Comment by ppazos** [comment]
+1 will pull again
