### ISSUE TITLE
Multiple Port Scans

### ISSUE THREAD

**Issue by gbiagomba** [1N3/Sn1per#133]
Hello,

This is more of a suggestion than anything else but it would be great if the -p flag supported multiple ports (e.g., 80, 443, 123-125, etc.)

**Comment by 1N3** [comment]
yeah, totally agree.. I'll keep this open.. it should be fairly easy to implement.

**Comment by gbiagomba** [comment]
Awesome thank you sir

**Comment by 1N3** [comment]
This is now possible in v7.4. You can now use sniper -t target.com -p 80,443,8080,8443 -w target to scan custom port lists against hosts. Closing out!

**Comment by gbiagomba** [comment]
@1N3 Ma man! Idk where u live but I would like to buy you a glass of beer my good sir lol
