### ISSUE TITLE
Workspace Flag

### ISSUE THREAD

**Issue by gbiagomba** [1N3/Sn1per#134]
Hello,

So I used the workspace fla and specified a name. It created the workspace but it did not move the results to that workspace, it kept everything in the root of loot.

**Comment by 1N3** [comment]
Thanks for the heads up.. I'll take a look.

**Comment by gbiagomba** [comment]
Just an FYI - I upgraded to version 4.4 and the issue is still there

**Comment by 1N3** [comment]
Strange.. I'll take another look.

**Comment by pgd988** [comment]
yep  there is bug for workspace. It create divided directory for any IP in nuke list into loot. And one directory for workspace name seted by -w with report txt file.

**Comment by 1N3** [comment]
Hi, 

This issue should be fixed in Sn1per v5.1 which is now public. Please update and let me know if this is still an issue. Closing out but will re-open if needed.

**Comment by gbiagomba** [comment]
@1N3 thank you good sir
