### ISSUE TITLE
when i run sniper

### ISSUE THREAD

**Issue by admin0day** [1N3/Sn1per#135]
when i run sniper it turnn back messages like this:
sniper 
/usr/bin/sniper: line 220: syntax error near unexpected token `<<<'
/usr/bin/sniper: line 220: `<<<<<<< HEAD'
how can i fix this probelm?

**Comment by admin0day** [comment]
but also return this when i installing:
ve unmet dependencies:
 arachni:i386 : Depends: ruby:i386 but it is not going to be installed or
                         ruby-interpreter:i386 but it is not installable
                Depends: bundler:i386 but it is not installable
 eyewitness:i386 : Depends: python:i386 but it is not going to be installed
                   Depends: python-bs4:i386 but it is not installable
                   Depends: python-fuzzywuzzy:i386 but it is not installable
                   Depends: python-levenshtein:i386 but it is not going to be installed
                   Depends: python-netaddr:i386 but it is not installable
                   Depends: python-pyasn1:i386 but it is not installable
                   Depends: python-pyvirtualdisplay:i386 but it is not installable
                   Depends: python-qt4reactor:i386 but it is not installable
                   Depends: python-selenium:i386 but it is not installable
                   Depends: firefoxdriver:i386 but it is not going to be installed
                   Depends: python-openssl:i386 but it is not installable
                   Depends: python-rsa:i386 but it is not installable
                   Depends: python-service-identity:i386 but it is not installable
                   Depends: python-twisted:i386 but it is not installable
by the way,my platform note is 
Linux xxxxxxx 4.9.59-v7_Re4son-Kali-Pi+ #1 SMP Tue Nov 21 00:36:47 CST 2017 armv7l GNU/Linux

**Comment by 1N3** [comment]
This was a result of a bad merge in 4.1. I fixed the first issue in 4.3 which is now available. You should be able to run sniper -u to update.

**Comment by admin0day** [comment]
it seem i can't install arachni:i386&eyewitness:i386 in my platform.is there any problems will affect use?

**Comment by 1N3** [comment]
which OS are you running on? Currently, sniper is only officially supported on Kali linux 2.0+. The only other option is to use the docker image in the README.

**Comment by admin0day** [comment]
u just remind me,i will return when i finished full-upgrade.

**Comment by carms642** [comment]
I'm getting the same error. I made updates.
```
uname -a 
4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali2 (2018-01-11) x86_64 GNU/Linux 
```

**Comment by 841409055** [comment]
u talking about the depend or the "<<<"?

**Comment by admin0day** [comment]
when i finished full-upgrade,the problem still inside when i am installing.
The following packages have unmet dependencies:
 arachni:i386 : Depends: ruby:i386 but it is not going to be installed or
                         ruby-interpreter:i386 but it is not installable
                Depends: bundler:i386 but it is not installable
 eyewitness:i386 : Depends: python:i386 but it is not going to be installed
                   Depends: python-bs4:i386 but it is not installable
                   Depends: python-fuzzywuzzy:i386 but it is not installable
                   Depends: python-levenshtein:i386 but it is not going to be installed
                   Depends: python-netaddr:i386 but it is not installable
                   Depends: python-pyasn1:i386 but it is not installable
                   Depends: python-pyvirtualdisplay:i386 but it is not installable
                   Depends: python-qt4reactor:i386 but it is not installable
                   Depends: python-selenium:i386 but it is not installable
                   Depends: firefoxdriver:i386 but it is not going to be installed
                   Depends: python-openssl:i386 but it is not installable
                   Depends: python-rsa:i386 but it is not installable
                   Depends: python-service-identity:i386 but it is not installable
                   Depends: python-twisted:i386 but it is not installable
E: Unable to correct problems, you have held broken packages.
this platform is my Kali-Pi
4.9.59-v7_Re4son-Kali-Pi+ #1 SMP Tue Nov 21 00:36:47 CST 2017 armv7l GNU/Linux

by the way,i try in two machine,they both got the same return when i run "sniper -u"
sniper -u
/usr/bin/sniper: line 220: syntax error near unexpected token `<<<'
/usr/bin/sniper: line 220: `<<<<<<< HEAD'
these platform are 
4.9.59-v7_Re4son-Kali-Pi+ #1 SMP Tue Nov 21 00:36:47 CST 2017 armv7l GNU/Linux
4.14.0-kali3-amd64 #1 SMP Debian 4.14.17-1kali1 (2018-02-16) x86_64 GNU/Linux

**Comment by 1N3** [comment]
@admin0day Haven't tested Sn1per on Kali-Pi but I assume in has it's own packages and slight differences from Kali 2.0 which is currently the only supported OS for Sn1per. I will leave this open in case someone is able to assist in the meantime. 

Regarding the "sniper -u" command not working, I think the best way to get sniper working is to run "git clone https://github.com/1N3/Sn1per into a new directory and re-run ./install.sh. The bug in 4.1 is likely causing the sniper file to not execute properly which is preventing you from upgrading.

**Comment by 841409055** [comment]
i am also try it on docker.the installing process is ok.but the run up just remind me update no matter how many times i finished the update
by the way,the OS is centos7
