### ISSUE TITLE
dont run sniper : line 220: syntax error [Fixed bug]

### ISSUE THREAD

**Issue by samsesh** [1N3/Sn1per#136]
/usr/bin/sniper: line 220: syntax error near unexpected token `<<<'
/usr/bin/sniper: line 220: `<<<<<<< HEAD'

**Comment by samsesh** [comment]
![screenshot from 2018-03-10 13-07-14](https://user-images.githubusercontent.com/22117518/37240687-2196347e-2464-11e8-90b7-af42e5dad968.png)
fixed bug!!

**Comment by 1N3** [comment]
This was fixed in 4.3 which is now public. You should be able to run sniper -u to upgrade to git clone sn1per and re-run install.sh.
