### ISSUE TITLE
When I run airstrike or nuke

### ISSUE THREAD

**Issue by pentester123** [1N3/Sn1per#137]
When I try and run airstrike or nuke it seems to restart sniper.

The commands don't seem to work.

I am running v4.3

@1N3

**Comment by 1N3** [comment]
hey, what syntax are you using? Can you provide a sample of the command? 

Try: ```sniper -m airstrike -f targets.txt -w targets``` to see if that works. It seems to be working fine for me, but let me know if that doesn't work.

**Comment by pentester123** [comment]
I have tried:

sniper -m airstrike -f filename.txt
sniper -m airstrike -f path/to/filename.txt
sniper -f  '/path/to/filename.txt' -m airstrike
sniper -f /path/to/filename.txt -m airstrike
sniper --file /path/to/filename.txt --mode airstrike
sniper -f filename.txt -m airstrike

**Comment by 1N3** [comment]
sorry man, not sure what the issue is. I re-ran the same commands on 4.3 and they worked just fine...

Does targets.txt contain IP's or domain names seperated by a new line? I'm not sure what else could be the problem.

**Comment by pentester123** [comment]
my targets.txt contains ip addresses and it is one per line

**Comment by 0xCC32** [comment]
i have same issue too.
i tried full path and even copying targets file in it's dir and didn't work

**Comment by 1N3** [comment]
hey guys, not sure what the issue is but I just tested this on my own system and it's working fine so I have uploaded the exact script I've been using here: https://gist.github.com/1N3/4803cce29fcce6ffc27554a6979aff79

Can you download the script and replace /usr/share/sniper/sniper with the v4.4 script and let me know if that works?

**Comment by 0xCC32** [comment]
yea it works fine now.
i guess it lacked of -w parameter for workspace even in airstrike and that wasn't described in airstrike parameters

**Comment by 1N3** [comment]
awesome. thanks for confirming. I will push out the fix to the master branch shortly.
