### ISSUE TITLE
Proxy File

### ISSUE THREAD

**Issue by 5l1v3r1** [1N3/Sn1per#139]
Can you please add a feature of --proxy-file like in sqlmap to continue the process when some websites are blocking ip's with a finite tries. Tor or vpn can be used but what i mean this feature can make the whole ip renewal process automatic and it is very useful. Thank you.

**Comment by menzow** [comment]
Sn1per strings together various applications so there's no insurance those will support proxies or wether they will all accept the same format. 

What you could try to do is setup the HTTP_PROXY and HTTPS_PROXY environment variables to point to a proxy server. Most developers will implement those out of convention. You can use a load balancer to redistribute the requests over a list of proxies. [ProxyBroker](https://github.com/constverum/ProxyBroker/) is a great solution for that. 

[proxychains-ng](https://github.com/rofl0r/proxychains-ng) is another solution. It may not be 100% reliable but generally works. To quote from their [README](https://github.com/rofl0r/proxychains-ng/blob/master/README):

>   ProxyChains is a UNIX program, that hooks network-related libc functions
>   in DYNAMICALLY LINKED programs via a preloaded DLL (dlsym(), LD_PRELOAD)
>   and redirects the connections through SOCKS4a/5 or HTTP proxies.
>   It supports TCP only (no UDP/ICMP etc).
> 
>   The way it works is basically a HACK; so it is possible that it doesn't
>   work with your program, especially when it's a script, or starts
>   numerous processes like background daemons or uses dlopen() to load
>   "modules" (bug in glibc dynlinker).
>   It should work with simple compiled (C/C++) dynamically linked programs
>   though.

**Comment by menzow** [comment]
I just found this and thought it would be usefuProxyBroker isn't suitable as a loadbalancer if you want to use your own list of proxies. [cow](https://github.com/cyfdecyf/cow/blob/master/README-en.md) (Climb Over the Wall) is a amazing proxy load balancer written in golang. Great feature is that it automatically detects and changes blocked proxies.

**Comment by RayrayCf9** [comment]
menzow edited on Apr 29, 2018 (most recent

**Comment by 1N3** [comment]
Closing this out since it would take too much time to try and implement this and no assurance that all tools would even support this. For best results, use VPN.
