### ISSUE TITLE
Directory incorrect when entering BruteX

### ISSUE THREAD

**Issue by Derek000** [1N3/Sn1per#14]
Hi,

Looks like the execution directory is incorrect when Sn1per gets to the brute force section.
I dropped a pwd in before the sections which showed it was in the run directory. So "cd ../BruteX/ broke it".
The error seen on execution is.

################################### Running Brute Force #############################
./sniper: line 562: cd: ../BruteX/: No such file or directory
./sniper: line 563: ./brutex: No such file or directory

################################### Running 3rd Party Extensions ####################
./sniper: line 570: cd: Breach-Miner: No such file or directory
python: can't open file 'breachminer.py': [Errno 2] No such file or directory
./sniper: line 573: cd: yasuo: No such file or directory
ruby: No such file or directory -- yasuo.rb (LoadError)
################################### Done! ###########################################

----------------------------------
I changed the cd: ../BruteX/ to cd BruteX and it worked.

Thanks

**Comment by 1N3** [comment]
Fixed! thanks for the heads up!
