### ISSUE TITLE
when updating to 4.4

### ISSUE THREAD

**Issue by akrolla** [1N3/Sn1per#143]
in a sudo user group but not under root when updating from 4.3 to 4.4 it clones desktop and places it in the sniper directory. this was on kali linux.

**Comment by 1N3** [comment]
Hey, thanks for the heads up. How did you update sniper exactly? Did you run ```sudo sniper --update``` or something else?

**Comment by 1N3** [comment]
Hi, 

This was a bug that was fixed in 5.0. Can you try upgrading and let me know if this is still an issue. Closing out for now but will re-open if it's still an issue.
