### ISSUE TITLE
Port 21 - msfconsole (ssh_identify_pubkeys) is missing to set KEY_FILE

### ISSUE THREAD

**Issue by hkm88** [1N3/Sn1per#145]
Hi,

i think below command for "ssh_identify_pubkeys" is missing to set "KEY_FILE".
Could fix this in new release?

<Command>
msfconsole -x "use scanner/ssh/ssh_enumusers; setg USER_FILE "$USER_FILE"; setg RHOSTS "$TARGET"; setg RHOST "$TARGET"; run; use scanner/ssh/ssh_identify_pubkeys; run; use scanner/ssh/ssh_version; run; exit;"

Thanks.
hkm88

**Comment by 1N3** [comment]
This was removed in v6+, so should no longer be an issue. Closing out.
