### ISSUE TITLE
Mysql Dependency  

### ISSUE THREAD

**Issue by MiteshShah** [1N3/Sn1per#146]
# docker run --rm -ti menzo/sn1per-docker sniper -t example.com 

Starting Nmap 7.70 ( https://nmap.org ) at 2018-06-03 14:20 UTC
nmap: nse_nsock.cc:612: void receive_callback(nsock_pool, nsock_event, void*): Assertion `lua_status(L) == LUA_YIELD' failed.
/usr/bin/sniper: line 2142:   549 Aborted                 nmap -A -sV -Pn --script=mysql* -p 3306 $TARGET
/usr/bin/sniper: line 2141: mysql: command not found

**Comment by 1N3** [comment]
hey, thanks for the heads up. Since @menzow manages the docker image, can you open up an issue on the docker project page https://github.com/menzow/sn1per-docker? He should be able to assist with that.

**Comment by MiteshShah** [comment]
Okay :)
