### ISSUE TITLE
#Feature request : Scan Report

### ISSUE THREAD

**Issue by jauharvp** [1N3/Sn1per#147]
It would be awesome if it has an option to get scan report.

**Comment by 1N3** [comment]
This is coming very soon in Sn1per 5.0 Professional. I'm hoping to have it released and ready some time this month.

**Comment by 1N3** [comment]
Hi,

Sn1per Professional 5.0 is available now from the xerosecurity.com website: https://xerosecurity.com. This produces a full HTML reporting interface of all sn1per scan results and workspaces. Let me know if you have any questions.

**Comment by jauharvp** [comment]
Great, I found the update on twitter. 
Kudos and Thanks @1N3
