### ISSUE TITLE
slurp link is broken

### ISSUE THREAD

**Issue by ifly53e** [1N3/Sn1per#149]
Looks like slurp is offline.  Request you add slurp.zip to the bin folder and update install.sh to put in correct path.  Thanks!

**Comment by 1N3** [comment]
Thanks, I'll take a look..

**Comment by 1N3** [comment]
Done. Pushed changes to master to fix this and slurp.zip was added to /bin.

**Comment by ifly53e** [comment]
Thanks for the file.  This slurp,zip was made on 12/4/2017.  There is a 2.0 release dated 12/24/2017 with enhanced features.  If you have the newer file, request you post that to the bin.  Thanks!

**Comment by 1N3** [comment]
Unfortunately, I do not. Perhaps it's cached somewhere online? I'll have to take a look but not sure where to get it right now.
