### ISSUE TITLE
Would you consider including Skipfish?

### ISSUE THREAD

**Issue by Derek000** [1N3/Sn1per#15]
I was thinking that this could be considered as a option from the Sn1per execution point.
Just use what you have i.e target and other available data from the output of the other apps. 

Don't stress... its come together really well.  8-)

Thanks
Derek

**Comment by 1N3** [comment]
Hi, closing this out as sniper already runs nikto, arachni and a bunch of other automated web tools. I don't think adding more tools/programs will improve overall output at this point, so going to close out for now. Thanks for the suggestion.
