### ISSUE TITLE
nikto commented out on upper 8000's ports

### ISSUE THREAD

**Issue by ifly53e** [1N3/Sn1per#152]
Is nikto supposed to be commented out ports like 8000, 8080, 8180, etc...?

One example:
https://github.com/1N3/Sn1per/blob/64289694c8512acd124a80bfcb78522914fe80a9/sniper#L2261

**Comment by 1N3** [comment]
These have already been removed in Sn1per 5.0 which will be pushed out to the public shortly. Before, it was running nikto automatically on high ports but now with the new scan modes, users can scan high web ports with sniper -t <target> -m webporthttp -p <port> -w workspace_alias.
