### ISSUE TITLE
Wrong port on line 1813

### ISSUE THREAD

**Issue by ifly53e** [1N3/Sn1per#154]
https://github.com/1N3/Sn1per/blob/5b64d62770adcfdee8e54793ae2b50147b9af019/sniper#L1813

Should be 123, not 68

**Comment by 1N3** [comment]
Fixed! Changes will be merged into master branch shortly. Thanks for combing through and finding all these 👍

**Comment by ifly53e** [comment]
No problem...A shout out in the changelog like you used to do would be cool.  Thanks!

**Comment by 1N3** [comment]
For sure! will do!
