### ISSUE TITLE
port_XXX variables 67,68,69,123

### ISSUE THREAD

**Issue by ifly53e** [1N3/Sn1per#155]
missing port_XXX variables in the code block starting here for ports 67, 68, 69, 123:
https://github.com/1N3/Sn1per/blob/5b64d62770adcfdee8e54793ae2b50147b9af019/sniper#L1482

port_67=`grep 'portid="67"' $LOOT_DIR/nmap/nmap-$TARGET.xml | grep open`
port_68=`grep 'portid="68"' $LOOT_DIR/nmap/nmap-$TARGET.xml | grep open`
port_69=`grep 'portid="69"' $LOOT_DIR/nmap/nmap-$TARGET.xml | grep open`
port_123=`grep 'portid="123"' $LOOT_DIR/nmap/nmap-$TARGET.xml | grep open`

**Comment by 1N3** [comment]
This is fixed now. Changes will be pushed to master soon.
