### ISSUE TITLE
SCANNING FOR COMMON VULNERABILITIES Error

### ISSUE THREAD

**Issue by anpseftis** [1N3/Sn1per#158]
====================================================================================
 SCANNING FOR COMMON VULNERABILITIES 
====================================================================================
Traceback (most recent call last):
	6: from yasuo.rb:34:in `<main>'
	5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	3: from /usr/lib/ruby/vendor_ruby/sqlite3.rb:2:in `<top (required)>'
	2: from /usr/lib/ruby/vendor_ruby/sqlite3.rb:6:in `rescue in <top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)

**Comment by 1N3** [comment]
This appears to be a Ruby error from Yasuo. Would suggest opening a bug report there https://github.com/0xsauby/yasuo.
