### ISSUE TITLE
App output being lost or stored in the app directory.

### ISSUE THREAD

**Issue by Derek000** [1N3/Sn1per#16]
Hi,

There seems to be a few critical things displayed on the screen that are not captured in any of the files.
This can obviously be reviewed in the terminal before closing it, but it would be great to preserve all the inelegance that comes out of the Sn1per in the loot directory.

eg. /Breach-Miner/Files/Results.html

The movement of the app output could be the last thing that happens in the script. Maybe even consider a full standard output save represented as a HTML to highlight the exceptions where possible.

Consider creating a directory in the loot directory which represents the Target and maybe the time/date so repeated execution doesn't overwrite old data.
This would be great if multiple targets are being assessed in one session.

Thanks
Derek

**Comment by 1N3** [comment]
Thanks for the feedback. This should be fixed in the latest version.
