### ISSUE TITLE
CloudHunter

### ISSUE THREAD

**Issue by neolead** [1N3/Sn1per#161]
what is that and where can get?

**Comment by 1N3** [comment]
Hi,

This is a tool I wrote but haven't published yet... I mistakenly left the commands in the sniper script for testing purposes. If you want to test it, you can clone it from here https://github.com/1N3/CloudHunter and chmod +x cloudhunter and move it to /usr/bin/cloudhunter after so sniper can reference it.

**Comment by 1N3** [comment]
I removed CloudHunter from v5.1 until it's been tested/implemented properly. Closing out for now but I may include this in future versions.
