### ISSUE TITLE
subdomain blasting does not work

### ISSUE THREAD

**Issue by 1522402210** [1N3/Sn1per#166]
![image](https://user-images.githubusercontent.com/25600994/43112394-8984d408-8f28-11e8-9b07-a4190faac15d.png)

I found that upgrading to 5.2, subdomain blasting does not work.

please check.

**Comment by 1522402210** [comment]
![image](https://user-images.githubusercontent.com/25600994/43112984-03b1f4a2-8f2b-11e8-9146-ed44dfce6b50.png)

**Comment by 1N3** [comment]
Hi, what command did you run to perform subdomain brute forcing? The syntax to perform subdomain brute forcing is 'sniper -t target.com --recon -w target'. The --recon or -re flag performs brute forcing and subdomain enumeration. Also, the screenshot you posted which states "SKIPPING FULL NMAP PORT SCAN" are normal debug messages. These are optional scan parameters that must be enabled. To enable full NMap port scans for a scan, use 'sniper -t target.com -fp -w target' and to brute force all services, use the -b flag (ie. sniper -t target.com -w target -b). These options can also be combined, so 'sniper -t target.com -b -fp -o -re -w target) will perform a normal sniper scan + scan all ports, + perform OSINT/recon + brute force all services + enumerate all subdomains. Hope that helps 👍

**Comment by 1522402210** [comment]
@1N3 oh..  thank you~

**Comment by 1N3** [comment]
Closing this out for now. Let me know if you still need help with this.
