### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by getsecnow** [1N3/Sn1per#168]
for some reason subfinder is not fetching any subdomains and also dnscan is not working

-=Subfinder v1.1.3 github.com/subfinder/subfinder
===============================================
-> Must provide a wordlist when bruteforce is enabled.
Try './subfinder -h' for more information
====================================================================================
 BRUTE FORCING DNS SUBDOMAINS 
====================================================================================
python: can't open file '/pentest/recon/dnscan/dnscan.py': [Errno 2] No such file or directory
cat: /usr/share/sniper/loot/uber.com/domains/domains-dnscan-uber.com.txt: No such file or directory

**Comment by 1N3** [comment]
Thanks for the heads up. I fixed the issue with dnscan having an invalid location - I'll checkin the fix sometime today. For subfinder, I reviewed the code and did some testing but can't reproduce. Can you try running the following command to see if it works for you?

```
subfinder -o /tmp/subfinder.txt -b -d target.com
```

**Comment by 1N3** [comment]
Actually, I re-downloaded a fresh copy of subfinder and it looks like it now requires a wordlist to run. I put in a fix in the latest master repo http://github.com/1N3/Sn1per/. I'll publish the official release sometime this week so people can upgrade via 'sniper -u' command.
