### ISSUE TITLE
Optional app extensions at command line

### ISSUE THREAD

**Issue by Derek000** [1N3/Sn1per#17]
Would it be possible to consider adding some of the optional app extensions/optional parameters to the command line over the time?

eg.
1/ override defaults for the harvester to -l 1000 -b all -h -v -n -c  -t 
- without modifying the run script.
  2/ sqlmap injection difficulty and enumeration
  3/ perhaps consider installing and using lynx if html file output is used to display consolidated results.
- less important, but useful if only a remote shell (non graphical) is available during an engagement.

Thanks
Derek

**Comment by 1N3** [comment]
We've added a ton of new config options to customize  Sn1per now in the /root/.sniper.conf to do this and will add more with time.
