### ISSUE TITLE
Update the version in sniper :) 

### ISSUE THREAD

**Issue by moorer2k** [1N3/Sn1per#171]
I see you updated to 5.3. Make sure to change that so we know it's the latest version. Just removed and reinstalled thinking it was still 5.2. haha.

**Comment by moorer2k** [comment]
Also, I am using GVM to manage my go installation. Would be nice to maybe add support for this in the future when detecting the go path!

**Comment by moorer2k** [comment]
Another thing I noticed, you may want to change that "/pentest/recon/dnscan/dnscan.py" to the proper path. I see you have it in there another time properly, but it def throws an error when it hits this.

**Comment by 1N3** [comment]
Thanks for the heads up. I'm working on some of the fixes you mentioned here but have not published the release yet until everything is tested. I should have this done in the next day or two. The DNScan bug will be fixed as well. I'll take a look at the GVM and Amass stuff though and see what can be done.

**Comment by moorer2k** [comment]
Thanks. I know there are some limits, given it's a bash script, but it's def one of the more promising ones I've seen in the less noisy automation game, especially dns related.

**Comment by 1N3** [comment]
This should be fixed now so closing out.
