### ISSUE TITLE
Many features not running after update!! AMASS,sublist3r, subFinder, email security etc...

### ISSUE THREAD

**Issue by ojaschauhan44** [1N3/Sn1per#174]
amass, sublist3r dont show any results or looks like dont even start.

SubFinder has a error with latest update saying  need for wordlist.
(Must provide a wordlist when bruteforce is enabled.
Try './subfinder -h' for more information
)

email Security part has error in python2 modules.? why using python2 still? its better to shift to python3
(
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.1.1) doesn't match a supported version!
)

DirBuster takes alot like alooooot time and some other tools dont show progress.
i dont know if its working or should i close it?
no progress shown in subfinder too..

also shodan search and results are good for testing so maybe that can be included!!

**Comment by 1N3** [comment]
Hi, are you able to run amass/sublist3r against the target standalone to see what the difference in results are? If no subdomains are found, there may not be any that the tool has found. Also, regarding the scan progress/speed, brute forcing subdomains and web files  can take while (This is normal). Best to either switch to a less intrusive scan mode like "stealth" mode or "normal" mode to brute force less files or wait. I'll do some testing on a fresh kali box to see if I can reproduce.

**Comment by ojaschauhan44** [comment]
SubFinder gets some domains but amass/sublist3r never do. no result is
shown its just name pops up and then shuts down.

and problem with report too no image is shown.

yeah please look it up in kali.
thankyou

**Comment by 1N3** [comment]
This should be fixed in Sn1per v6.0. Please git clone the latest release and let me know if that does not work.
