### ISSUE TITLE
cat: /etc/*-release: No such file or directory ---> This is the error, it is showing it.

### ISSUE THREAD

**Issue by goyalvartul** [1N3/Sn1per#177]
Sn1per-master vartul.goyal$ ./sniper -t google.com
cat: /etc/*-release: No such file or directory
./sniper: line 304: cd: /usr/share/sniper: No such file or directory
[*] Saving loot to /usr/share/sniper/loot/google.com [\e[0mOK\e[0m]\e[0m
grep: /etc/issue: No such file or directory
modes/normal.sh: line 26: /usr/share/sniper/loot/google.com/scans/google.com-normal.txt: No such file or directory
modes/normal.sh: line 27: sniper: command not found
tee: /usr/share/sniper/loot/google.com/output/sniper-google.com-201810081209.txt: No such file or directory
Vartul:Sn1per-master vartul.goyal$ 

How to run the Sniper tool? I am getting this above error?

**Comment by 1N3** [comment]
Hi, looks like the sniper script isn't installed. Which OS are you running on and have you tried running the install.sh script yet to install sniper?

**Comment by goyalvartul** [comment]
I tried Mac and Linux

**Comment by 1N3** [comment]
Sn1per is only compatible with Kali Linux 2.0 out of the box. Which Linux distro did you try installing on?
