### ISSUE TITLE
Gathering DNS subdomain (AMASS | SUBFINDER)

### ISSUE THREAD

**Issue by Jinovas** [1N3/Sn1per#181]
Hey just ran sniper on my desktop VM and found the same issue happening there and so far I'm not sure why since everything in the sniper and recon scripts seems to look correct. Here's what I'm seeing:

`====================================================================================
 GATHERING DNS SUBDOMAINS VIA AMASS 
====================================================================================
cut: /usr/share/sniper/loot/workspace/jen/domains/domains-www.website-redacted.com-amass.txt: No such file or directory
cut: /usr/share/sniper/loot/workspace/jen/domains/domains-www.website-redacted.com-amass.txt: No such file or directory
====================================================================================
 GATHERING DNS SUBDOMAINS VIA SUBFINDER 
====================================================================================

[NOTE] Edit /root/.config/subfinder/config.json with your options !===============================================
-=Subfinder v1.1.3 github.com/subfinder/subfinder
===============================================
-> Must provide a wordlist when bruteforce is enabled.
Try './subfinder -h' for more information
`

**Comment by 1N3** [comment]
I just installed the latest amass and it appears to have made a change to the command line options which made the commands used in sniper invalid... I fixed the amass command now in the master branch for sniper. To fix, you can git clone https://github.com/1N3/Sn1per /tmp/Sn1per and re-run the install.sh in /tmp/Sn1per/ after to get the update. The version will still be 6.0 until I publish the changes, but let me know if that helps.

Also, the issue with subfinder should also be fixed. It's complaining that no wordlist was specified which should be fixed now. If you re-run the install.sh after cloning the github repo again, I'll take another look but it is working for me right now.

Keep me posted.

**Comment by Jinovas** [comment]
Ok will do! I'll do it later tonight after work. 

Thx! :)

**Comment by Jinovas** [comment]
Good news! Amass looks like it's working normal as well as subfinder. Yay! :)

**Comment by 1N3** [comment]
Awesome. Glad to hear it! 👍
