### ISSUE TITLE
sniper --target <CIDR> ; what is the correct notation?

### ISSUE THREAD

**Issue by saczysmark** [1N3/Sn1per#182]
Hey,
Could you give the correct notation for CIDR in the command 
[*] DISCOVER MODE
sniper -t|--target <CIDR> -m|--mode discover -w|--workspace <WORSPACE_ALIAS>

I tried 
sniper -t 192.168.10.1-254 or 192.168.10.1/24 and both of them don't work

E.g.:

=============================================================================
 PINGING HOST 
==============================================================================
ping: 192.168.10.1-254: Name or service not known

**Comment by 1N3** [comment]
Hi,

The correct syntax is ```sniper -t 192.168.10.1/24 -m discover -w 192.168.10.0```

That should work, but let me know if it doesn't.

**Comment by saczysmark** [comment]
Hi,
now it works. Thank you.
