### ISSUE TITLE
Sniper v6 install

### ISSUE THREAD

**Issue by gbiagomba** [1N3/Sn1per#184]
When I run the install, I get the below output...looking at the install script I narrowed it down to lines 93-105.

# cd /root/go/src/github.com/bogdanovich/dns_resolver; git pull --ff-only
fatal: unable to access 'https://github.com/bogdanovich/dns_resolver/': Could not resolve host: github.com
package github.com/bogdanovich/dns_resolver: exit status 1
mv: cannot stat 'subfinder': No such file or directory
--2018-12-02 05:07:28--  https://github.com/michenriksen/aquatone/blob/master/subdomains.lst
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-12-02 05:07:33 ERROR 404: Not Found.

**Comment by 1N3** [comment]
Hi,

It looks like you may have lost internet connectivity based on the error:

Could not resolve host: github.com
package github.com/bogdanovich/dns_resolver: exit status 1

I would try running 'host github.com' first to make sure it resolves, then run ./install.sh again to see if that works.

**Comment by gbiagomba** [comment]
I was able to fix it
