### ISSUE TITLE
Error: Google probably now is blocking our requests

### ISSUE THREAD

**Issue by oesterhase** [1N3/Sn1per#185]
Always when i enter sniper -o -re -fp -b -t Domain

I get the messages 

[!] Error: Google probably now is blocking our requests
[~] Finished now the Google Enumeration ...

then it stopped?

**Comment by 1N3** [comment]
This is likely the result of running metagoofil as part of the 'recon' mode. This is fairly common/normal but should continue with all other search engines before finalizing the results. That being said, it might be worth checking with the metagoofil Github page or developer as I'm not sure if there's anything different I can do on my side to get around this. You mentioned though that the scan scan stopped? Does that mean it's just hanging on metagoofil indefinitely or just that the results from the tool just don't display any results? Also, if you recon mode multiple times in a short period of time from the same IP, you're more likely to get blocked. If you use VPN, I found it's better to switch IP's before running recon mode to avoid setting off any alarms or getting blocked. Just a thought..
