### ISSUE TITLE
cat: BruteX/wordlists/snmp-community-strings.txt: No such file or directory

### ISSUE THREAD

**Issue by ximico** [1N3/Sn1per#19]
Kali Linux 2: updated
Sn1per: fresh release

+ -- --=[Port 162 opened... running tests...
cat: BruteX/wordlists/snmp-community-strings.txt: No such file or directory

**Comment by 1N3** [comment]
Are you running the latest Sn1per version? 1.5a? If so, did you run the install.sh script? There was some changes to BruteX that were recently updated so re-running the install.sh should clean up the issue. Let me know.
