### ISSUE TITLE
sslscan command not found

### ISSUE THREAD

**Issue by jepunband** [1N3/Sn1per#191]
Hi one of the error during the scan i get this error "sslcan command not found".
I already have sslscan installed. I can run sslscan on it's own.

**Comment by 1N3** [comment]
Hi, does this happen every time you run Sn1per? Also, which mode are you using? Can you paste the exact error output from Sn1per?

**Comment by jepunband** [comment]
the error seems to be fixed after a re-install, however there is these 2 errors that is not fixed.

1. python3: can't open file /usr/share/sniper/plugins/wig/wig.py: no such file or directory

2. modes/normal.sh: line 1171: cd: /usr/share/sniper/plugins/yasuo: No such file or directory
ruby: No such file or directory -- yasuo.rb

plugins folder is empty and does not have these files as stated above ...

thanks.

**Comment by 1N3** [comment]
Strange... these are both installed via the install.sh file under the "Downloading extensions" section. This relies mainly on having an active internet connection and git installed. Not sure what else to recommend except maybe running the install.sh file again.

**Comment by 1N3** [comment]
Closing this out for now but let me know if you still need help with this.
