### ISSUE TITLE
Removing workspace error

### ISSUE THREAD

**Issue by Comodooo** [1N3/Sn1per#192]
Hi, 

Just installed the tool and everything went fine running it a first time. Now when I tried to run it against another domain I only get the text:

"Do you want to remove the workspace?"

I have tried using the --list parameter to see what I have but it's empty. I have also tried the uninstall script and reinstalling the tool, but I still get the same error. Even tried creating a workspace manually by adding the directory that it was trying to look for but I still get the same result. 

Any clues about this? Running it on a fresh Kali box with all packages updated.

**Comment by 1N3** [comment]
Hi, which command are you running exactly?

**Comment by Comodooo** [comment]
sniper -d domain.com

**Comment by 1N3** [comment]
Hi, the -d switch is to delete a workspace. Try using -t for the target:

sniper -t domain.com

**Comment by Comodooo** [comment]
jebus christ..... don't know what to say, mixed up the syntax for different tools...... everything seems to be in order now.....

**Comment by 1N3** [comment]
All good! ;)
