### ISSUE TITLE
mv: cannot stat 'SubOver': No such file or directory

### ISSUE THREAD

**Issue by Parshuram2** [1N3/Sn1per#193]
Error message while running Install.sh.

**Comment by 1N3** [comment]
Hi, can you send me the output from the following command?

cd ~/go/bin/;go get -u github.com/Ice3man543/SubOver; mv SubOver /usr/local/bin/subover

**Comment by Parshuram2** [comment]
I get the same message "mv: cannot stat 'SubOver': No such file or directory". It didn't work because the file  at github is named SubOver-master instead of SubOver. So, I downloadd it changed the name to SubOver and copied it to go/bin. I am running Install.sh..now...Hope it works. If it doesn't will get back to you. Thanks so much for your reply

**Comment by Parshuram2** [comment]
It didn't work. Now, it get's stuck after
inflating: slurp/README.md         
  inflating: slurp/permutations.json  
  inflating: slurp/slurp-linux-amd64  
  inflating: slurp/slurp-macos-amd64  
  inflating: slurp/slurp-windows-386.exe 

Also, I checked go/bin..the folder I Copied over is also not there.

**Comment by Parshuram2** [comment]
ok..it worked. Thanks.
