### ISSUE TITLE
how i can connect server?

### ISSUE THREAD

**Issue by CyberTheReape** [1N3/Sn1per#194]
hello. thank for this project.. this program with a web site 443 port brute force attack made. found username and password..but what program should I use to connect to port 443?so I do not know exactly where to use this username and password..

**Comment by 1N3** [comment]
Hi, these are usually a false positive result but if you load the site in a web browser, it should prompt you for credentials if basic auth is enabled. If nothing prompts you for credentials, just ignore the result of the brute force.

**Comment by CyberTheReape** [comment]
Ok thank you...

**Comment by 1N3** [comment]
No prob!
