### ISSUE TITLE
process_nmap_scan' yasuo.rb:232:in each_slice': invalid slice size (ArgumentError)

### ISSUE THREAD

**Issue by everything4lulz** [1N3/Sn1per#195]
hello, i used sn1per community edition a few times, and now when i scan its doing some of the scans then in the yasou scan i have a traceback:

Traceback (most recent call last):
	3: from yasuo.rb:700:in `<main>'
	2: from yasuo.rb:132:in `run'
	1: from yasuo.rb:232:in `process_nmap_scan'
yasuo.rb:232:in `each_slice': invalid slice size (ArgumentError)
I, [2019-05-13T14:19:51.842253 #20197]  INFO -- : Using nmap scan output file logs/nmap_output_2019-05-13_14-19-48.xml

  then it importing the nmap xml files into metasploit then shows this text:
+ -- --=[Generating reports...
[||||]
 + -- --=[Sorting all domains...
 + -- --=[Removing blank screenshots...
 + -- --=[Sn1per Professional is not installed. To download Sn1per Professional, go to https://xerosecurity.com. 
 + -- --=[Done!

i thought that maybe its just expired and i have to buy professional but it never said something about limited hosts in the community edition.

**Comment by 1N3** [comment]
Hi, the error seems to be coming from Yasuo specifically. I'd recommend opening a github issue with the developer here for assistance as I'm not familiar with the error or the cause: https://github.com/0xsauby/yasuo

The message about Sn1per Professional not being installed is normal and not required to run Sn1per scans using the Community Edition.

**Comment by 1N3** [comment]
Did a quick search.... perhaps this will help: https://github.com/0xsauby/yasuo/issues/12
