### ISSUE TITLE
theHarvester outdated

### ISSUE THREAD

**Issue by Jinovas** [1N3/Sn1per#199]
Just wanted to say that there's a new version of theHarvester (3.1.0) out and does require some api keys for it to run. The version in sniper seems to still kinda work but the newer version produces more results(I assume from the use of the API keys that censys and a few others require)

**Comment by 1N3** [comment]
Appreciate the heads up. Will definitely look into this to see how to update the settings...

**Comment by Jinovas** [comment]
No worries! :)

**Comment by Jinovas** [comment]
Oh also, the 3.1.0 version is only on github currently. I looked at the install script and saw that it was installing from the kali repositories which only has the 3.0.6 version.

**Comment by 1N3** [comment]
I updated theHarvester to use the latest 3.x version available from Kali, so this should work now.
