### ISSUE TITLE
Running sniper on Ubuntu 14.04 64-bit

### ISSUE THREAD

**Issue by JayMaree** [1N3/Sn1per#20]
./sniper: line 81: whois: command not found
./sniper: line 82: theharvester: command not found
./sniper: line 83: theharvester: command not found
./sniper: line 84: theharvester: command not found
./sniper: line 85: theharvester: command not found
./sniper: line 86: dnsrecon: command not found
./sniper: line 87: dnsrecon: command not found
./sniper: line 88: dnsrecon: command not found
./sniper: line 89: dnsenum: command not found
./sniper: line 91: shodan: command not found

I started ./sniper on a fully up to date Ubuntu VM.

**Comment by 1N3** [comment]
Thanks for the heads up.. did you by chance run the install.sh script?

**Comment by 1N3** [comment]
I fixed some options in the setup.sh to install theHarvester but let me know if this is still an issue.

**Comment by JayMaree** [comment]
Still the same:
./sniper: line 89: theHarvester: command not found
./sniper: line 90: theHarvester: command not found
./sniper: line 91: theHarvester: command not found
./sniper: line 92: theHarvester: command not found
./sniper: line 93: dnsrecon: command not found
./sniper: line 94: dnsrecon: command not found
./sniper: line 95: dnsrecon: command not found
./sniper: line 96: dnsenum: command not found
./sniper: line 98: shodan: command not found

A few things works fine now, like the Shodan install step. Didn't work either before.

**Comment by 1N3** [comment]
I put in a fix for #2 and #3 which should allow you to run your scans. I'll need to look into compatibility issues with Ubuntu though as Sn1per was made primarily for Kali Linux.

**Comment by 1N3** [comment]
You can now run a docker container from any Linux flavor (Check the main project README...) in order to run sniper which should solve your issue. Closing out for now, but let me know if you're still having issues getting it to run.

**Comment by menzow** [comment]
@JayMaree @1N3 ; The docker solution is the perfect solution with guaranteed compatibility on any OS that runs docker. 

But that doesn't solve the issue at hand: running sn1per on Ubuntu. Your problem is that you're missing specific programs sn1per tries to run. Some sn1per dependencies reside in the kali linux repository.

To install these programs you need to add the kali repository to your sources list. This can be done through the following commands: 
```
echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" >> /etc/apt/sources.list.d/kali.sources.list
gpg --keyserver pgpkeys.mit.edu --recv-key  ED444FF07D8D0BF6
gpg -a --export ED444FF07D8D0BF6 | apt-key add -
apt-get update 
```
[More info](http://docs.kali.org/general-use/kali-linux-sources-list-repositories)

Now you can manually install each missing dependency, or run the following command to install them all:
```
apt-get install -y \
	ruby \
	rubygems \
	python \
	dos2unix \
	zenmap \
	sslyze \
	uniscan \
	xprobe2 \
	cutycapt \
	unicornscan \
	waffit \
	host \
	whois \
	dirb \
	dnsrecon \
	curl \
	nmap \
	php \
	php-curl \
	hydra \
	iceweasel \
	wpscan \
	sqlmap \
	nbtscan \
	enum4linux \
	cisco-torch \
	metasploit-framework \
	theharvester \
	dnsenum \
	nikto \
	smtp-user-enum \
	whatweb \
	dnsutils \
	sslscan \
	amap \
	arachni \
apt-get clean && \
mv /usr/bin/python /usr/bin/python.unknown && \
ln -s /usr/bin/python2.7 /usr/bin/python && \
curl https://bootstrap.pypa.io/get-pip.py | python && \
gem install  \
	mechanize \
	bcrypt \
	net-http-persistent \
	rake \
	ruby-nmap \
	text-table && \
pip install  \
	colorama \
	dnspython \
	ipaddress \
	tldextract \
	urllib3

```

After installing all dependencies, I'd advice to re-install sn1per through the following command:
```
git clone https://github.com/1N3/Sn1per.git ~/Sn1per
cd ~/Sn1per
./install.sh
```

With the previous commands ran you should now have a fully working copy of sn1per installed on your host OS.

**Comment by hariom282538** [comment]
SCANNING FOR COMMON VULNERABILITIES 
====================================================================================
Traceback (most recent call last):
	2: from yasuo.rb:34:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- sqlite3 (LoadError)

**Comment by hariom282538** [comment]
“brute force file not specified, bay.”

**Comment by satyamkumar420** [comment]
modes/normal.sh: line 26: sniper: command not found

**Comment by satyamkumar420** [comment]
└─$ sudo ./sniper -t www.linkedin.com
[*] Loaded configuration file from /usr/share/sniper/sniper.conf [OK]
[*] Loaded configuration file from /root/.sniper.conf [OK]
[*] Saving loot to /usr/share/sniper/loot/ [OK]
[*] Scanning www.linkedin.com [OK]
modes/normal.sh: line 26: sniper: command not found
