### ISSUE TITLE
add Virtual host scanner

### ISSUE THREAD

**Issue by dorkerdevil** [1N3/Sn1per#201]
Add the virtual host scanner

**Comment by 1N3** [comment]
Definitely something I would like to add in the future. Do you have any suggested tools/methods for doing this?

**Comment by dorkerdevil** [comment]
here 
https://github.com/codingo/VHostScan

**Comment by 1N3** [comment]
This was added in v7.4 via gobuster. Need to run at least 'normal', 'web' or 'nuke' mode to run. 👍
