### ISSUE TITLE
add js link finder

### ISSUE THREAD

**Issue by dorkerdevil** [1N3/Sn1per#202]
passive and active crawling gives tons of js files.
so idea is collect the js files and pass them to js link finder

**Comment by 1N3** [comment]
Definitely something I would like to add in the future... just need the time to work on it. I'll leave this open and see if this can be added.

**Comment by dorkerdevil** [comment]
can be added, if we can use passive scanner to get all the links/endpoints  and then save all those links and filter the .js links only, then curl it or wget and save all those .js files locally and then pass those .js files to js link finder.
i tried manually. so its might be possible to do so in sn1per

**Comment by attacker34** [comment]
Hi @1N3  

Now, Its best time to work on this Enhancement. 
Sincerely,

**Comment by 1N3** [comment]
This was added in v8.3 which is currently public.
