### ISSUE TITLE
wayback archive error 

### ISSUE THREAD

**Issue by dorkerdevil** [1N3/Sn1per#203]
waybackarchive: Get http://web.archive.org/cdx/search/cdx?url=*.example.com/*&output=json&fl=original&collapse=urlkey&page=
: net/http: HTTP/1.x transport connection broken: malformed HTTP response "<html>"

**Comment by 1N3** [comment]
Did a quick stealth scan against example.com but not getting the same error on mine. All I can say is this domain has a ton of entries on waybackmachine which might be overloading the server or the connection in general. Have you tried another domain to see if you get the same error?

**Comment by dorkerdevil** [comment]
during recon, most likely its gets time out or throws error but during the airstrike , the passive scanner works well..

**Comment by 1N3** [comment]
Checked the code and all modes appear to be using the same command for this. I'll keep this open for now but let me know if you still see this error consistently on other domains.
