### ISSUE TITLE
asn lookup

### ISSUE THREAD

**Issue by dorkerdevil** [1N3/Sn1per#204]
is it possible to add amass in sniper to perform asn lookup?
i know sn1per uses amass.

**Comment by 1N3** [comment]
Looking at the help menu for Amass but don't see which command switch will perform ASN lookups. Do you have an example command for this? The command current used by sn1per is: 

```amass -ip -brute -active -o $LOOT_DIR/domains/domains-$TARGET-amass.txt -min-for-recursive 3 -d $TARGET 2>/dev/null```

**Comment by dorkerdevil** [comment]
A guide for amass is available here
https://github.com/OWASP/Amass/blob/master/doc/user_guide.md

**Comment by dorkerdevil** [comment]
Amass Intel -asn <ASN number>

**Comment by 1N3** [comment]
ASN look ups were added via ASnip to retrieve ASN's via 'recon' mode in v8.0. Closing out.
