### ISSUE TITLE
Add Hunter.io API integration

### ISSUE THREAD

**Issue by 1N3** [1N3/Sn1per#205]
https://github.com/n4xh4ck5/pyhunter

**Comment by danyalzafar007** [comment]
Dear @1N3 
Tool asked for Hunter API Key while running... There is no entry in Conf file to add API Keys for Hunter.io?
 tool stuck and could not run further.

**Comment by 1N3** [comment]
I'm working on adding this to the next version of Sn1per. That being said, since Sn1per uses theHarvester, you can also add your API directly to theHarvester by editing your /usr/share/theharvester/discovery/huntersearch.py file and adding your API key there (should look similar to below).

self.database = "https://api.hunter.io/v2/domain-search?domain=" + word + "&api_key=039838b34f2d269ecda2750b75a42c51e3a34ff3fdfdf2&limit=" + str(self.limit)

**Comment by 1N3** [comment]
This was added to v7.2 which is now public. To activate Hunter.io, update your ~/.sniper.conf file with the following settings:

# HUNTER.IO API KEY
HUNTERIO_KEY=""
HUNTERIO="1"

* NOTE: This requires the (-o) switch for OSINT to work.
