### ISSUE TITLE
error while running tool

### ISSUE THREAD

**Issue by maheshwar1729** [1N3/Sn1per#206]
root@kali:~/Sn1per# sniper google.com
[*] Loaded configuration file from ~/.sniper.conf [OK]
Unknown scan option google.com...refer to the help menu for usage details.

**Comment by fr0stedfl4ke** [comment]
You're supposed to use -t as an option with your target name. Simply running sniper "domain" doesn't work. You need to use sniper -t first. Type sniper --help for additional information as to the different parameters and options.

**Comment by 1N3** [comment]
Thanks @fr0stedfl4ke ... I meant to reply back sooner but completely forgot, so thanks for the assist! @maheshwar1729, using -t should work but feel free to reopen if you still need help.
