### ISSUE TITLE
cannot install on docker

### ISSUE THREAD

**Issue by anggisaja** [1N3/Sn1per#211]
Step 6/8 : RUN sed -i 's/systemctl status ${PG_SERVICE}/service ${PG_SERVICE} status/g' /usr/bin/msfdb && msfdb reinit
 ---> Running in bf67439b2fb7
sed: can't read /usr/bin/msfdb: No such file or directory
The command '/bin/sh -c sed -i 's/systemctl status ${PG_SERVICE}/service ${PG_SERVICE} status/g' /usr/bin/msfdb && msfdb reinit' returned a non-zero code: 2

**Comment by 1N3** [comment]
there's been some changes/fixes in the latest docker file. Can you try again and see if that works?

**Comment by anggisaja** [comment]
Step 6/8 : RUN sed -i 's/systemctl status ${PG_SERVICE}/service ${PG_SERVICE} status/g' /usr/bin/msfdb && msfdb reinit
 ---> Running in e897ee02d51d
sed: can't read /usr/bin/msfdb: No such file or directory
The command '/bin/sh -c sed -i 's/systemctl status ${PG_SERVICE}/service ${PG_SERVICE} status/g' /usr/bin/msfdb && msfdb reinit' returned a non-zero code: 2

**Comment by rain0r** [comment]
Got the same problem:

```
Sending build context to Docker daemon  39.81MB
Step 1/8 : FROM kalilinux/kali-linux-docker
 ---> f26f3ae90aee
Step 2/8 : LABEL org.label-schema.name='Sn1per - Kali Linux'     org.label-schema.description='Automated pentest framework for offensive security experts'     org.label-schema.usage='https://github.com/1N3/Sn1per'     org.label-schema.url='https://github.com/1N3/Sn1per'     org.label-schema.vendor='https://xerosecurity.com'     org.label-schema.schema-version='1.0'     org.label-schema.docker.cmd.devel='docker run --rm -ti hariomv/sniper'     MAINTAINER="Hariom Vashisth <hariom.devops@gmail.com>"
 ---> Using cache
 ---> 3a0b612b406d
Step 3/8 : RUN echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list &&     echo "deb-src http://http.kali.org/kali kali-rolling main contrib non-free" >> /etc/apt/sources.list
 ---> Using cache
 ---> fd20216c9cbc
Step 4/8 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 71e3a476ea8a
Step 5/8 : RUN set -x     && apt-get -yqq update     && apt-get -yqq dist-upgrade     && apt-get clean
 ---> Using cache
 ---> f138109d0b95
Step 6/8 : RUN sed -i 's/systemctl status ${PG_SERVICE}/service ${PG_SERVICE} status/g' /usr/bin/msfdb && msfdb reinit
 ---> Running in 44f1de022023
sed: can't read /usr/bin/msfdb: No such file or directory
The command '/bin/sh -c sed -i 's/systemctl status ${PG_SERVICE}/service ${PG_SERVICE} status/g' /usr/bin/msfdb && msfdb reinit' returned a non-zero code: 2
```

**Comment by skynetweb** [comment]
Same problem here
`+ apt-get clean
Removing intermediate container 4056267a8717
 ---> b8e793fe966a
Step 6/8 : RUN sed -i 's/systemctl status ${PG_SERVICE}/service ${PG_SERVICE} status/g' /usr/bin/msfdb && msfdb reinit
 ---> Running in a62944d384b6
sed: can't read /usr/bin/msfdb: No such file or directory
The command '/bin/sh -c sed -i 's/systemctl status ${PG_SERVICE}/service ${PG_SERVICE} status/g' /usr/bin/msfdb && msfdb reinit' returned a non-zero code: 2`

**Comment by tjshipe** [comment]
Same problem 👍 
```sed: can't read /usr/bin/msfdb: No such file or directory
The command '/bin/sh -c sed -i 's/systemctl status ${PG_SERVICE}/service ${PG_SERVICE} status/g' /usr/bin/msfdb && msfdb reinit' returned a non-zero code: 2```

**Comment by tjshipe** [comment]
It looks like the kali-linux-docker image doesn't include the standard tools anymore: https://github.com/offensive-security/kali-linux-docker

"There are no tools added to this image, so you will need to install them yourself"

**Comment by techadontech** [comment]
was this resolved guys

**Comment by agussang** [comment]
Stiil bug, get same error

sed: can't read /usr/bin/msfdb: No such file or directory
The command '/bin/sh -c sed -i 's/systemctl status ${PG_SERVICE}/service ${PG_SERVICE} status/g' /usr/bin/msfdb && msfdb reinit' returned a non-zero code: 2

**Comment by techadontech** [comment]
add this before running msfdb reinit
RUN apt-get install -y metasploit-framework

afterwards run the database then it will proceed

**Comment by Cr4zylive** [comment]
------------------ 原始邮件 ------------------
发件人: "agussang"<notifications@github.com>;
发送时间: 2019年8月2日(星期五) 下午5:03
收件人: "1N3/Sn1per"<Sn1per@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [1N3/Sn1per] cannot install on docker (#211)




Stiil bug, get same error
 
sed: can't read /usr/bin/msfdb: No such file or directory
 The command '/bin/sh -c sed -i 's/systemctl status ${PG_SERVICE}/service ${PG_SERVICE} status/g' /usr/bin/msfdb && msfdb reinit' returned a non-zero code: 2
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.







#msfdb delete

#msfdb reinit

**Comment by techadontech** [comment]
FROM kalilinux/kali-linux-docker

LABEL org.label-schema.name='Sn1per - Kali Linux' \
    org.label-schema.description='Automated pentest framework for offensive security experts' \
    org.label-schema.usage='https://github.com/1N3/Sn1per' \
    org.label-schema.url='https://github.com/1N3/Sn1per' \
    org.label-schema.vendor='https://xerosecurity.com' \
    org.label-schema.schema-version='1.0' \
    org.label-schema.docker.cmd.devel='docker run --rm -ti hariomv/sniper' \
    MAINTAINER="Hariom Vashisth <hariom.devops@gmail.com>"

RUN echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list && \
    echo "deb-src http://http.kali.org/kali kali-rolling main contrib non-free" >> /etc/apt/sources.list
ENV DEBIAN_FRONTEND noninteractive

RUN set -x \
    && apt-get -yqq update \
    && apt-get -yqq dist-upgrade \
    && apt-get clean
RUN apt-get install -y metasploit-framework

RUN sed -i 's/systemctl status ${PG_SERVICE}/service ${PG_SERVICE} status/g' /usr/bin/msfdb && msfdb reinit

RUN \
    apt-get --yes install git \
    && mkdir -p security \
    && cd security \
    && git clone https://github.com/1N3/Sn1per.git \
    && cd Sn1per \
    && ./install.sh

CMD ["bash"]

**Comment by Yashiroo** [comment]
This is what i get now:
`Step 6/8 : RUN sed -i 's/systemctl status ${PG_SERVICE}/service ${PG_SERVICE} status/g' /usr/bin/msfdb && msfdb reinit
 ---> Running in 72fbd5f5c757
sed: can't read /usr/bin/msfdb: No such file or directory
The command '/bin/sh -c sed -i 's/systemctl status ${PG_SERVICE}/service ${PG_SERVICE} status/g' /usr/bin/msfdb && msfdb reinit' returned a non-zero code: 2
`
It looks like msf is not being set up properly? Anyone had some time to look at this?
I guess kali docker image changed lately..

**Comment by 1N3** [comment]
I updated the DockerFile with @techadontech's fix. Please try and let us know if that fixes the issue.

**Comment by cyrinux** [comment]
Hi @1N3, it doesn't work, all trailing backslash are missing :)

**Comment by cyrinux** [comment]
@1N3 the working fix here, i fix the syntax + start postgresql
https://github.com/1N3/Sn1per/pull/220
