### ISSUE TITLE
Screenshots failed for all sites, using the script in installation tested on debain 10 

### ISSUE THREAD

**Issue by th3g3nt3lman1** [1N3/Sn1per#213]
abnormal error code: '1' ScreenShot Somehow failed Getting this error for all domains, tested on Debian 10

**Comment by 1N3** [comment]
Hey, just to confirm, are you running Sn1per from an X windows desktop or remotely over SSH?

It *should* work over both but have noticed some issues from other users when running over SSH.

If you are running via SSH (ie. headless), try the following solution/workaround:

apt-get update && apt-get install phantomjs
apt-get install xvfb
xvfb-run webscreenshot https://domain.com:443

If xvfb-run command works for you, you'll need to update all command references for the webscreenshot.py command to use the 'xvfb-run' alternative.

I'm also working on adding a config option to the next version of Sn1per to include this as a work around option.

**Comment by th3g3nt3lman1** [comment]
just got it solved by adding the below in .bashrc
export QT_QPA_PLATFORM=offscreen

then:
source ~/.bashrc 

tested again screenshot are coming :)

**Comment by th3g3nt3lman1** [comment]
in that case i wont have to change anything all command references for the webscreenshot.py command.

**Comment by 1N3** [comment]
Oh nice! Glad to hear it's working now.
