### ISSUE TITLE
Add 'sudo' for install_debian_ubuntu.sh command in README

### ISSUE THREAD

**Issue by ProHackTech** [1N3/Sn1per#214]
In readme, the install instructions for Debian/Ubuntu/Parrot is to run the bash script like this: `bash install_debian_ubuntu.sh` , but it must be run using sudo to avoid inevitable errors. When installing from ParrotOS, there will always be install errors because root is never the default user unless specified. Thanks.

**Comment by 1N3** [comment]
Thanks, I'll update the README with this.
