### ISSUE TITLE
Feature Request : Date/Time stamp upon execution of each command

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#218]
Licensed user and love it! I know some commands will log starts but I was wondering if we can get a definitive date and time log at each script start.

A client reported several issues to a web form and I was going back to review everything ran and cross reference against the time of issue. Turned out not me but would be nice to know exactly when everything ran especially in reports.

David

**Comment by 1N3** [comment]
I like the idea of having time stamps for everything but can't provide an ETA at the moment. I'll look at adding this in the future though.

**Comment by 1N3** [comment]
Implemented in v7.3 which is now public ;) Closing out!
