### ISSUE TITLE
Shodan command needs to be manually installed

### ISSUE THREAD

**Issue by mw3demo** [1N3/Sn1per#22]
Saw the shodan command, but nothing related to it install. It needs to be installed manually by the user via:

    easy_install shodan
    shodan init <api key>

We can add "easy_install shodan" into install.sh , but the user will manually need to register and get an api key for shodan init if they don't have it already.

Might be worth mentioning this in the readme, or show an error advising to do the above in sniper after the command fails.

**Comment by 1N3** [comment]
Thanks for the heads up.. I added an option in setup.sh to install shodan and enter the API key. Should be good now.
