### ISSUE TITLE
Importing constantly

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#221]
Licensed user of 7

I am running discover scans via a script on 21 /24s and 1 /16. Yeah there is a lot! I notice that the majority of the time is taken up by this...
[*] Importing 'Nmap XML' data
[*] Import: Parsing with 'Nokogiri v1.10.4'
[*] Importing host x.x.x.x
It seems as though it importing hosts already imported.

So Then I run full port on all discovered hosts and again the import is taking days.

Is there a way to turn off the import to allow manual through db_import at the end?

David

**Comment by 1N3** [comment]
This is controlled via the METASPLOIT_IMPORT="1" setting in your ~/.sniper.conf file. Setting this to "0" should prevent Sn1per from automatically importing all hosts into Metasploit's DB.

**Comment by clive7391** [comment]
Ahh thanks! That is what that meant. There are a few things in the conf that I am still trying to understand.

I guess changing it in mid scan will not stop the imports from happening. I am 2 weeks in and hate to start over.

**Comment by 1N3** [comment]
No prob!

yeah, unfortunately, it would only change the next scans behavior as the settings get read upon scan start.
