### ISSUE TITLE
Possible to reassemble report hyperlinks when moved from testing system?

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#222]
Licensed Pro 7 user.

I use headless CLI devices to do my testing and then copy the workspace folder to my working system which has browser and desktop. However, the hyperlinks all point back to file:///usr/share/sniper/loot/workspace/*

Is there way to either rebuild the links for review of reports moved to another system?

Follow up, I imagine I might be able to run a simple HTTP server from the workspace root and simply browse the served index.html?

**Comment by 1N3** [comment]
Currently the only way to do this in the current version is to host out the root of your Linux system via a web server (Apache/SimpleHTTPServer). However, this exposes the entire file system to the public so we suggest either setting strict IPTables firewall rules to only whitelist your IP to this port or enable either Basic Authentication/Digest Authentication via Apache/nginx to prevent unauthorized access. The next version of Sn1per will allow path relative hosting via Apache/PHP to the workspace directory which will make this process easier and more secure but this is still under development. 

Hope that helps.
@xer0dayz

**Comment by clive7391** [comment]
Thank you!

**Comment by 1N3** [comment]
Just searching and found this script to host SimpleHTTPServer with basic authentication. This is probably the best solution in the meantime https://gist.githubusercontent.com/fxsjy/5465353/raw/c5e5b66f5b5b35247560d19fd2ea5251f88e34b7/SimpleAuthServer.py

Just execute the script from the root of your drive and should be all set to access remotely with some form of security in place. ```cd / && python /path/to/simplehttpserver.py 8000 admin:admin```

**Comment by clive7391** [comment]
That works to browse the report on the headless remote box but links are broke.
I ran it from the workspace root so limited only to that directory.
Good interim solution. Thanks!
