### ISSUE TITLE
Full port hangs at running nmap scripts. After port 161 open?

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#223]
Licensed 7

Running multiple full port scans and they always seem to hang at running nmap scripts portion.
Currently have three stuck overnight.

===============================================================
 RUNNING SHOW MOUNT 
===============================================================
clnt_create: RPC: Program not registered
clnt_create: RPC: Program not registered
clnt_create: RPC: Program not registered
 + -- --=[Port 123 closed... skipping.
 + -- --=[Port 135 closed... skipping.
 + -- --=[Port 137 closed... skipping.
 + -- --=[Port 139 closed... skipping.
 + -- --=[Port 161 opened... running tests...
====================================================================================
 RUNNING NMAP SCRIPTS 
====================================================================================
Starting Nmap 7.80 ( https://nmap.org ) at 2019-09-10 16:16 EDT

Checking --status it appears this may be the one.
 nmap --script=/usr/share/nmap/scripts/vulscan/vulscan.nse,/usr/share/nmap/scripts/vulners,/usr/share/nmap/scripts/snmp-brute.nse,/usr/share/nmap/scripts/snmp-hh3c-logins.nse,/usr/share/nmap/scripts/snmp-interfaces.nse,/usr/share/nmap/scripts/snmp-ios-config.nse,/usr/share/nmap/scripts/snmp-netstat.nse,/usr/share/nmap/scripts/snmp-processes.nse,/usr/share/nmap/scripts/snmp-sysdescr.nse,/usr/share/nmap/scripts/snmp-win32-services.nse,/usr/share/nmap/scripts/snmp-win32-shares.nse,/usr/share/nmap/scripts/snmp-
Can't get the entire line but you have the idea.

Coincidentally, it seems like it happens only if the host has 161 open.

Is there a nmap script for 161 that would be hanging that I do not see? 

Is _clnt_create: RPC: Program not registered_ an issue?

**Comment by clive7391** [comment]
Or maybe this is the an issue (nmap scripts hanging)
enum4linux complete on Wed Sep 11 07:24:07 2019

Traceback (most recent call last):
  **File "/usr/share/sniper/bin/samrdump.py", line 159, in <module>
    logger.init()
AttributeError: 'module' object has no attribute 'init'**
Doing NBT name scan for addresses from 10.x.x.x

IP address       NetBIOS Name     Server    User             MAC address
------------------------------------------------------------------------------
10.x.x.x     NAME    <server>  NAME    00:00:00:00:00:00
==================================================================
 RUNNING NMAP SCRIPTS 
==================================================================
Starting Nmap 7.80 ( https://nmap.org ) at 2019-09-11 07:24 EDT

**Comment by clive7391** [comment]
I can confirm it is port 161 as I have had 9 that all stall after 161 is found open and probably a nmap snmp script.

**Comment by 1N3** [comment]
Yeah, so it's definitely an NMap script which includes snmp-brute to brute force SNMP community strings which could take a while. NMap doesn't do a good job of reporting running status for each script but most of the time, it is still running in the background waiting to finish.

If you need to cancel the NMap script, I have found that you can just run 'killall nmap' to kill the script and it *should* continue with the rest of the Sn1per scan as normal.

**Comment by 1N3** [comment]
Regarding "Is clnt_create: RPC: Program not registered an issue?" I don't think so as I receive the same error. I believe it just means it can't pull the RPC data from the service which can happen.

**Comment by clive7391** [comment]
I have let it run for 8+ hours and still nothing. I find that hard to believe it would be brute forcing community strings for that long.

I would like to know which snmp scripts are being run and I will manually run each to see which one hangs or takes long. Where can I find the snmp scripts used?

**Comment by 1N3** [comment]
All the scripts are below. This can also be found on line 615 in /usr/share/sniper/modes/normal.sh. Hope that helps and I agree that it shouldn't take that long to brute force SNMP strings. Outside of this, I'm not sure why it could be hanging but selective running might help narrow it down at least.

nmap --script=/usr/share/nmap/scripts/vulscan/vulscan.nse,/usr/share/nmap/scripts/vulners,/usr/share/nmap/scripts/snmp-brute.nse,/usr/share/nmap/scripts/snmp-hh3c-logins.nse,/usr/share/nmap/scripts/snmp-interfaces.nse,/usr/share/nmap/scripts/snmp-ios-config.nse,/usr/share/nmap/scripts/snmp-netstat.nse,/usr/share/nmap/scripts/snmp-processes.nse,/usr/share/nmap/scripts/snmp-sysdescr.nse,/usr/share/nmap/scripts/snmp-win32-services.nse,/usr/share/nmap/scripts/snmp-win32-shares.nse,/usr/share/nmap/scripts/snmp-win32-software.nse,/usr/share/nmap/scripts/snmp-win32-users.nse -sV -A -p 162 -sU -sT $TARGET

**Comment by clive7391** [comment]
I noticed the script and your comment have this
usr/share/nmap/scripts/vulners

the nmap script is 
/usr/share/nmap/scripts/vulners.nse

Is this causing an issue?

**Comment by 1N3** [comment]
I don't think that is the issue as the vulners script seems to run fine for me even though the trailing .nse is missing. Also, NMap usually does a good job of letting you know when it can't find a script or when it's referenced incorrectly, so my guess is it's something else.

**Comment by clive7391** [comment]
Line 586 for port 161 and line 607 for port 162. I deleted the snmp-brute.nse and things are proceeding so far.

**Comment by 1N3** [comment]
snmp-brute.nse was removed in v7.3 which is now public! Thanks for the info!
