### ISSUE TITLE
Documentation on .sniper.conf

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#225]
7.2 Pro and trying to understand the .conf options a little more. While I know 0 and 1 toggle on and off but just would like to know a little more of what some are and didn't see on website and docs about them.

VERBOSE="0" What makes it verbose? Will this give more reportable stuff or debugging type?
AUTOBRUTE="0" I take it this is only for Nuke?
FULLNMAPSCAN="0" Is this different than -fp?
OSINT="0" Wouldn't the -O switch enable this?
ENABLE_AUTO_UPDATES="1" I don't believe I have seen this auto-update?
# ONLINE="1" ?
REPORT="1" I believe this will not generate the report which can be done manually?
LOOT="1" Does this report on loot found (creds, etc)?
SNIPER_PRO_CONSOLE_OUTPUT="0" ?
SN1PER_AUTOLOAD="1" ?

ARACHNI_SCAN="1" Any additional setup for this like Burp Pro?

Thanks for the great product! Just trying to get all out of it.

**Comment by 1N3** [comment]
I'm in the process of updating our documentation with notes on the configuration options (https://github.com/1N3/Sn1per/wiki/Sn1per-Configuration-Options), but please see below regarding the settings you requested:

* VERBOSE="0" - Sets verbose mode to enabled or disables and displays command syntax of each running command via the console. This is currently experimental and not fully implemented.
* AUTOBRUTE="0" - Enables automatic brute forcing via "normal" and "nuke" mode scans. Can also be enabled from the command line via the (-b) switch.
* FULLNMAPSCAN="0" - Enabled automatic full NMap scanning via "normal" and "nuke" mode scans. Can also be enabled from the command line via the (-fp) switch. 
* OSINT="1" - Enables automatic OSINT mode scans via "normal", "stealth", "airstrike" and "nuke" mode scans. Can also be selectively enabled from the command line via the (-o) switch.
* ENABLE_AUTO_UPDATES="1" - Automatically checks for new Sn1per Community version updates from Github.
* ONLINE="1" - Checks if an active internet connection is present. This is still an experimental feature and not fully implemented or utilized. 
* REPORT="1" - Enables report generation for all Sn1per scans. This is a mandatory option, so disabling will cause Sn1per to stop functioning properly.
* LOOT="1" - Saves all console output and reports to a specified loot or workspace directory. Disable to prevent logging and saving of all files. Please note that this option is required for Sn1per Professional to function properly.
* SNIPER_PRO_CONSOLE_OUTPUT="0" - Displays an overview of all hosts in a workspace (ie. open ports, web title, web headers, DNS, etc.) at the end of all Sn1per scans via the console.
* SN1PER_AUTOLOAD="1" - Automatically opens a web browser to load the Sn1per Professional HTML reports from. Disable to prevent this.
* ARACHNI_SCAN="1" - Enables Arachni automated web application scans via the "webscan" mode. No additional configuration is required on Kali Linux 2.x.

Hope that helps.

**Comment by clive7391** [comment]
Helps very much! Much obliged!

I was pretty close on my guesses.

Just to be sure, I can always regenerate a report even if I move or merge work spaces correct? 

sudo sniper -w <WORKSPACE> --reimport

**Comment by 1N3** [comment]
No prob! 

Yes, as long as you merge all folders in the workspace directory and do ```sniper -w <workspace> --reimportall```, it will work. --reimportall will regenerate ALL reports for all hosts, not just the hosts which have been updated or changed.
