### ISSUE TITLE
why don't we have the "skip test" option?

### ISSUE THREAD

**Issue by Parshuram2** [1N3/Sn1per#227]

**Comment by 1N3** [comment]
Might be able to eventually add an interactive mode (ie. -i) switch to do this but you can also selectively enable/disable all plugins and scan options in the ~/.sniper.conf file as well. I'll leave this open to track the request.

**Comment by 1N3** [comment]
Closing out for now. I would recommend configuring your /root/.sniper.conf to selectively enabled/disabled plugins/options. This will be much easier in the professional version of Sn1per as well.
