### ISSUE TITLE
rm read var to assist automation

### ISSUE THREAD

**Issue by anoncam** [1N3/Sn1per#232]
https://github.com/1N3/Sn1per/blob/15257a8cdfff9d4ea349b35543b33a8a9d4f475f/install.sh#L26

https://cloud.docker.com/repository/registry-1.docker.io/pidof/kali/builds/3b47687f-3b3a-4e4d-9dd1-85998cfddde4

**Comment by 1N3** [comment]
Added the following update to install.sh to bypass the readvar:

```./install.sh force```

Hope this helps.
