### ISSUE TITLE
Stuck Sublist3r

### ISSUE THREAD

**Issue by dzhenway** [1N3/Sn1per#234]
Hi,

I got stuck when try run sn1p3r `sudo sniper -t target.com -m stealth -o -re`

`HTTPSConnectionPool(host='www.virustotal.com', port=443): Read timed out. (read timeout=25)`

thank

**Comment by 1N3** [comment]
Hi, many times, sublist3r can appear stuck and certain API's may timeout but if you run 'sniper --status' or even tcpdump for DNS/UDP requests, you will see it's actually still working in the background. However, this process can be time consuming depending on how many sub-domains are being brute forced or retrieved, so keep that in mind.

**Comment by 1N3** [comment]
Closing this out but let me know if this is still occurring.
