### ISSUE TITLE
Program won't take a file

### ISSUE THREAD

**Issue by 0xShin** [1N3/Sn1per#235]
Hello devs,

I am having this problem that the program can't take a file, is this a bug or am I doing it wrong? Thank you very much for your time.

![image](https://user-images.githubusercontent.com/50789123/69150963-9898b580-0a8e-11ea-8b5e-d57da42f041d.png)

**Comment by 1N3** [comment]
Hi,
For multi-host scans, you need to specify a workspace to save to via the -w switch (ie. sniper -f file.txt -m massportscan -w myworkspace).

Hope that helps.
