### ISSUE TITLE
I have a doubt

### ISSUE THREAD

**Issue by meetgyn** [1N3/Sn1per#237]
Does the Free version open in the browser as in the images below?
If so, how should I proceed?

**Comment by 1N3** [comment]
Hi, I don't see the images but if you're referring to the web UI displayed on the homepage of https://xerosecurity.com, that would be the professional version of Sn1per. The free version does not include a reporting UI.

**Comment by meetgyn** [comment]
Thank you. That's exactly what I would like to know.
