### ISSUE TITLE
Sn1per stuck on gathering DNS info

### ISSUE THREAD

**Issue by 1N3** [1N3/Sn1per#238]
If Sn1per appears to be stuck on the "GATHERING DNS INFO" stage, this was caused by an update to dnsenum which we have fixed. To apply the fix, you will need to re-clone the public repo and re-run the install.sh file again:
```
git clone https://github.com/1N3/Sn1per
cd Sn1per
./install.sh
```

**Comment by fr33wi11** [comment]
This issues seems still present . As one can see running the latest version using dockers and also updated it using sniper -u. 

However, it still stuck on gathering DNS info

Any advise?

<img width="727" alt="Screen Shot 2020-02-14 at 7 57 35 am" src="https://user-images.githubusercontent.com/9892047/74477649-cbbcda80-4eff-11ea-8f8b-8fc100fa9ba7.png">
