### ISSUE TITLE
CIDR for all modes

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#239]
Is there a way (other than manipulating the code) that one may scan using CIDR? I would prefer to have discover type scan but scan all ports.

Likewise do a CIDR nuke without bruteforce.

**Comment by 1N3** [comment]
Discover mode is currently the only way. Discover mode does a lot of parsing to pick out live hosts first, then runs 'flyover' mode to pick up basic details. I suppose eventually, this could be changed to 'nuke' mode or any other multi-host mode through some additional switches/options, etc. I don't have an immediate solution but will look at possibly adding this in the future.

**Comment by clive7391** [comment]
No problem. I script it out as a workaround.

Congrats on 8.0. Waiting to hear if there will an upgrade option for 6 and 7 pro users.

**Comment by 1N3** [comment]
Thanks! We are working on the upgrade deal now ;) Definitely want to keep loyal users happy, so stay tuned on Twitter 👍

**Comment by clive7391** [comment]
Thanks and outstanding job!
