### ISSUE TITLE
Import into Metasploit Pro

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#241]
I am licensed all version and running latest v8 with CLE.

I want to auto import into Metasploit Pro.

I changed the sniper executable line 411 to:
    msfpro -x "workspace -a $WORKSPACE; workspace $WORKSPACE; db_import $LOOT_DIR/nmap/nmap*.xml; hosts; services; exit;" | tee $LOOT_DIR/notes/msf-$WORKSPACE.txt

It throws the error:
[i] Database already started
 + -- --=[ Importing NMap XML files into Metasploit...
Traceback (most recent call last):
	5: from /opt/metasploit-pro/apps/pro/engine/msfpro:17:in `<main>'
	4: from /opt/metasploit-pro/apps/pro/engine/lib/metasploit/pro/engine/command/base.rb:65:in `start'
	3: from /opt/metasploit-pro/apps/pro/engine/lib/metasploit/pro/engine/command/base.rb:38:in `require_environment!'
	2: from /opt/metasploit-pro/apps/pro/engine/lib/metasploit/pro/engine/command/base.rb:53:in `parsed_options'
	1: from /opt/metasploit-pro/apps/pro/engine/lib/metasploit/pro/engine/command/base.rb:53:in `new'
/opt/metasploit-pro/apps/pro/engine/lib/metasploit/pro/engine/parsed_options/base.rb:41:in `initialize': invalid option: x (OptionParser::InvalidOption)
	5: from /opt/metasploit-pro/apps/pro/engine/msfpro:17:in `<main>'
	4: from /opt/metasploit-pro/apps/pro/engine/lib/metasploit/pro/engine/command/base.rb:65:in `start'
	3: from /opt/metasploit-pro/apps/pro/engine/lib/metasploit/pro/engine/command/base.rb:38:in `require_environment!'
	2: from /opt/metasploit-pro/apps/pro/engine/lib/metasploit/pro/engine/command/base.rb:53:in `parsed_options'
	1: from /opt/metasploit-pro/apps/pro/engine/lib/metasploit/pro/engine/command/base.rb:53:in `new'
/opt/metasploit-pro/apps/pro/engine/lib/metasploit/pro/engine/parsed_options/base.rb:41:in `initialize': invalid option: -x (OptionParser::InvalidOption)

Thoughts?

**Comment by 1N3** [comment]
I'm not familiar with the differences between MSF community vs. Pro, but it seems the "-x" flag is invalid:
```
initialize': invalid option: -x (OptionParser::InvalidOption)
```
Did you try using the default command first? I would have thought the normal import process would also work for Pro...
```
msfconsole -x "workspace -a $WORKSPACE; workspace $WORKSPACE; db_import $LOOT_DIR/nmap/nmap*.xml; hosts; services; exit;" | tee $LOOT_DIR/notes/msf-$WORKSPACE.txt
```

**Comment by clive7391** [comment]
Pro uses the console command mfspro not mfsconsole.

I can always import manually but I was also looking to leverage pro for all the scans also. I will do some testing and let you know.

Great job on 8!

**Comment by 1N3** [comment]
Sounds good and thanks again for your support! Hopefully there is a quick change to the command to get this working.
