### ISSUE TITLE
Sn1per stuck on 'Gathering Server Info'

### ISSUE THREAD

**Issue by alvinisasi** [1N3/Sn1per#242]
I have stuck when sn1per run wafwoof in 'Gathering Server Info' phase. I ran sn1per with command :
`sniper -t <target>`

**Comment by 1N3** [comment]
Hi, it probably means the target host has a WAF or IPS that is blocking you. To scan using less intrusive methods, maybe try 'sniper -t target -m stealth' to see if that helps.

**Comment by alvinisasi** [comment]
> Hi, it probably means the target host has a WAF or IPS that is blocking you. To scan using less intrusive methods, maybe try 'sniper -t target -m stealth' to see if that helps.

Thank you for the answer, but i've tried it but got same failure

**Comment by 1N3** [comment]
Hi, it probably means your IP is being blocked. Unfortunately, there's not much you can do outside of using a VPN or proxy like TOR or otherwise to get around being blocked.
