### ISSUE TITLE
Sn1per didn't create files for scan

### ISSUE THREAD

**Issue by oliverkko** [1N3/Sn1per#244]
Hi,

Last few scans I have a problem, that sniper didn't create files for scan, after that all scan can't run right.

For example:

```
root@kali:~# sniper -t https://somesite.com/ -o -re -fp -b -w somesite
[*] Loaded configuration file from ~/.sniper.conf [OK]
[*] Saving loot to /usr/share/sniper/loot/ [OK]
modes/normal.sh: line 28: /usr/share/sniper/loot//scans/somesite.com/-normal.txt: No such file or directory
modes/normal.sh: line 29: /usr/share/sniper/loot//scans/running-somesite.com/-normal.txt: No such file or directory
tee: /usr/share/sniper/loot//output/sniper-somesite.com/-202001090450.txt: No such file or directory
[*] Loaded configuration file from ~/.sniper.conf [OK]
[*] Saving loot to /usr/share/sniper/loot/workspace/https:--somesite.com- [OK]
```

Pls, can you help with this issue?

Thanks.

**Comment by 1N3** [comment]
Hi,
Sn1per doesn't currently accept URL's for the target input - it needs to be either the domain/hostname/IP for -t. Eventually, I may add a (-u) for URL switch, but that is not available currently. This is why it didn't save the files properly.
