### ISSUE TITLE
Add Open Redirection Tool

### ISSUE THREAD

**Issue by attacker34** [1N3/Sn1per#245]
Hi @cyrinux 

Please add this Tool for Open Redirection Checking:

```
https://github.com/ak1t4/open-redirect-scanner/

```

Some more Payloads here:

```
https://github.com/cujanovic/Open-Redirect-Payloads/blob/master/Open-Redirect-payloads.txt
https://github.com/payloadbox/open-redirect-payload-list
https://pentester.land/cheatsheets/2018/11/02/open-redirect-cheatsheet.html


```

**Comment by 1N3** [comment]
Will look into this... might be able to fit this into the next release.

**Comment by 1N3** [comment]
The tool referenced no longer appears to be available. Closing out for now, but will look at other solutions to do this in the future.
