### ISSUE TITLE
masswebscan Command Not Working Properly

### ISSUE THREAD

**Issue by attacker34** [1N3/Sn1per#248]
Hi @1N3 

I have tried to run this command:

```
sniper -f targets.txt -m masswebscan

```

But Getting this Error:

```
You need to specify a target or workspace to use. Type sniper --help for command usage.

```

I have tried to Add new workspace name with flag -w but its still not working. Does it need a workspace which is already created and Sn1per already run on some target? 

Thanks.

**Comment by 1N3** [comment]
Thanks for the heads up... I found the issue and pushed a fix to the master branch. For a quick fix, just run the following commands:

```
rm -f /usr/share/sniper/modes/masswebscan.sh
wget https://raw.githubusercontent.com/1N3/Sn1per/master/modes/masswebscan.sh -O /usr/share/sniper/modes/masswebscan.sh
```

You can also just clone the repo and run the install.sh script again too.

**Comment by 1N3** [comment]
btw, the proper usage is just 'sniper -f /path/to/file.txt -m masswebscan -w workspace_alias'

**Comment by attacker34** [comment]
Hi @1N3  Yes, I have tried both commands but its not working...
