### ISSUE TITLE
target and DNS are listed in output

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#249]
8 pro user.

I conduct a discovery scan and it will list the IP as the target and in the next column it will have the DNS name. All good

Halfway down it switches to having the DNS name for the target and the IP for DNS. Duplicate information from above but flipped.

Why does it list the domain name as a target instead of just the IP?

**Comment by 1N3** [comment]
Is it possible to attach an example screenshot? I'm not sure I follow what's happening exactly or at what stage of the scan. By 'discovery' scan, I assume the command was something like 'sniper -t 10.0.0.0/24 -m discovery -w 10.0.0.0', correct?

**Comment by 1N3** [comment]
Closing out for now, but let me know if you still need help with this.
