### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by shanow7** [1N3/Sn1per#251]
I've problem with installation

![image](https://user-images.githubusercontent.com/37192410/74678080-39942b00-51ba-11ea-82df-8ac2f01ed963.png)

why theharvester does not use all sources, e.g. twitter, linkedin and hunter?

can you add tools such as:
https://github.com/kennbroorg/iKy
https://github.com/lulz3xploit/LittleBrother
https://github.com/1N3/BlackWidow
https://github.com/CiKu370/OSIF
https://github.com/m4ll0k/Infoga
https://github.com/Cignoraptor-ita/cignotrack
https://github.com/sc1341/InstagramOSINT
https://github.com/sherlock-project/sherlock
https://github.com/SilverPoision/Rock-ON
https://github.com/ultrasecurity/webkiller
https://github.com/thewhiteh4t/FinalRecon
https://github.com/sundowndev/PhoneInfoga
https://github.com/i3visio/osrframework
https://github.com/lanmaster53/recon-ng

**Comment by 1N3** [comment]
Hi,
Can you try re-running the following command to see the result?
```
pip install h8mail
```
If that still doesn't work, can you try running:
```
pip3 install h8mail
```
Also, which OS and version are you running?

**Comment by attacker34** [comment]
Hi @1N3 

Please integrate your awesome tool  https://github.com/1N3/BlackWidow    in Sn1per. Thanks.

**Comment by shanow7** [comment]
I have a question, can you use similar tools to display results that are found in discover spiderfoot or theharvester?Temat: Re: [1N3/Sn1per] installation problem (#251)Data: 2020-02-22 2:55Nadawca: "NA" Adresat: "1N3/Sn1per" ; DW: "shanow7" ; "Author" ; Hi @1N3
Please integrate your awesome tool  https://github.com/1N3/BlackWidow    in Sn1per. Thanks.

**Comment by 1N3** [comment]
BlackWidow is already integrated into Sn1per. Just use 'stealth' or 'web' modes to initiate a scan.
