### ISSUE TITLE
install on Kali Linux stalled at brutex

### ISSUE THREAD

**Issue by adunkey** [1N3/Sn1per#253]
Hi,

Kicked off install about 3 hours on Kali Linux and it's stuck here:

![image](https://user-images.githubusercontent.com/4255262/74883597-355a4000-5369-11ea-92b0-65ffb6083725.png)

any workarounds/suggestions?

Thanks

**Comment by 1N3** [comment]
Hi,
Just hit "enter". I also checked in a fix to change this behavior on brutex to not prompt, but you can just hit enter to continue installing.
