### ISSUE TITLE
Update sn1per seems not respect installation dir

### ISSUE THREAD

**Issue by eL-Prova** [1N3/Sn1per#255]
It seems that updating sn1per wont respect my installation directory.
My sniper.conf has installation dir for `/home/myaccount/tools/sniper`
When I run sniper and try to update the location for the updated version is `/usr/share/sniper` like the default.

**Comment by 1N3** [comment]
Currently, Sn1per requires that the installation dir is /usr/share/sniper/. I will leave this open as a feature request to look into in the future though.

**Comment by eL-Prova** [comment]
(Y) Thanks for feedback. I will try to find some time to create an pull request

**Comment by 1N3** [comment]
The only solution for the forseable future is to create a symlink: 

```ln -s /usr/share/sniper /home/myaccount/tools/sniper```
