### ISSUE TITLE
Support scanning file with multiple subnets via discover mode

### ISSUE THREAD

**Issue by 1N3** [1N3/Sn1per#256]

**Comment by clive7391** [comment]
I know this is a placeholder for you but, if anybody wants something in the meantime, I created a simple script.
Place all networks in scope.txt and run...
discover.sh workspace-alias

#!/bin/bash
#discover.sh workspace
for a in `cat scope.txt`; do sniper -t $a -w $1 -m discover; done;
#fi

**Comment by 1N3** [comment]
Thanks. I will try and have both the command line mode and GUI option to allow this in the next release.

**Comment by 1N3** [comment]
We added a new feature to Sn1per Professional to allow this. More info here: https://xerosecurity.com/wordpress/sn1per-professional-v9-1-se-update-released/

Hope that helps.
