### ISSUE TITLE
Openvas not working

### ISSUE THREAD

**Issue by researchlab17** [1N3/Sn1per#257]
tried both ports 9390 which is default and port 9392 which is what works for the web console on my setup, niether one works. Any reccomendations, proper password is also set.

====================================================================================•x[2020-03-17](11:00)x•
 RUNNING OPENVAS VULNERABILITY SCAN 
====================================================================================•x[2020-03-17](11:00)x•
One command option must be present.
-:1.1: Document is empty

^
One command option must be present.
-:1.1: Document is empty

^
One command option must be present.
REPORT_ID: 
No report ID found. Listing scan tasks:
One command option must be present.
====================================================================================•x[2020-03-17](11:00)x•
 DONE 
====================================================================================•x[2020-03-17](11:00)x•

**Comment by 1N3** [comment]
hey, apologies for the delay. Make sure you are editing your ~/.sniper.conf file where ~ is your home directory (typically /root/.sniper.conf). The default port is 9390. If that still doesn't work, let me know.

**Comment by researchlab17** [comment]
Confirmed both conf files are configured correctly, as is Openvas, running basic tests itself without issue. What else can we try? We've tried using it in a vanilla and production environment now and it would be really nice to automate Openvas in this way.

====================================================================================•x[2020-03-24](11:06)x•
RUNNING OPENVAS VULNERABILITY SCAN
====================================================================================•x[2020-03-24](11:06)x•
REPORT_ID:
No report ID found. Listing scan tasks:
====================================================================================•x[2020-03-24](11:06)x•
DONE
====================================================================================•x[2020-03-24](11:06)x•
____
_________ / _/___ ___ _____
/ ___/ __ \ / // __ \/ _ \/ ___/
(__ ) / / // // /_/ / __/ /
/____/_/ /_/___/ .___/\___/_/
/_/

**Comment by researchlab17** [comment]
We just by chance updated the password in the original git folder and we are getting a new result, but still no scan, same issue no report id found?

====================================================================================•x[2020-03-24](11:29)x•
RUNNING OPENVAS VULNERABILITY SCAN
====================================================================================•x[2020-03-24](11:29)x•
Scanning target: [REDACTED URL]

-----------------------------------------------
Listing OpenVAS version...
-----------------------------------------------

Listing OpenVAS targets...
-----------------------------------------------

Listing OpenVAS tasks...
-----------------------------------------------

Creating scan task...
-----------------------------------------------
REPORT_ID:

No report ID found. Listing scan tasks:
====================================================================================•x[2020-03-24](11:29)x•
DONE
====================================================================================•x[2020-03-24](11:29)x•

**Comment by researchlab17** [comment]
Seems the vulnscan and massvulnscan scripts are still kitted for the older versions of OpenVAS

**Comment by researchlab17** [comment]
Upon further modification to vulnscan I've noticed that the "config id" was set for original builders setup working on modification set for my build, will report back more tomorrow when I return to this machine. Hopefully we can all figure this out and use it for ourselves!

**Comment by 1N3** [comment]
Yeah, keep me posted... I've only tested this from Kali Linux 2019.4 and 2020.1 with OpenVAS 9.0.3 so far and both work fine for me.

**Comment by researchlab17** [comment]
Yeah no luck, can you try setting up a new VM and see if you're having the same issue?

**Comment by lubosm** [comment]
I have tested this with Snlper v8.2 and OpenVAS 9.0.3kali1 and the result is the same :( 
===================================================================================•x[2020-04-13](23:37)x•
 RUNNING OPENVAS VULNERABILITY SCAN 
====================================================================================•x[2020-04-13](23:37)x•
One command option must be present.
-:1.1: Document is empty

^
One command option must be present.
-:1.1: Document is empty

^
One command option must be present.
REPORT_ID: 
No report ID found. Listing scan tasks:
One command option must be present.
====================================================================================•x[2020-04-13](23:37)x•
 DONE 
====================================================================================•x[2020-04-13](23:37)x•

**Comment by 1N3** [comment]
If OpenVAS isn't working, please try running the following command to verify that the omp client can communicate with OpenVAS. You will need to replace the variables with the appropriate host, port, user/pass to work:

```
omp -h $OPENVAS_HOST -p $OPENVAS_PORT -u $OPENVAS_USERNAME -w $OPENVAS_PASSWORD -O
```

If this works, it should output for the OpenVAS version.
