### ISSUE TITLE
Slack Legacy Tokens Deprecation - 5th May 2020

### ISSUE THREAD

**Issue by dark-flare** [1N3/Sn1per#263]
After 5th May it won't be possible to create new legacy tokens on Slack, as per:
https://api.slack.com/changelog/2020-02-legacy-test-token-creation-to-retire

**Comment by 1N3** [comment]
Thanks for the heads up! Will look into this.

**Comment by 1N3** [comment]
Added in v8.7. Closing out. Guide here: https://github.com/1N3/Sn1per/wiki/Slack-API-Integration
