### ISSUE TITLE
Start/restart web app?

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#266]
8.3 Pro user.

Added fuzzer and updated. No longer have web access via https://:1337.

Is there a web server restart command or diag I can try?

**Comment by 1N3** [comment]
Yes, you can restart by running ```/etc/init.d/apache2 restart```

**Comment by clive7391** [comment]
Thanks for that.
Sort of related...
Is there a way to reset the creds for the gui without an uninstall reinstall?

**Comment by 1N3** [comment]
Yes, we updated our docuimentation with this info, but it's probably not obvious it's there:
https://xerosecurity.com/wordpress/documentation/

Forgot Password

If you forget your password or simply want to change or reset the ‘admin’ user password, run the following command:
```
htdigest -c /etc/htdigest/.htdigest restricted admin
```
