### ISSUE TITLE
cloning error

### ISSUE THREAD

**Issue by nocomp** [1N3/Sn1per#267]
hi folks,
thx for this great tool, i am testing it atm, and facing an issue that keeps goin on
Clonage dans '/usr/local/lib/python3.8/dist-packages/cmsmap-1.0-py3.8.egg/cmsmap/tmp/wordpress'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (19/19), done.
error: échec RPC ; curl 56 GnuTLS recv error (-9): Erreur de décodage du paquet TLS reçu.
fatal: L'hôte distant a fermé la connexion de manière inattendue
fatal: fin de fichier prématurée
fatal: échec de index-pack

it never succeed to finalize the cloning operation, how can i bypass that?
thxx for your time

**Comment by 1N3** [comment]
Hi, can you try the following to see if it works? 

git clone https://github.com/Dionach/CMSmap.git

**Comment by 1N3** [comment]
Not getting the same error on a fresh Kali image but feel free to reopen if you're still having issues.
