### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Leeyuxun** [1N3/Sn1per#268]
The following error occurred when executing ./install.sh after cloning the repository：

Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests) (3.0.4)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
**curl: (7) Failed to connect to raw.githubusercontent.com port 443: 拒绝连接**
 + -- --=[ Installing gem dependencies...

**Comment by 1N3** [comment]
Seems like you hit a connection error connecting to github. I would retry the install.sh again.

**Comment by Leeyuxun** [comment]
thank youI just avoided that mistake.The reason for the error is GFW.I have been waiting in kali all afternoon, and the installation has been successful.
