### ISSUE TITLE
Asterisk in dirsearch subprocess is listing the files

### ISSUE THREAD

**Issue by amirnsahmad** [1N3/Sn1per#269]
All the dirsearch commands are not using the asterisk properly. The asterisk is listing the files.

Example:
python3 $PLUGINS_DIR/dirsearch/dirsearch.py -u http://$TARGET:$PORT -w $WEB_BRUTE_STEALTH -x 400,404,405,406,429,502,503,504 -F -e $WEB_BRUTE_EXTENSIONS -f -r -t $THREADS --random-agents --plain-text-report=$LOOT_DIR/web/dirsearch-$TARGET.txt 2> /dev/null > /dev/null && cat $LOOT_DIR/web/dirsearch-$TARGET.txt

This is generating a subprocess like this:
python3 /usr/share/sniper/plugins/dirsearch/dirsearch.py -u http://site.com -w /usr/share/sniper/wordlists/web-brute-common.txt -x 400,404,405,406,429,502,503,504 -F -e build dist Dockerfile LICENSE LinkFinder.egg-info linkfinder.py README.md requirements.txt setup.py template.html test_parser.py -t 20 --random-agents --plain-text-report=/usr/share/sniper/loot/workspace/teste.txt

**Comment by 1N3** [comment]
Thanks, this will be fixed in the next version (v8.4) which should be out in the next week or so.

**Comment by 1N3** [comment]
This is fixed now. Closing out.
