### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by absane** [1N3/Sn1per#27]
Nice tool! So far it looks like this tool is going to quickly replace the set of scripts I built that do similar work. Good work. With that said I have some requests for features:
- Ability to conduct internal recon/scans/bruteforce.
- Split up the results of each scan/test/attack into sub directories for easier searching through organization
- Convert nmap results to all 3 formats + XLS
- Incorporate EyeWitness to screenshot web apps/RDP/VNC

**Comment by 1N3** [comment]
Hey thanks for the feedback. EyeWitness is already on the roadmap to add in and I like the idea of the sub-directories for each scan/target. I'm also going to look into how to utilize this better for internal recon and scanning.

**Comment by absane** [comment]
Sounds good! Also, one thing that just occurred to me is that it might also be nice to have an option to use Masscan/Unicornscan for port enumeration and then use Nmap to do service enumeration + anything else (scripts, etc). Nmap is great but it does not scale well for port scanning a large set of IPs.

Much of this might be a tall order but the script is so far very good. Keep up the awesome work.

**Comment by No-0Peration** [comment]
Checkout my recon script it had some of those features... But its still in development

**Comment by morganh83** [comment]
Excellent tool. I love it! The only feature I would like to see is the ability to select the tests it runs. For example, I do not want to run Hydra and brute force any logins on my client's network. Would love to be able to select (or configure) which tools are executed during one of the modes.

**Comment by 1N3** [comment]
@morganh83 Sn1per includes the ability to disable brute forcing, google hacking queries and full nmap port scanning in the sniper script itself (see below). Simply change the settings for each from 1 to 0 to enable/disable. Eventually, I'll add more robust options for other toolsets, but this should help you out for now. 

```
# ENABLE/DISABLE AUTOMATIC BRUTE FORCE
# DEFAULT IS "1" (ENABLED)
AUTOBRUTE="1"

# ENABLE/DISABLE FULL DETAILED NMAP SCAN
# DEFAULT IS "1" (ENABLED)
FULLNMAPSCAN="1"

# ENABLE/DISABLE AUTOMATIC GOOGLE HACKING QUERIES
# DEFAULT IS "1" (ENABLED)
GOOHAK="1"
```

**Comment by 1N3** [comment]
Most of these features have already been added to Sn1per Professional v7.0. Please see https://xerosecurity.com for more details.
