### ISSUE TITLE
[request] use helpful/normal commit message instead of static one

### ISSUE THREAD

**Issue by bugbaba** [1N3/Sn1per#270]
Hi,

Firstly thanks for the amazing work you have been doing on this product/project.

But could you please normal/helpful commit messages instead of your current static message, I mean personally I don't think its bringing any value to seo/marketing of this project, with normal commit message people will be access the changes in the code more easily and thus will be able to contribute more easily.

![image](https://user-images.githubusercontent.com/29960776/84065763-822e5900-a9e2-11ea-90c4-a8ec9138f4b7.png)

--
Regards,
@bugbaba

**Comment by 1N3** [comment]
Thanks for the feedback. Will start keeping more descriptive comments for each commit.
