### ISSUE TITLE
Error on GitHub process 

### ISSUE THREAD

**Issue by khanjanny** [1N3/Sn1per#272]
i am facing a problem with the GitHub part. I have already added API key but it showing error. is there anything I am doing wrong ...??  

```
[i] Status code : 401
[!] Unexpected HTTP response 401
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
[i] Github query : https://api.github.com/search/code?q=**********&sort=indexed&o=desc
 
```

**Comment by 1N3** [comment]
Which mode did  you run to generate this error?

**Comment by khanjanny** [comment]
when i run through one of your bug_bounty_quick config. mode was  "STEALTH MODE + OSINT + RECON "

**Comment by 1N3** [comment]
Gotcha.

In that case, you will need to add your API keys to that config profile first. The profiles overwrite your default config under /root/.sniper.conf

**Comment by khanjanny** [comment]
but I think I have added on both of the bug_bounty_quick.config and ~/.sniper.config , i think am doing something wrong but if i add GitHub api on both config it should work.

**Comment by 1N3** [comment]
Did you ever get this working?

**Comment by khanjanny** [comment]
no

**Comment by 1N3** [comment]
Did you follow this guide first? 

https://github.com/1N3/Sn1per/wiki/Github-API-Integration

You need to add your Github API keys to /usr/share/sniper/plugins/gitGraber/config.py for this to work.
