### ISSUE TITLE
Metasploit

### ISSUE THREAD

**Issue by Jase-NZ** [1N3/Sn1per#273]
After upgrade to 8.4 I see the following info. I don't think it matters just annoying to see it all the time.
`The pg and/or activerecord gem version has changed, meaning deprecated pg constants
may no longer be in use, so try deleting this file to see if the
'The PGconn, PGresult, and PGError constants are deprecated...' message has gone:
/usr/share/metasploit-framework/lib/pg/deprecated_constants.rb`

**Comment by 1N3** [comment]
Hi,
Haven't seen this error yet, but can you try the following and see if the error goes away?

mv /usr/share/metasploit-framework/lib/pg/deprecated_constants.rb /usr/share/metasploit-framework/lib/pg/deprecated_constants.rb.bak

**Comment by Jase-NZ** [comment]
Hey thanks for the reply and awesome work. Been down that road and throws this up instead.
As I said it does not seem to stop anything .
`The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:240:in `load_dependency'`

**Comment by 1N3** [comment]
Just updated the installer in v8.5, so this shouldn't happen now. Let know though.
