### ISSUE TITLE
Sniper no job

### ISSUE THREAD

**Issue by v0re** [1N3/Sn1per#276]
root@v0R37:~# sniper -c ~/.sniper.conf -t google.com -w WORKSPACE_ALIAS
Starting PostgreSQL 12 database server: main.
[*] Loaded configuration file from ~/.sniper.conf [OK]
[*] Creating backup of existing config to ~/.sniper.conf.bak...[OK]
[*] Copying /root/.sniper.conf to ~/.sniper.conf...[OK]
cp: '/root/.sniper.conf' and '/root/.sniper.conf' are the same file
[*] Saving loot to /usr/share/sniper/loot/workspace/WORKSPACE_ALIAS [OK]
Starting PostgreSQL 12 database server: main.
[*] Checking for active internet connection [OK]
Starting PostgreSQL 12 database server: main.
[*] Loaded configuration file from ~/.sniper.conf [OK]
[*] Saving loot to /usr/share/sniper/loot/workspace/WORKSPACE_ALIAS [OK]
Starting PostgreSQL 12 database server: main.
[*] Checking for active internet connection [OK]
                ____
    _________  /  _/___  ___  _____
   / ___/ __ \ / // __ \/ _ \/ ___/
  (__  ) / / // // /_/ /  __/ /
 /____/_/ /_/___/ .___/\___/_/
               /_/

 + -- --=[https://xerosecurity.com
 + -- --=[Sn1per v8.4 by @xer0dayz

====================================================================================•x[2020-06-23](20:59)x•
 GATHERING DNS INFO
====================================================================================•x[2020-06-23](20:59)x•
====================================================================================•x[2020-06-23](20:59)x•
 CHECKING FOR SUBDOMAIN HIJACKING
====================================================================================•x[2020-06-23](20:59)x•

====================================================================================•x[2020-06-23](20:59)x•
 PINGING HOST
====================================================================================•x[2020-06-23](20:59)x•
PING google.com (104.27.197.88) 56(84) bytes of data.
64 bytes from 104.27.197.88 (104.27.197.88): icmp_seq=1 ttl=56 time=155 ms

--- jable.tv ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 155.460/155.460/155.460/0.000 ms

====================================================================================•x[2020-06-23](20:59)x•
 RUNNING TCP PORT SCAN
====================================================================================•x[2020-06-23](20:59)x•
Warning: Nmap may not work correctly on Windows Subsystem for Linux.
For best performance and accuracy, use the native Windows build from https://nmap.org/download.html#windows.
WARNING: Duplicate port number(s) specified.  Are you alert enough to be using Nmap?  Have some coffee or Jolt(tm).
Couldn't open a raw socket. Error: Permission denied (13)
Starting Nmap 7.80 ( https://nmap.org ) at 2020-06-23 20:59 CST
====================================================================================•x[2020-06-23](20:59)x•
 RUNNING UDP PORT SCAN
====================================================================================•x[2020-06-23](20:59)x•
Warning: Nmap may not work correctly on Windows Subsystem for Linux.
For best performance and accuracy, use the native Windows build from https://nmap.org/download.html#windows.
Starting Nmap 7.80 ( https://nmap.org ) at 2020-06-23 20:59 CST
Couldn't open a raw socket. Error: Permission denied (13)
====================================================================================•x[2020-06-23](20:59)x•
 RUNNING HTTP PROBE
====================================================================================•x[2020-06-23](20:59)x•
modes/normal.sh: line 130: fprobe: command not found
modes/normal.sh: line 131: fprobe: command not found

====================================================================================•x[2020-06-23](20:59)x•
 RUNNING INTRUSIVE SCANS
====================================================================================•x[2020-06-23](20:59)x•
 + -- --=[Port 21 closed... skipping.
 + -- --=[Port 22 closed... skipping.
 + -- --=[Port 23 closed... skipping.
 + -- --=[Port 25 closed... skipping.
 + -- --=[Port 53 closed... skipping.
 + -- --=[Port 67 closed... skipping.
 + -- --=[Port 68 closed... skipping.
 + -- --=[Port 69 closed... skipping.
 + -- --=[Port 79 closed... skipping.
 + -- --=[Port 80 closed... skipping.
 + -- --=[Port 110 closed... skipping.
 + -- --=[Port 111 closed... skipping.
 + -- --=[Port 123 closed... skipping.
 + -- --=[Port 135 closed... skipping.
 + -- --=[Port 137 closed... skipping.
 + -- --=[Port 139 closed... skipping.
 + -- --=[Port 161 closed... skipping.
 + -- --=[Port 162 closed... skipping.
 + -- --=[Port 264 closed... skipping.
 + -- --=[Port 389 closed... skipping.
 + -- --=[Port 443 closed... skipping.
 + -- --=[Port 445 closed... skipping.
 + -- --=[Port 500 closed... skipping.
 + -- --=[Port 512 closed... skipping.
 + -- --=[Port 513 closed... skipping.
 + -- --=[Port 514 closed... skipping.
 + -- --=[Port 1099 closed... skipping.
 + -- --=[Port 1433 closed... skipping.
 + -- --=[Port 2049 closed... skipping.
 + -- --=[Port 2181 closed... skipping.
 + -- --=[Port 3306 closed... skipping.
 + -- --=[Port 3310 closed... skipping.
 + -- --=[Port 3128 closed... skipping.
 + -- --=[Port 3389 closed... skipping.
 + -- --=[Port 3632 closed... skipping.
 + -- --=[Port 5432 closed... skipping.
 + -- --=[Port 5555 closed... skipping.
 + -- --=[Port 5800 closed... skipping.
 + -- --=[Port 5900 closed... skipping.
 + -- --=[Port 5984 closed... skipping.
 + -- --=[Port 6000 closed... skipping.
 + -- --=[Port 6667 closed... skipping.
 + -- --=[Port 7001 closed... skipping.
 + -- --=[Port 8000 closed... skipping.
 + -- --=[Port 8001 closed... skipping.
 + -- --=[Port 9495 closed... skipping.
 + -- --=[Port 10000 closed... skipping.
 + -- --=[Port 16992 closed... skipping.
 + -- --=[Port 27017 closed... skipping.
 + -- --=[Port 27018 closed... skipping.
 + -- --=[Port 27019 closed... skipping.
 + -- --=[Port 28017 closed... skipping.
 + -- --=[Port 49180 closed... skipping.
====================================================================================•x[2020-06-23](20:59)x•
 SKIPPING FULL NMAP PORT SCAN
====================================================================================•x[2020-06-23](20:59)x•
====================================================================================•x[2020-06-23](20:59)x•
 SKIPPING BRUTE FORCE
====================================================================================•x[2020-06-23](20:59)x•
====================================================================================
•?((¯°·..• Sc0pe Vulnerability Report by @xer0dayz •._.·°¯))؟•
====================================================================================
Critical: 0
High: 0
Medium: 0
Low: 0
Info: 0
Score: 0
====================================================================================
====================================================================================
====================================================================================•x[2020-06-23](20:59)x•
 SCAN COMPLETE!
====================================================================================•x[2020-06-23](20:59)x•
                ____
    _________  /  _/___  ___  _____
   / ___/ __ \ / // __ \/ _ \/ ___/
  (__  ) / / // // /_/ /  __/ /
 /____/_/ /_/___/ .___/\___/_/
               /_/

[*] Opening loot directory /usr/share/sniper/loot/workspace/WORKSPACE_ALIAS [OK]
 + -- --=[ Generating reports...
[|]
 + -- --=[ Sorting all files...
 + -- --=[ Removing blank screenshots and files...
 + -- --=[ Sn1per Professional is not installed. To download Sn1per Professional, go to https://xerosecurity.com.
 + -- --=[ Done!``

**Comment by 1N3** [comment]
Warning: Nmap may not work correctly on Windows Subsystem for Linux.
For best performance and accuracy, use the native Windows build from https://nmap.org/download.html#windows.
WARNING: Duplicate port number(s) specified. Are you alert enough to be using Nmap? Have some coffee or Jolt(tm).
Couldn't open a raw socket. Error: Permission denied (13)

Looks like NMap doesn't have permission to open sockets. Which OS are you running from?
