### ISSUE TITLE
BeautifulSoup

### ISSUE THREAD

**Issue by v0re** [1N3/Sn1per#277]
•x[2020-06-28](03:53)x•
Traceback (most recent call last):
  File "/usr/bin/blackwidow", line 6, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

**Comment by v0re** [comment]
MODES : AIRSTRIKE

**Comment by 1N3** [comment]
Can you try running ```pip install bs4``` and running blackwidow again? It seems to be working on the latest Kali image fine after running the install.sh from Sn1per, but let me know if you're running a different OS version.

**Comment by 1N3** [comment]
Just checked in a fix for this in the master BlackWidow repo. Can you try re-cloning the repo and re-running the install.sh file? I tested it, and it should work now. Keep me posted.
