### ISSUE TITLE
E unable to locate package theHarvester

### ISSUE THREAD

**Issue by jinconstantine** [1N3/Sn1per#28]
E unable to locate package theHarvester

After doing this in terminal i receive the error but still the installation completed:

sudo su
git clone https://github.com/1N3/Sn1per.git
cd Sn1per
chmod +x install.sh
./install.sh
y

I think this has something to do with "theharvester" being installed by default in Kali Linux

PS: I am using the new Kali_ Rolling Repository in my sources.list and not the OLD Kali-Sana Repository

**Comment by 1N3** [comment]
This is fixed now. Closing out.
