### ISSUE TITLE
IPV6  based target in Cloud issue

### ISSUE THREAD

**Issue by jsankr** [1N3/Sn1per#280]
sniper -t xxxxxxxx.com
Unable to perform IPV6 based targets on Cloud web application servers. 
Getting error from TCP Port Scan, DNS resolution occurs perfectly.

xxxxxxxx.com looks like an IPv6 target specification -- you have to use the -6 option

where do I need to mention this -6 ?

**Comment by 1N3** [comment]
You could try updating your /root/.sniper.conf "NMAP_OPTIONS" setting by adding -6
