### ISSUE TITLE
webscan module clarification

### ISSUE THREAD

**Issue by uday952** [1N3/Sn1per#285]
WEBSCAN: Launches a full HTTP & HTTPS web application scan against via Burpsuite and Arachni. 

What does it mean ? 

burp and arachni will be handled by Sn1per itself, or we have to use the tools ? Canu explain more about the above statement

**Comment by 1N3** [comment]
Arachni comes installed with Sn1per by default, so you can just run 'webscan' mode from Sn1per to start an Arachni scan.

For Burpsuite, use this guide to setup scans:
https://github.com/1N3/Sn1per/wiki/Burpsuite-Professional-2.x-Integration

For Burpsuite to work, it has to be running first and Sn1per will initiate the scan and display the vulnerabilities after.
