### ISSUE TITLE
Add gf-patterns and gau

### ISSUE THREAD

**Issue by dorkerdevil** [1N3/Sn1per#286]
it will be really awesome if gf-patterns and gau will be added

**Comment by 1N3** [comment]
Thanks, will look into gf-patterns. Gua is actually already added to Sn1per and is activated by setting GUA="1" in your /root/.sniper.conf and running any web based scan modes such as "stealth", "web", "webporthttps" ect.

**Comment by 1N3** [comment]
This was added in Sn1per v8.8 which is now public! You can now configure your grep patterns via your /root/.sniper.conf file. 👍
