### ISSUE TITLE
Missing config option in Sn1per Pro

### ISSUE THREAD

**Issue by GraylockInc** [1N3/Sn1per#288]
In the youtube video "Automate OWASP Zap Web Application Scans using Sn1per" there is a drop down feature to select config files. I do not have this, is something else broken?

From the video
![image](https://user-images.githubusercontent.com/70162517/93345326-4cc2b400-f7f8-11ea-9bb5-178fff27aec6.png)

My web console
![image](https://user-images.githubusercontent.com/70162517/93345564-97443080-f7f8-11ea-9276-52e0e3369c63.png)

**Comment by 1N3** [comment]
Hi, 
That feature is still under development and not currently released. There is a disclaimer in the video description, but you would need to view the video description to see it. That feature will likely get released closer towards the end of the year.

**Comment by GraylockInc** [comment]
Gotcha.
