### ISSUE TITLE
Add Interlace support

### ISSUE THREAD

**Issue by GraylockInc** [1N3/Sn1per#289]
It would be great if we could get Interlace support for Nikto and other single threaded applications, I'd work on adding it myself but it says explicitly not to modify the code on Community and Pro or the Pro license will be revoked.

**Comment by 1N3** [comment]
Thanks. Will look into this. 

Just to clarify on the license, any code on Github can be modified and submitted as a PR for possible inclusion in the main branch. All we ask is that the program name and credits aren't removed or changed. Obviously for Pro support/users, we can only support the main github release/branch as other modifications could introduce issues in Pro.

**Comment by GraylockInc** [comment]
With CE 2.0 I think we can close this, that was the result I was looking for, multithreading. :)
