### ISSUE TITLE
The command theharvester is deprecated. Please use theHarvester instead.

### ISSUE THREAD

**Issue by 1N3** [1N3/Sn1per#291]
User reports error "The command theharvester is deprecated. Please use theHarvester instead." in latest Kali build.

**Comment by 1N3** [comment]
This will be fixed in v8.8. In the meantime, the work around is to re-install theharvester:

```
wget https://github.com/laramies/theHarvester/archive/V3.1.tar.gz
tar -zxvf V3.1.tar.gz
rm V3.1.tar.gz
rm -f /usr/bin/theharvester
ln -s /usr/share/sniper/plugins/theHarvester-3.1/theHarvester.py /usr/bin/theharvester
```

**Comment by SabberHossen** [comment]
thanks

**Comment by Kinglfpr** [comment]
buenas tardes un favor aun sale el mismo error en theHarvester
theHarvester 4.2.0                                              *
* Coded by Christian Martorella                                   *
* Edge-Security Research                                          *
* cmartorella@edge-security.com                                   *
*                                                                 *
*******************************************************************
[!] Invalid source.
