### ISSUE TITLE
Port Scanner Option

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#294]
8.8 Pro with all options including Port Scanner.

I see the port scanner does not exist unless you already have a workspace.

I was hoping I could use the Port Scanner to do my initial discovery and add it as a new workspace.

Is there a way?

**Comment by 1N3** [comment]
There's no way to do this completely within the GUI, but you could create an empty workspace (ie. mkdir -p /usr/share/sniper/loot/workspace/<workspace>/). This will allow you to view it in the workspace navigator and initiate the port scanner add-on. Unfortunately, this feature wasn't built into the original design. However, this is something I'll try and work on adding to a future minor version update for the add-on. I will keep you posted on the progress.

**Comment by clive7391** [comment]
Brilliant!

Thank you.
Close
