### ISSUE TITLE
F+ result for CSP Not Enforced

### ISSUE THREAD

**Issue by Oranger1** [1N3/Sn1per#295]
hi!
I met a problem , no matter how to scan by different modes, the result is same.
it make me crazy,  i need some help, thanks!

![image](https://user-images.githubusercontent.com/65127626/98191547-62c93700-1f54-11eb-9cc3-ad4ff5887e17.png)

**Comment by Oranger1** [comment]
![image](https://user-images.githubusercontent.com/65127626/98191790-e551f680-1f54-11eb-8422-cedf79f736a0.png)

**Comment by Oranger1** [comment]
====================================================================================?x[2020-11-05](02:44)x?
====================================================================================
??((?°?..? Sc0pe Vulnerability Report by @xer0dayz ?._.?°?))?? 
====================================================================================
Critical: 0
High: 0
Medium: 0
Low: 0
Info: 1
Score: 1
====================================================================================
P5 - INFO, CSP Not Enforced, http://47.107.84.139:--noreport/, 
====================================================================================
====================================================================================?x[2020-11-05](02:44)x?
 SCAN COMPLETE! 
====================================================================================?x[2020-11-05](02:44)x?


it always display an info leak， i have install 5 environment from vulhub；

**Comment by 1N3** [comment]
Will see if there's a way to eliminate any F+ results in this rule.

**Comment by 1N3** [comment]
This will be fixed in v8.9
