### ISSUE TITLE
I need some help on using sn1per,

### ISSUE THREAD

**Issue by Oranger1** [1N3/Sn1per#296]
i have updated the newest sniper, and now, i only just got some about network vulnerabilities after scan,  and i have installed drone environment contains vulnerabilities, but it is useless,  i can't scan about any vulnerabilities the drone environment. 

maybe somebody can help me?  thanks!!

**Comment by GraylockInc** [comment]
Drone environment? What scans are you thinking, we need more information.

**Comment by Oranger1** [comment]
> Drone environment? What scans are you thinking, we need more information.

I download from vulhub, but i can't get the result contains vulnerabilitiy like cve201717405; 
![image](https://user-images.githubusercontent.com/65127626/98496295-4ee74300-227c-11eb-9527-589d36885572.png)

**Comment by GraylockInc** [comment]
Scans running* autocorrect got me. 

So you're having docker trouble? So when you are saying fine you mean docker environment?

**Comment by Oranger1** [comment]
Sorry, i can't understand about "Scans running* autocorrect got me",it is a command?
yes, docker environment;

**Comment by Oranger1** [comment]
> Scans running* autocorrect got me.
> 
> So you're having docker trouble? So when you are saying drone you mean docker environment?

Thanks for your kind help.r My English is poor so maybe some explaination is not accurate enough.I downloaded some target machine environments with docker,which contain vulnerabilities, but I can't scan those vulnerabilities in the target machine environment with spiner tool.

Sorry, i can't understand about "Scans running* autocorrect got me",it is a command?
yes, docker environment;

**Comment by 1N3** [comment]
Would recommend getting familiar with all Sn1per scan modes and options first (sniper -h). Also get familiar with all configuration options and integrations referenced in the Wiki page here: https://github.com/1N3/Sn1per/wiki to get the most value out of Sn1per. If you have specific questions, let us know.
