### ISSUE TITLE
Web Screenshots Not Working in Ubuntu 2020

### ISSUE THREAD

**Issue by 1N3** [1N3/Sn1per#297]

**Comment by 1N3** [comment]
Was able to get this working by running the following as 'root' on Ubuntu 2020:

```
sudo su
snap install chromium 2> /dev/null
ln -s /snap/bin/chromium /usr/bin/chromium 2> /dev/null
xhost + 2> /dev/null
mkdir -p /run/user/0 2> /dev/null
```

This will be fixed in v8.9.

**Comment by avioren** [comment]
Hi. I want not able to correct the issue with Sn1per Pro 8.8 on Ubuntu 20.04 with this solution.

"snap install chromium 2" throws

error: cannot install "chromium", "2": invalid instance name: invalid snap
       name: "2"

**Comment by 1N3** [comment]
Hi, the correct command is ```snap install chromium``` as root.
