### ISSUE TITLE
E: Unable to locate package php7.4 in Ubuntu 18.04

### ISSUE THREAD

**Issue by 1N3** [1N3/Sn1per#301]
E: Unable to locate package php7.4
E: Couldn't find any package by glob 'php7.4'
E: Couldn't find any package by regex 'php7.4'
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php7.4-curl
E: Couldn't find any package by glob 'php7.4-curl'
E: Couldn't find any package by regex 'php7.4-curl'

**Comment by 1N3** [comment]
To fix, run the following:
```
sudo apt-get update
sudo apt -y install software-properties-common
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
```
Then re-run the activation.sh script again from your Sn1per Professional v8.0 activation email:
```
curl https://xerosecurity.com/pro/8.0/<LICENSE_KEY_HERE>/activation.sh | sudo bash
```

**Comment by amandio-eto** [comment]
how to fix this
Building dependency tree
Reading state information... Done
E: Unable to locate package php7.4
E: Couldn't find any package by glob 'php7.4'
E: Couldn't find any package by regex 'php7.4'
root@server-cacti:~# ^C
