### ISSUE TITLE
Arachni End of Life - Kali 2020.3+

### ISSUE THREAD

**Issue by 1N3** [1N3/Sn1per#303]
Arachni no longer functions on Kali 2020.3+. Recommend using Kali 2020.2 or earlier to avoid conflicts.

**Comment by gbiagomba** [comment]
@1N3 Have you considered switching arachni to either ffuf or nuclei?

**Comment by 1N3** [comment]
Closing this out since Arachni 1.5.1 still seems to work on Kali 2021.3.
