### ISSUE TITLE
Install Pro Over Docker

### ISSUE THREAD

**Issue by Sajibekanti** [1N3/Sn1per#304]
What is the Method to Run Pro Version Over Docker?

System : 
Centos 7

**Comment by 1N3** [comment]
To install Sn1per Professional using Docker, please do the following:

```
docker pull xerosecurity/sn1per
docker run -p 1337:1337 -it xerosecurity/sn1per /bin/bash
```
This will give you a root prompt within the container. 

From here, run the activation.sh script/command you received with your order to install Sn1per Professional. 
```
curl https://xerosecurity.com/pro/8.0/<YOUR_LICENSE_KEY_HERE>/activation.sh | sudo bash
```

After, you can access the web UI by going to https://<DOCKER_IP_HERE>:1337

**Comment by Sajibekanti** [comment]
Completely Setup Done
