### ISSUE TITLE
UDP scan fault.

### ISSUE THREAD

**Issue by JaseNZC** [1N3/Sn1per#307]
Fresh install of Kali and Sn1per.

every scan always returns the following fault during scan. I did notice this happen since the last upgrade.

RUNNING UDP PORT SCAN 
====================================================================================•x[2020-12-17](10:02)x•
Error #486: Your port specifications are illegal.  Example of proper form: "-100,200-1024,T:3000-4000,U:60000-"
QUITTING!

**Comment by 1N3** [comment]
Thanks for the heads up. This will be fixed in v8.9 which is set to be released in the next week or so.

**Comment by 1N3** [comment]
Fixed! Closing out.
