### ISSUE TITLE
Recon flag also doing OSINT stuff

### ISSUE THREAD

**Issue by najum98** [1N3/Sn1per#308]
The -re flag when run solely also starts doing OSINT, like collecting osint from online documents, gathering the harvester osint info etc

I mean they should only run if I explicitly call the -o flag, the commands I am using is: sudo sniper -t https://www.example.com/ -re

**Comment by najum98** [comment]
OSINT was marked "1" in default settings of sniper.conf file

**Comment by 1N3** [comment]
Thanks for the heads up. The OSINT flag should probably be unset/removed from the default conf since it typically gets enabled from the -o switch. Will update this.

**Comment by 1N3** [comment]
Just checked and it looks like OSINT is disabled in the default sniper.conf. Closing out.
