### ISSUE TITLE
SuperMicro-Password-Scanner unable to run after install

### ISSUE THREAD

**Issue by mero01** [1N3/Sn1per#31]
After install SuperMicro-Password-Scanner is not executable so the below error is seen when Sn1per is run "Permission Denied" 

This seems to work as a fix, 

**chmod +x SuperMicro-Password-Scanner/supermicro_scan.sh**

I have submitted a code change to you 

Thanks

**Comment by 1N3** [comment]
Thanks for the heads up! merging into the next release.

**Comment by mero01** [comment]
No Problems Mate! 

Thanks for the hard work.

**Comment by 1N3** [comment]
Checked in the fix in 1.6d!
