### ISSUE TITLE
Scanning using CIDR notation

### ISSUE THREAD

**Issue by dmittakarin8** [1N3/Sn1per#310]
**Describe the bug**
Scanning using CIDR notation

**To Reproduce**
1. Peform a multi target scan with targets using CIDR notation
2. Example is 10.0.0.0/32 or 10.0.0.0/24 
2. No results in workspace
3. Change target to be IP only 10.0.0.1-255
4. Results found in workspace

**Expected behavior**
Can sniper handle cidr notation in a multi target scan or a single target scan?  For large assessments the scope may include cidr notation.  Currently it seems that cidr notation has to be converted to ip ranges for sniper to be able to scan the target range

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser : Firefox
 - Version: Sn1per Professional v8.9

**Comment by 1N3** [comment]
CIDR/Subnet scans are handled via 'discover' mode (ie. sniper -t 10.0.0.0/24 -m discover -w 10.0.0.0).
