### ISSUE TITLE
Issue with some software not working on different Kali versions

### ISSUE THREAD

**Issue by digitizeddude** [1N3/Sn1per#320]
I saw that you mentioned you are using Kali 2020.4 to use Nessus with it. Can you tell me what software from the architectural diagram from here (https://xerosecurity.com/wordpress/documentation/#system-requirements) doesn't work on Kali 2020.4? I tried to rebuild my older kali boxes cause i made the mistake to update/upgrade Kali but it created more of a mess when i tried to install some software. So i'm stuck with a machine that is running 2020.4. 

The issue i'm finding on the Kali 2020.4 machine is that the conf files have changed after the upgrade. The conf files are no longer working for some reason because they changed. For example, vuln scans no longer pull up nessus and for some reason OWASP Zap doesn't launch. I checked the file and some settings were set back to 0. Was this an expected change or a bug whereby i would need to recreate the conf files? Thanks for the help and clarity.

**Comment by 1N3** [comment]
The OpenVAS and Arachni no longer work on Kali 2020.4 and newer. 

As for the confs changing after upgrading to the latest version of Sn1per, this is expected. By default, optional plugins that require 3rd party programs such as Nessus and ZAP are disabled in the conf. However, you can update your /root/.sniper.conf to enable these manually by setting them to "1" which will override the default /usr/share/sniper/sniper.conf options. 

There's been a lot of changes in conf options, so these options had to be overridden in the latest release for compatibility.

**Comment by digitizeddude** [comment]
Understood. Thanks for the info. With the upgrade to Pro 9.0, are there any other conf files that i need to backup? Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 1N3** [comment]
The only confs you may want to backup are any custom confs you created manually and any preferences/options you may have saved to /root/.sniper.conf. Outside of this, Pro v9.0 will use the same options as Pro v8.0 - you'll just have the flexibility to select, edit and save new confs direct from the v9.0 web UI now.

The upgrade should not affect theHarvester as far as I'm aware.

**Comment by digitizeddude** [comment]
Thank you.
