### ISSUE TITLE
Bruteforce with Hydra keeps running even through -b option not chosen

### ISSUE THREAD

**Issue by digitizeddude** [1N3/Sn1per#323]
I ran a standard scan using the following command with Sniper Pro 8: sniper -t domain.com -m normal -w domain.com and for some reason brute force through Hydra is running against the site. Is this an expected result? I've never seen this before so i'm just trying to figure out if the issue is a bug. 
The environment is running on Kali 2020.4 with the lastest version of Sniper and Sniper Pro 8. The command was run through Sniper Pro. 
Thanks

**Comment by 1N3** [comment]
Thanks for the heads up. Looks like this was a bug.. 

You have two options to fix. You can:

1) Set your /root/.sniper.conf "AUTO_BRUTE" setting to "0"

or 

2) You can download the updated /usr/share/sniper/modes/bruteforce.sh in the master repo to replace your existing script

```
rm -f /usr/share/sniper/modes/bruteforce.sh
wget https://raw.githubusercontent.com/1N3/Sn1per/master/modes/bruteforce.sh -O /usr/share/sniper/modes/bruteforce.sh
chmod 775 /usr/share/sniper/modes/bruteforce.sh
```
