### ISSUE TITLE
Error! You need to specify a workspace alias via the -w switch

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#324]
I attempt to begin by selecting a Multi-Target Scan and add 192.168.1.0/24
I leave all other at default
Add the name test to Workspace
Select scan and get a new window with the error "Error! You need to specify a workspace alias via the -w switch"
The workspace is created despite the error.
No scan completed

Select Single Target Scan
Enter target 192.168.1.200
and same thing.

What I discovered is that despite deleting the workspace via Workspace Management (which I attempted to reuse the same workspace name), it generates the error.

So if I delete a workspace "test", I cannot create a new scan with a workspace "test"
I can use workspace "test-2".

A bug?

v9 Pro all add-ons
Kali 2020.4
Firefox

**Comment by 1N3** [comment]
I will address the all issues mentioned, but to start, I want to focus on scanning subnets first. 

To scan subnets with Sn1per, currently the only method is to use 'discover' mode which is still available under the "Single Target" scan mode drop-down (I know... It's actually scanning multiple hosts, but it only passes the -t switch which is a "single" argument switch). Other multi-target modes require a text file with multiple line delimited targets listed. 

That being said, you will need to use 'discover' mode to scan a subnet. 

![subnet-scan1](https://user-images.githubusercontent.com/7894221/105085790-79f8ca80-5a55-11eb-9fba-6f90b0843263.PNG)

**Comment by clive7391** [comment]
I guess I will go back to my script to do multiple cidr
for a in `cat scope.txt`; do sniper -t $a -w $1 -m discover; done;

**Comment by 1N3** [comment]
I'm working on adding this https://github.com/1N3/Sn1per/issues/325 which will do exactly what you're looking for (ie. scan multiple subnets using the multi-host target input box). Hoping to have this in the next version (ie. v9.1).

**Comment by 1N3** [comment]
Regarding the message "Error! You need to specify a workspace alias via the -w switch" and not being able to delete and use the same workspace, I'm not able to reproduce this. 

I launched a new scan (ie. target: 127.0.0.1) with a workspace name of 127.0.0.1. After the scan completes, I delete the workspace using workspace management. Then I re-ran the same scan with same options and the workspace is created without error after. 

If you have any screenshots or any more data, that might help, but I'm not sure what else could be causing this without more info.

**Comment by clive7391** [comment]
It seems as though it is doing it with just that one previous workspace that has been deleted. I don't want to post the WS name but here is the error.
![image](https://user-images.githubusercontent.com/19671719/105109602-d7f3d500-5a8a-11eb-9716-3a3fef3867b3.png)

It may just be a fluke with that old workspace.
