### ISSUE TITLE
Duplicate target: Hostname and IP

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#326]
9 Pro and all add-ons
Kali 2020.4
Firefox

I am conducting a discover scan to determine scope and see far more targets than expected.

When I conduct a discover scan, the targets get populated but I see netbios names or IP addresses. When analyzing, I see a netbios name and a IP entry each for the same target. So this seems to add many more targets than there actually is because everything that resolves a name is counted twice.

Can netbios names be listed on the same line as their IP in another column rather than a separate entry?

**Comment by 1N3** [comment]
Didn't realize it was doing this, but I changed the /usr/share/sniper/modes/discover.sh NMap commands to use the '-n' which disables DNS resolution in the initial discovery scan to fix this. After the initial discover scan, the 'flyover' scan is then performed automatically which will give the reverse DNS of each IP's in a separate column from the web UI report. 

To apply the fix, run the following:
```
rm -f /usr/share/sniper/modes/discover.sh
wget https://raw.githubusercontent.com/1N3/Sn1per/master/modes/discover.sh -O /usr/share/sniper/modes/discover.sh
chmod 775 /usr/share/sniper/modes/discover.sh
```

**Comment by clive7391** [comment]
It seems since I patched the issue, I get no DNS names now. I was hoping to retain the names but have them with their IP and not a separate entry.

**Comment by 1N3** [comment]
You could use the Pro UI to get this. 

![image](https://user-images.githubusercontent.com/7894221/105377344-eeec1180-5bc7-11eb-90e8-4770190a0eae.png)

I did a quick discover scan of a small PayPal /30 to do this. 

From the command line, it would take some code changes and rework.
