### ISSUE TITLE
/usr/share/sniper/sniper.conf: line 4: $'\r': command not found

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#327]
9 Pro all add-ons
Kali 2020.4
Nessus Professional Version 8.13.1

Installed Nessus add-on
tar -zxvf nessus-add-on.tar.gz
sudo bash install-nessus-add-on.sh

Tried a couple of command line scans and had errors.

The following is an example of testing the local device which has Sn1per and Nessus on it. It appears as though it is getting hung up on carriage returns in the conf and calling out to OpenVAS instead of Nessus. I tried with a vulnerable system with the same results.

sniper -t 127.0.0.1 -m vulnscan -w 127.0.0.1
/usr/share/sniper/sniper.conf: line 4: $'\r': command not found
/usr/share/sniper/sniper.conf: line 12: $'\r': command not found
/usr/share/sniper/sniper.conf: line 18: $'\r': command not found
/usr/share/sniper/sniper.conf: line 23: $'\r': command not found
/usr/share/sniper/sniper.conf: line 26: $'\r': command not found
/usr/share/sniper/sniper.conf: line 31: $'\r': command not found
/usr/share/sniper/sniper.conf: line 34: $'\r': command not found
/usr/share/sniper/sniper.conf: line 38: $'\r': command not found
/usr/share/sniper/sniper.conf: line 46: $'\r': command not found
/usr/share/sniper/sniper.conf: line 53: $'\r': command not found
/usr/share/sniper/sniper.conf: line 58: $'\r': command not found
/usr/share/sniper/sniper.conf: line 61: $'\r': command not found
/usr/share/sniper/sniper.conf: line 65: $'\r': command not found
/usr/share/sniper/sniper.conf: line 68: $'\r': command not found
/usr/share/sniper/sniper.conf: line 71: $'\r': command not found
/usr/share/sniper/sniper.conf: line 74: $'\r': command not found
/usr/share/sniper/sniper.conf: line 95: $'\r': command not found
/usr/share/sniper/sniper.conf: line 103: $'\r': command not found
/usr/share/sniper/sniper.conf: line 111: $'\r': command not found
/usr/share/sniper/sniper.conf: line 127: $'\r': command not found
/usr/share/sniper/sniper.conf: line 132: $'\r': command not found
/usr/share/sniper/sniper.conf: line 137: $'\r': command not found
/usr/share/sniper/sniper.conf: line 141: $'\r': command not found
/usr/share/sniper/sniper.conf: line 145: $'\r': command not found
/usr/share/sniper/sniper.conf: line 148: $'\r': command not found
/usr/share/sniper/sniper.conf: line 154: $'\r': command not found
/usr/share/sniper/sniper.conf: line 168: $'\r': command not found
/usr/share/sniper/sniper.conf: line 184: $'\r': command not found
/usr/share/sniper/sniper.conf: line 189: $'\r': command not found
/usr/share/sniper/sniper.conf: line 210: $'\r': command not found
/usr/share/sniper/sniper.conf: line 219: $'\r': command not found
/usr/share/sniper/sniper.conf: line 222: $'\r': command not found
]Kniper.conf guration file from /usr/share/sniper
[*] Loaded configuration file from /root/.sniper.conf [OK]
[*] Saving loot to /usr/share/sniper/loot/workspace/127.0.0.1 [OK]
[*] Scanning 127.0.0.1 [OK]
[*] Saving loot to /usr/share/sniper/loot/workspace/127.0.0.1 [OK]
/usr/share/sniper/sniper.conf: line 4: $'\r': command not found
/usr/share/sniper/sniper.conf: line 12: $'\r': command not found
/usr/share/sniper/sniper.conf: line 18: $'\r': command not found
/usr/share/sniper/sniper.conf: line 23: $'\r': command not found
/usr/share/sniper/sniper.conf: line 26: $'\r': command not found
/usr/share/sniper/sniper.conf: line 31: $'\r': command not found
/usr/share/sniper/sniper.conf: line 34: $'\r': command not found
/usr/share/sniper/sniper.conf: line 38: $'\r': command not found
/usr/share/sniper/sniper.conf: line 46: $'\r': command not found
/usr/share/sniper/sniper.conf: line 53: $'\r': command not found
/usr/share/sniper/sniper.conf: line 58: $'\r': command not found
/usr/share/sniper/sniper.conf: line 61: $'\r': command not found
/usr/share/sniper/sniper.conf: line 65: $'\r': command not found
/usr/share/sniper/sniper.conf: line 68: $'\r': command not found
/usr/share/sniper/sniper.conf: line 71: $'\r': command not found
/usr/share/sniper/sniper.conf: line 74: $'\r': command not found
/usr/share/sniper/sniper.conf: line 95: $'\r': command not found
/usr/share/sniper/sniper.conf: line 103: $'\r': command not found
/usr/share/sniper/sniper.conf: line 111: $'\r': command not found
/usr/share/sniper/sniper.conf: line 127: $'\r': command not found
/usr/share/sniper/sniper.conf: line 132: $'\r': command not found
/usr/share/sniper/sniper.conf: line 137: $'\r': command not found
/usr/share/sniper/sniper.conf: line 141: $'\r': command not found
/usr/share/sniper/sniper.conf: line 145: $'\r': command not found
/usr/share/sniper/sniper.conf: line 148: $'\r': command not found
/usr/share/sniper/sniper.conf: line 154: $'\r': command not found
/usr/share/sniper/sniper.conf: line 168: $'\r': command not found
/usr/share/sniper/sniper.conf: line 184: $'\r': command not found
/usr/share/sniper/sniper.conf: line 189: $'\r': command not found
/usr/share/sniper/sniper.conf: line 210: $'\r': command not found
/usr/share/sniper/sniper.conf: line 219: $'\r': command not found
/usr/share/sniper/sniper.conf: line 222: $'\r': command not found
]Kniper.conf guration file from /usr/share/sniper
[*] Loaded configuration file from /root/.sniper.conf [OK]
[*] Saving loot to /usr/share/sniper/loot/workspace/127.0.0.1 [OK]
[*] Scanning 127.0.0.1 [OK]
                ____               
    _________  /  _/___  ___  _____
   / ___/ __ \ / // __ \/ _ \/ ___/
  (__  ) / / // // /_/ /  __/ /    
 /____/_/ /_/___/ .___/\___/_/     
               /_/                 

 + -- --=[ https://xerosecurity.com
 + -- --=[ Sn1per v9.0 by @xer0dayz

====================================================================================•x[2021-01-20](08:11)x•
 RUNNING OPENVAS VULNERABILITY SCAN 
====================================================================================•x[2021-01-20](08:11)x•
Scanning target: 127.0.0.1 

-----------------------------------------------
Listing OpenVAS version...
-----------------------------------------------
modes/vulnscan.sh: line 49: omp: command not found

Listing OpenVAS targets...
-----------------------------------------------
modes/vulnscan.sh: line 53: omp: command not found

Listing OpenVAS tasks...
-----------------------------------------------
modes/vulnscan.sh: line 57: omp: command not found

Creating scan task...
-----------------------------------------------
modes/vulnscan.sh: line 61: omp: command not found
-:1.1: Document is empty

^
modes/vulnscan.sh: line 63: omp: command not found
modes/vulnscan.sh: line 69: omp: command not found
-:1.1: Document is empty

^
modes/vulnscan.sh: line 73: omp: command not found
REPORT_ID: 
modes/vulnscan.sh: line 75: omp: command not found

No report ID found. Listing scan tasks:
modes/vulnscan.sh: line 92: omp: command not found
====================================================================================•x[2021-01-20](08:11)x•
 RUNNING SC0PE WEB VULNERABILITY SCAN 
====================================================================================•x[2021-01-20](08:11)x•
====================================================================================•x[2021-01-20](08:11)x•
 RUNNING SC0PE NETWORK VULNERABILITY SCAN 
====================================================================================•x[2021-01-20](08:11)x•
====================================================================================•x[2021-01-20](08:11)x•
====================================================================================
•?((¯°·..• Sc0pe Vulnerability Report by @xer0dayz •._.·°¯))؟• 
====================================================================================
Critical: 0
High: 0
Medium: 0
Low: 0
Info: 0
Score: 0
====================================================================================
====================================================================================
====================================================================================•x[2021-01-20](08:11)x•
 SCAN COMPLETE! 
====================================================================================•x[2021-01-20](08:11)x•
                ____               
    _________  /  _/___  ___  _____
   / ___/ __ \ / // __ \/ _ \/ ___/
  (__  ) / / // // /_/ /  __/ /    
 /____/_/ /_/___/ .___/\___/_/     
               /_/                 

[*] Opening loot directory /usr/share/sniper/loot/workspace/127.0.0.1 [OK]
 + -- --=[ Generating reports...
[|]
 + -- --=[ Sorting all files...
 + -- --=[ Removing blank screenshots and files...
 + -- --=[ Generating Sn1per Professional reports...
 + -- --=[ Generating CSV Report... 
[|]
[*] To access the local web interface, go to https://127.0.0.1:1337 
[*] To access the remote web interface, go to https://YOUR.IP.HERE:1337 
[*] The username to login is 'admin' 
[*] The password is the password you set when you installed Sn1per Professional 
 + -- --=[ Done!

**Comment by 1N3** [comment]
I put in some added code to prevent this, but try running ```dos2unix /usr/share/sniper/sniper.conf``` and running again.

**Comment by 1N3** [comment]
You can also apply the patch by running the following:
```
rm -f /usr/share/sniper/modes/discover.sh
wget https://raw.githubusercontent.com/1N3/Sn1per/master/sniper -O /usr/share/sniper/sniper
chmod 4775 /usr/share/sniper/sniper
```

**Comment by 1N3** [comment]
Also, you will need to follow this guide to configure and enable Nessus https://github.com/1N3/Sn1per/wiki/Nessus-Integration

If you're not using OpenVAS, you can disable it in your /root/.sniper.conf or create a conf template to call at the command line with these options saved https://github.com/1N3/Sn1per/wiki/Sn1per-Configuration-Templates

**Comment by clive7391** [comment]
I did follow the Nessus guide for the install and double checked the /root/.sniper.conf

I patched as you asked but I am receiving invalid credentials. I validate from copying from /root/.sniper.conf to the GUI and they work.

Also 
# OPENVAS CONFIG
OPENVAS="0"


sniper -t 127.0.0.1 -m vulnscan -w 127.0.0.1
[*] Loaded configuration file from /usr/share/sniper/sniper.conf [OK]
[*] Loaded configuration file from /root/.sniper.conf [OK]
[*] Saving loot to /usr/share/sniper/loot/workspace/127.0.0.1 [OK]
[*] Scanning 127.0.0.1 [OK]
[*] Checking for active internet connection [OK]
[*] Saving loot to /usr/share/sniper/loot/workspace/127.0.0.1 [OK]
[*] Loaded configuration file from /usr/share/sniper/sniper.conf [OK]
[*] Loaded configuration file from /root/.sniper.conf [OK]
[*] Saving loot to /usr/share/sniper/loot/workspace/127.0.0.1 [OK]
[*] Scanning 127.0.0.1 [OK]
                ____               
    _________  /  _/___  ___  _____
   / ___/ __ \ / // __ \/ _ \/ ___/
  (__  ) / / // // /_/ /  __/ /    
 /____/_/ /_/___/ .___/\___/_/     
               /_/                 

 + -- --=[ https://xerosecurity.com
 + -- --=[ Sn1per v9.0 by @xer0dayz

====================================================================================•x[2021-01-20](12:06)x•
 RUNNING NESSUS VULNERABILITY SCAN 
====================================================================================•x[2021-01-20](12:06)x•
[*] Grabbing API key...
7A2C4A96-4AEE-4706-9617-2EF643532628
[*] Logging in...
[*] Session ID: Invalid Credentials
[*] Scan policies:
[*] Adding target (127.0.0.1)...

[*] Starting scan...
{"error":"Invalid Credentials"}
[*] Status: 
An error occured: 
====================================================================================•x[2021-01-20](12:07)x•
 RUNNING SC0PE WEB VULNERABILITY SCAN 
====================================================================================•x[2021-01-20](12:07)x•
====================================================================================•x[2021-01-20](12:07)x•
 RUNNING SC0PE NETWORK VULNERABILITY SCAN 
====================================================================================•x[2021-01-20](12:07)x•
====================================================================================•x[2021-01-20](12:07)x•
====================================================================================
•?((¯°·..• Sc0pe Vulnerability Report by @xer0dayz •._.·°¯))؟• 
====================================================================================
Critical: 0
High: 0
Medium: 0
Low: 0
Info: 0
Score: 0
====================================================================================
====================================================================================
====================================================================================•x[2021-01-20](12:07)x•
 SCAN COMPLETE! 
====================================================================================•x[2021-01-20](12:07)x•
                ____               
    _________  /  _/___  ___  _____
   / ___/ __ \ / // __ \/ _ \/ ___/
  (__  ) / / // // /_/ /  __/ /    
 /____/_/ /_/___/ .___/\___/_/     
               /_/                 

[*] Opening loot directory /usr/share/sniper/loot/workspace/127.0.0.1 [OK]
 + -- --=[ Generating reports...
[||||]
 + -- --=[ Sorting all files...
 + -- --=[ Removing blank screenshots and files...
 + -- --=[ Generating Sn1per Professional reports...
 + -- --=[ Generating CSV Report... 
[|]
[*] To access the local web interface, go to https://127.0.0.1:1337 
[*] To access the remote web interface, go to https://YOUR.IP.HERE:1337 
[*] The username to login is 'admin' 
[*] The password is the password you set when you installed Sn1per Professional 
 + -- --=[ Done!

**Comment by clive7391** [comment]
That should probably be 775 instead of
chmod 4775 /usr/share/sniper/sniper
??

**Comment by clive7391** [comment]
Version 8.13.1 (#257) LINUX

I am not using admin but a specific username which I also added to .conf.

Does it have to be user admin?

**Comment by clive7391** [comment]
So I deleted the username account and made the account admin and still invalid credentials.

Is there a debug way to see what it doesn't like?

Is it the API?

sniper -t 127.0.0.1 -m vulnscan -w 127.0.0.1
[*] Loaded configuration file from /usr/share/sniper/sniper.conf [OK]
[*] Loaded configuration file from /root/.sniper.conf [OK]
[*] Saving loot to /usr/share/sniper/loot/workspace/127.0.0.1 [OK]
[*] Scanning 127.0.0.1 [OK]
[*] Checking for active internet connection [OK]
[*] Saving loot to /usr/share/sniper/loot/workspace/127.0.0.1 [OK]
[*] Loaded configuration file from /usr/share/sniper/sniper.conf [OK]
[*] Loaded configuration file from /root/.sniper.conf [OK]
[*] Saving loot to /usr/share/sniper/loot/workspace/127.0.0.1 [OK]
[*] Scanning 127.0.0.1 [OK]
                ____               
    _________  /  _/___  ___  _____
   / ___/ __ \ / // __ \/ _ \/ ___/
  (__  ) / / // // /_/ /  __/ /    
 /____/_/ /_/___/ .___/\___/_/     
               /_/                 

 + -- --=[ https://xerosecurity.com
 + -- --=[ Sn1per v9.0 by @xer0dayz

====================================================================================•x[2021-01-20](20:31)x•
 RUNNING NESSUS VULNERABILITY SCAN 
====================================================================================•x[2021-01-20](20:31)x•
[*] Grabbing API key...
7A2C4A96-4AEE-4706-9617-2EF643532628
[*] Logging in...
[*] Session ID: Invalid Credentials
[*] Scan policies:
[*] Adding target (127.0.0.1)...

[*] Starting scan...
{"error":"Invalid Credentials"}
[*] Status: 
An error occured:

**Comment by clive7391** [comment]
It didn't like the complex password. LOL

Even in quotes, N3$$u$!! wasn't liked.

Now I have to test one better than password :/

Working!

**Comment by clive7391** [comment]
So is it possible to choose a different Nessus scan policy? I assume it would be set in the config?

Also, I could set 3 different conf's to: 
scan top 100 ports with vulners
scan remaining ~ 65400 ports (TCP top UDP)
Conduct a vuln scan

maybe take it further and import .xml into Metasploit
Run enum4linux on 445?

**Comment by 1N3** [comment]
> 
> 
> It didn't like the complex password. LOL
> 
> Even in quotes, N3$$u$!! wasn't liked.
> 
> Now I have to test one better than password :/
> 
> Working!

Glad to hear it's working now!

Regarding use of complex passwords, I think a simple fix is to change the sniper.conf to use single quotes instead of double quotes for the NESSUS_PASSWORD value:

```
NESSUS_PASSWORD='N3$$u$!!'
```

**Comment by 1N3** [comment]
> 
> 
> So is it possible to choose a different Nessus scan policy? I assume it would be set in the config?
> 

I haven't tested with other custom policies, but if you know the policy ID you want to select, you could try changing the conf to use a different policy ID. I also opened a feature request to look into this for future versions here: https://github.com/1N3/Sn1per/issues/328

> Also, I could set 3 different conf's to:
> scan top 100 ports with vulners
> scan remaining ~ 65400 ports (TCP top UDP)
> Conduct a vuln scan
> 
> maybe take it further and import .xml into Metasploit
> Run enum4linux on 445?

Yes. All possible with conf templates.
