### ISSUE TITLE
No screenshots, renderer binary could not have been found in your current PATH environment variable

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#329]
9Pro all add-ons
Kali 2020.4

Conducted a Discover scan of Internal and external hosts. May have 80, 443.

There are no screenshots in the output.

Ran a deep recon and noticed this error that may be the reason.

webscreenshot.py version 2.2.1

[+] 1 URLs to be screenshot
[ERROR][http://XX.XX.30.1:8008] renderer binary could not have been found in your current PATH environment variable, exiting
[+] 0 actual URLs screenshot
[+] 1 error(s)

**Comment by 1N3** [comment]
webscreenshot.py uses chromium. Try running ```apt-get install -y chromium``` and then running ```python2 /usr/share/sniper/bin/webscreenshot.py -r chromium https://target.com:port```

Alternatively, you could also try using cutycapt as an alternative if that doesn't work.
```
cutycapt --url=http://TARGET:port --out=TARGET.jpg --insecure --max-wait=5000 2> /dev/null
```

**Comment by clive7391** [comment]
E: Package 'chromium' has no installation candidate

Well I was hoping this would have worked out of the box. Lots of bugs.

**Comment by clive7391** [comment]
Actually Chromium is installed by default.

**Comment by clive7391** [comment]
Another scan revealed them but nothing was changed. Hmmm
