### ISSUE TITLE
Recon scan stuck

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#331]
9 Pro all addons
Kali 2020.4

Started recon on 8 external IPs

Running scan: cat /usr/share/sniper/loot/workspace/MAI/domains/custom-targets.txt | xargs -P 10 -r -n 1 -I '{}' sudo sniper -t '{}' -c /usr/share/sniper/conf/deep_active_recon -w MAI

Not sure where it is but here is the output
[*] To access the local web interface, go to https://127.0.0.1:1337
[*] To access the remote web interface, go to https://YOUR.IP.HERE:1337
[*] The username to login is 'admin'
[*] The password is the password you set when you installed Sn1per Professional
+ -- --=[ Done!
[*] To access the local web interface, go to https://127.0.0.1:1337
[*] To access the remote web interface, go to https://YOUR.IP.HERE:1337
[*] The username to login is 'admin'
[*] The password is the password you set when you installed Sn1per Professional
[*] To access the local web interface, go to https://127.0.0.1:1337
[*] To access the remote web interface, go to https://YOUR.IP.HERE:1337
[*] The username to login is 'admin'
[*] The password is the password you set when you installed Sn1per Professional
+ -- --=[ Done!
+ -- --=[ Done!
[STATUS] 2.09 tries/min, 274 tries in 02:11h, 12 to do in 00:06h, 1 active
[STATUS] 2.08 tries/min, 274 tries in 02:12h, 12 to do in 00:06h, 1 active

SNIP

[STATUS] 0.26 tries/min, 274 tries in 17:38h, 12 to do in 00:47h, 1 active
[STATUS] 0.26 tries/min, 274 tries in **17:39h**, 12 to do in 00:47h, 1 active

**Comment by 1N3** [comment]
Please email support@xerosecurity.com for assistance with Sn1per Professional so we can assist you there. This appears to relate to Sn1per Professional and not the Community Edition.
