### ISSUE TITLE
Right pane blacked out

### ISSUE THREAD

**Issue by clive7391** [1N3/Sn1per#332]
9 Pro
Kali 2020.4

Ran a discover scan.
Attempt to click on a target and the right pane goes black. Some other options on the left such as screenshots, vulns and creds work.

Even if I right click on the target and open in new tab, black screen.

Restarted apache, restarted system.

![image](https://user-images.githubusercontent.com/19671719/105507657-78b7df80-5c99-11eb-84bd-853eda495c77.png)

**Comment by clive7391** [comment]
Thanks for the email.

I cleared the cache in both Firefox browsers (using 127.0.0.1 and remote same lan).
No luck.

Ran  the commands 
wget... to update host report file and now it is not blank but eh, look

![image](https://user-images.githubusercontent.com/19671719/105551358-a2d8c400-5cd0-11eb-9d7c-b63544c4bf4a.png)

**Comment by 1N3** [comment]
Please email support@xerosecurity.com for assistance with Sn1per Professional so we can assist you there. This appears to relate to Sn1per Professional and not the Community Edition.
