### ISSUE TITLE
Issue with Zap integration

### ISSUE THREAD

**Issue by digitizeddude** [1N3/Sn1per#333]
I've got a weird error that i've never seen before and i'm not sure if it is a bug. Error below:
 RUNNING OWASP ZAP SCAN 
====================================================================================•x[2021-01-24](22:44)x•
[i] Scanning: http://testfire.net/
Traceback (most recent call last):
  File "/usr/share/sniper/bin/zap-scan.py", line 20, in <module>
    from zapv2 import ZAPv2
ModuleNotFoundError: No module named 'zapv2'
grep: /usr/share/sniper/bin/zap-report.txt: No such file or directory
[i] Scan complete.
[+] Report saved to: /usr/share/sniper/loot/workspace/testfire.net/web/zap-report-testfire.net-http-202101242244.html
[i] Scanning: https://testfire.net/
Traceback (most recent call last):
  File "/usr/share/sniper/bin/zap-scan.py", line 20, in <module>
    from zapv2 import ZAPv2
ModuleNotFoundError: No module named 'zapv2'
grep: /usr/share/sniper/bin/zap-report.txt: No such file or directory
[i] Scan complete.
[+] Report saved to: /usr/share/sniper/loot/workspace/testfire.net/web/zap-report-testfire.net-https-202101242244.html

I have made all of the changes based on the zap integration details on the sn1per website but i get the error above.
I'm running Kali 2020.4
Zap 2.10.0
Sniper version 9.0
Sniper Pro 8

Command i ran was: sniper -t testfire.net -m webscan -w testfire.net

Thanks

**Comment by digitizeddude** [comment]
By the way, i had ZAP open while running the webscan and i couldn't see any activity on ZAP because this error comes up. Thx

**Comment by 1N3** [comment]
The error message is ModuleNotFoundError: No module named 'zapv2'

You will need to run ```pip3 install python-owasp-zap-v2.4``` as referenced in [https://github.com/1N3/Sn1per/wiki/OWASP-ZAP-Integration](https://github.com/1N3/Sn1per/wiki/OWASP-ZAP-Integration) to fix this.

**Comment by digitizeddude** [comment]
Zap is good now when running the command through terminal.
