### ISSUE TITLE
Webscan not working for Burp Suite Professional

### ISSUE THREAD

**Issue by digitizeddude** [1N3/Sn1per#334]
I have run the command: sniper -t testfire.net -m webscan -w testfire.net and i get no results from BurpSuite. I've followed the integration instructions and manual runs of Burp Suite Pro are fine.
Kali 2020.4
Burp Suite Professional 2020.12.1, build 5278
Sniper version 9.0
Sniper Pro 8

Thanks.

**Comment by digitizeddude** [comment]
I managed to get burp to work but i get this as part of the results:

jq: error (at <stdin>:0): Cannot iterate over null (null)

Is this an expected error?

**Comment by 1N3** [comment]
It sounds like there's a null value being parsed which is fine. I could turn off/down verbose logging, but the results should not be affected.

**Comment by digitizeddude** [comment]
Thanks. I appreciate the clarification.
