### ISSUE TITLE
Question - is it possible to access the UI on localhost using the community edition?

### ISSUE THREAD

**Issue by ben-gy** [1N3/Sn1per#337]
Apologies. I'm not sure if this is the right place to be asking this question.

The documentation and demo video showcases a UI that can be accessed to view the scan results. I can't see anywhere in the documentation that references how I can access the UI. Can you please point me in the right direction? Once I've worked it out I can submit a PR to update the readme if that's helpful.

**Comment by 1N3** [comment]
Hi, the UI is part of Sn1per Professional which requires a license from xerosecurity.com to access. The community edition is strictly command line driven. Hope that helps.
