### ISSUE TITLE
Sniper V update?

### ISSUE THREAD

**Issue by GraylockInc** [1N3/Sn1per#339]
I ran Sniper earlier and it asked to update to the new version and it threw out a bunch of errors.

What is Sniper V and why is there no mention of it?

**Comment by GraylockInc** [comment]
![image](https://user-images.githubusercontent.com/70162517/111544372-5e066200-8742-11eb-83f7-5143d5342c13.png)

**Comment by 1N3** [comment]
Thanks for the heads up. Will look into this... 

I believe this may have been a temporary glitch (ie. if the site doesn't respond quick enough or is down at the time of the update check), you will get this. I'll look into adding a better failure check in v9.2.
