### ISSUE TITLE
Implement Slack C2 Functionality

### ISSUE THREAD

**Issue by GraylockInc** [1N3/Sn1per#342]
Has the new Slack API integration for free / Pro been implemented yet?

**Comment by 1N3** [comment]
Yes. You should be able to follow this guide to set it up: https://github.com/1N3/Sn1per/wiki/Slack-API-Integration

**Comment by GraylockInc** [comment]
Thanks for making sure it was still current info! :)

**Comment by GraylockInc** [comment]
Reopening this topic with a relevant question.

Is there the ability or can a Pro extension be built to use Slack as a Command and Control option?

**Comment by 1N3** [comment]
Not currently, but definitely something we can open or change to a feature request to track.

**Comment by Ma1572** [comment]
> Has the new Slack API integration for free / Pro been implemented yet?

**Comment by 1N3** [comment]
Yes. You should be able to follow this guide to set it up: https://github.com/1N3/Sn1per/wiki/Slack-API-Integration
