### ISSUE TITLE
openvas

### ISSUE THREAD

**Issue by ansh6438** [1N3/Sn1per#347]
Hello to all,

I'm having problems using openvas from the docker image, could you help me? When I use gvm-check-setup there is an error message about the redis socket but it seems that to initialize it I have to use systemd and the container seems to start with init.

Could you help me ?

thanks a lot

**Comment by 1N3** [comment]
https://github.com/1N3/Sn1per/wiki/OpenVAS-Integration - Sn1per only supports OpenVAS 7.0.
