### ISSUE TITLE
WPScan Plugin Not Working

### ISSUE THREAD

**Issue by asf-framework-bmg** [1N3/Sn1per#354]
Although the WPscan API key is configured in /root/.sniper_api_keys.conf & option is set to 1 in /root/.sniper.conf.

When running the web scan with command " sniper -t website.com -m web -w website.com", the scan  get the error message in the scan "Scan Aborted: Update required, you can not run a scan if a database file is missing" but WPscan works fine on running the wpscan commands. Using latest version of kali

**Comment by asf-framework-bmg** [comment]
Also running from a kali box, get the error message in the scan "Scan Aborted: Update required, you can not run a scan if a database file is missing" but WPscan works fine on running the wpscan commands

**Comment by blackstone250** [comment]
Hello,

Yes, same here. 
Sn1per should native import all the app that'll use to avoid issues. 
I suggest the following steps:

**_Remove all wpscan package related_:**
sudo apt-get remove wpscan
sudo apt-get remove --auto-remove wpscan
sudo apt-get purge wpscan  
udo apt-get purge --auto-remove wpscan  
gem uninstall wpscan

**_Install Requirements & Wpscan:_**
sudo apt install gnupg2
sudo apt-add-repository -y ppa:rael-gc/rvm
sudo apt-get install rvm -y
reboot (Mandatory reboot)
sudo usermod -a -G rvm "your_username"
rvm user gemsets
rvm install ruby
sudo gem install rails
rvm all do gem update --system (without sudo)
sudo apt install ruby-full -y
sudo apt-get install libcurl4-openssl-dev libxml2 libxml2-dev libxslt1-dev ruby-dev build-essential libgmp-dev zlib1g-dev -y
git clone https://github.com/wpscanteam/wpscan.git
cd wpscan
sudo gem install bundler && bundle install --without test
sudo gem install wpscan
gem update wpscan
sudo wpscan --update

**Comment by asf-framework-bmg** [comment]
Thats great that worked for me!

**Comment by blackstone250** [comment]
Thank you for your reply! It's greateful and Usefull your opinion!

There's a missing command i have added "bundle install (without sudo)"
In your case you can complete the secuence and add aditional components you can do: 
cd wpscan
bundle install (without sudo)

**Comment by 1N3** [comment]
This will be fixed in the next public release of Sn1per. In the meantime, running wpscan --update should do the trick.
