### ISSUE TITLE
Scans Crashing When Black Widow Enabled

### ISSUE THREAD

**Issue by asf-framework-bmg** [1N3/Sn1per#356]
![image](https://user-images.githubusercontent.com/66023460/128017592-fb6f51f4-c977-4bf9-9a63-4d6504e47e77.png)

Scans crashing pausing when blackwidow is enabled, scan works fine when black widow is disabled in Sn1per config.

Using Kali box

**Comment by blackstone250** [comment]
Hi, 

**_Remove all wpscan package related (if possible)_**
sudo apt-get remove blackwidow
sudo apt-get remove black-widow
sudo apt-get remove --auto-remove blackwidow
sudo apt-get remove --auto-remove black-widow
sudo apt-get purge blackwidow
sudo apt-get purge black-widow
sudo apt-get purge --auto-remove blackwidow
sudo apt-get purge --auto-remove black-widow
gem uninstall blackwidow
gem uninstall black-widow

**_Install Requirements & BlackWidow_**
sudo add-apt-repository ppa:offensive-hub/black-widow
sudo apt-get update
sudo apt-get install black-widow
pip3 install black-widow

**Comment by 1N3** [comment]
Hi, does this happen for all sites or just specific websites? Do you have a test URL/example you could share that is causing the error?
