### ISSUE TITLE
Insecure permissions (777) recursively set on installation directory and all files after running main script allow privilege escalation/code execution as root

### ISSUE THREAD

**Issue by nikip72** [1N3/Sn1per#358]
Sn1per v.90 free edition, Ubuntu 21.04

Installation directory permissions before first run of the script:

root@snipertest:~# ls -la /usr/share/sniper/
total 6668
drwxrwxrwx  10 root root    4096 Aug 16 19:19 .
drwxr-xr-x 222 root root   12288 Aug 16 19:41 ..
-rw-r--r--   1 root root   36518 Aug 16 18:33 CHANGELOG.md
-rw-r--r--   1 root root    1269 Aug 16 18:33 Dockerfile
-rw-r--r--   1 root root     306 Aug 16 18:33 LICENSE.md
-rw-r--r--   1 root root   11697 Aug 16 18:33 README.md
-rw-r--r--   1 root root 6491364 Aug 16 18:33 Sn1per.gif
-rw-r--r--   1 root root  159147 Aug 16 18:33 Sn1per.jpg
drwxr-xr-x   2 root root    4096 Aug 16 18:33 bin
drwxr-xr-x   2 root root    4096 Aug 16 19:41 conf
-rwxr-xr-x   1 root root   11548 Aug 16 18:33 install.sh
drwxr-xr-x   9 root root    4096 Aug 16 19:42 loot
drwxr-xr-x   2 root root    4096 Aug 16 18:33 modes
drwxr-xr-x  43 root root    4096 Aug 16 19:27 plugins
drwxr-xr-x   2 root root    4096 Aug 16 18:33 pro
-rw-r--r--   1 root root     276 Aug 16 18:33 sn1per.desktop
-rw-r--r--   1 root root    4283 Aug 16 18:33 sn1per.png
-rwxr-xr-x   1 root root   28290 Aug 16 18:33 sniper
-rw-r--r--   1 root root    9752 Aug 16 18:33 sniper.conf
drwxr-xr-x   4 root root    4096 Aug 16 18:33 templates
-rwxr-xr-x   1 root root     980 Aug 16 18:33 uninstall.sh
drwxr-xr-x   2 root root    4096 Aug 16 18:33 wordlists

Running sn1per:

root@snipertest:~# sniper -t 192.168.1.1
[*] Loaded configuration file from /usr/share/sniper/sniper.conf [OK]
[*] Loaded configuration file from /root/.sniper.conf [OK]
[*] Saving loot to /usr/share/sniper/loot/ [OK]
[*] Scanning 192.168.1.1 [OK]
...
[*] Opening loot directory /usr/share/sniper/loot/workspace/192.168.1.1 [OK]
 + -- --=[ Generating reports...
[snip]
 + -- --=[ Sorting all files...
 + -- --=[ Removing blank screenshots and files...
 + -- --=[ Sn1per Professional is not installed. To download Sn1per Professional, go to https://xerosecurity.com.
 + -- --=[ Done!

Permissions on installation directory after script finishes:

root@snipertest:~# ls -la /usr/share/sniper/
total 6668
drwxrwxrwx  10 root root    4096 Aug 16 20:30 .
drwxr-xr-x 222 root root   12288 Aug 16 19:41 ..
-rwxrwxrwx   1 root root   36518 Aug 16 18:33 CHANGELOG.md
-rwxrwxrwx   1 root root    1269 Aug 16 18:33 Dockerfile
-rwxrwxrwx   1 root root     306 Aug 16 18:33 LICENSE.md
-rwxrwxrwx   1 root root   11697 Aug 16 18:33 README.md
-rwxrwxrwx   1 root root 6491364 Aug 16 18:33 Sn1per.gif
-rwxrwxrwx   1 root root  159147 Aug 16 18:33 Sn1per.jpg
drwxrwxrwx   2 root root    4096 Aug 16 18:33 bin
drwxrwxrwx   2 root root    4096 Aug 16 19:41 conf
-rwxrwxrwx   1 root root   11548 Aug 16 18:33 install.sh
drwxrwxrwx  16 root root    4096 Aug 16 20:30 loot
drwxrwxrwx   2 root root    4096 Aug 16 18:33 modes
drwxrwxrwx  43 root root    4096 Aug 16 19:27 plugins
drwxrwxrwx   2 root root    4096 Aug 16 18:33 pro
-rwxrwxrwx   1 root root     276 Aug 16 18:33 sn1per.desktop
-rwxrwxrwx   1 root root    4283 Aug 16 18:33 sn1per.png
-rwsrwxrwx   1 root root   28290 Aug 16 18:33 sniper
-rwxrwxrwx   1 root root    9752 Aug 16 20:30 sniper.conf
drwxrwxrwx   4 root root    4096 Aug 16 18:33 templates
-rwxrwxrwx   1 root root     980 Aug 16 18:33 uninstall.shuser
drwxrwxrwx   2 root root    4096 Aug 16 18:33 wordlists

Issue:

Lines 464-466 from init function from main script:

  chmod 777 -Rf $INSTALL_DIR 2> /dev/null
  chown root $INSTALL_DIR/sniper 2> /dev/null
  chmod 4777 $INSTALL_DIR/sniper 2> /dev/null

**Comment by 1N3** [comment]
This is by design to allow all users to access Sn1per data and run scans despite not being root. The flat text files should not be overly sensitive in nature, so it's less of a concern. 

If you're running Sn1per in a multi-user environment where the other user's cannot be trusted (which should be very rare), you can run Sn1per in Docker which containerizes the installation from other users on the system. Alternatively, you can update the script/source code to modify the permissions (not recommended, but is an option...).
