### ISSUE TITLE
Trying to run a stealth scan but Nmap is taking a really long time.

### ISSUE THREAD

**Issue by digitizeddude** [1N3/Sn1per#361]
I'm scanning a website that has Sucuri as its WAF. I'm trying to do a full port stealth scan and nmap is taking long. I ran it off command line:
sniper -t www.website.com -m stealth -o -c /root/.sniper.conf -w website.com

What adjustment can i make so that i'm less likely to get blocked by Sucuri/WAF and actually finish the scan in a timely manner. I'm also using protonvpn to scan from in case that matters. 

This is where it stands now using Sniper and it is taking some time. I would presume that Sucuri has already started to rate limit me and that's why i've already tried to use a different server to scan from using ProtonVPN. The results are still as per below: 

Stats: 1:17:20 elapsed; 0 hosts completed (1 up), 1 undergoing Service Scan
Service scan Timing: About 0.61% done

However, when i run nmap -sA www.website.com  
I get a response and manage to see port information. 

As far as the environment goes:
PRETTY_NAME="Kali GNU/Linux Rolling"
VERSION="2021.1"
VERSION_ID="2021.1"
Sniper SE v9.2
Sniper Pro

Any help would be great. 

Thank you.

**Comment by 1N3** [comment]
Looks like we already answered over email, but leaving the response here for record as well:

You will need to change your sniper.conf NMAP_OPTIONS settings to reflect the NMap switches you want to use for the scan and reference that conf when running the scan.
