### ISSUE TITLE
Urgent! Important! New download link doesn't shown scans in the web interface

### ISSUE THREAD

**Issue by blackstone250** [1N3/Sn1per#365]
Hello,

I have reinstalled clean OS Kali Linux 2021.3 / Ubuntu 20.04.3 LTS with the new download domain to avoid old files or corrupted setup.
Also tested Vmware KaliLinux 2021.3 (Docker CE for Sn1per doesn't work well on Ubuntu or KaliLinux)

curl https://sn1persecurity.com/pro/9.0/"my license" /activation.sh | sudo bash

Scans files are saved in workspaces but it doesn't shown in the interface (tested allow full access to rute /usr/share/sniper with command sudo chmod a+wrx /usr/share/sniper)

![imagen](https://user-images.githubusercontent.com/55670766/136703643-f646e472-caa6-4b49-9f32-21c590940f68.png)

![imagen](https://user-images.githubusercontent.com/55670766/136703636-e65722db-aedd-4ead-aef3-b924fd22670f.png)

![imagen](https://user-images.githubusercontent.com/55670766/136703728-fb0afa12-f7d0-421a-a8da-511af8bb5b08.png)

![imagen](https://user-images.githubusercontent.com/55670766/136703651-feceb2d9-eb70-4fb4-9933-01c1960c6955.png)

**Comment by 1N3** [comment]
We have responded via our support email and will be closing this issue as this is not a Sn1per Community Edition issue.
