### ISSUE TITLE
Sn1per Pro 9.3 SE: Ubuntu 20.04.3 LTS: Some apps not working

### ISSUE THREAD

**Issue by ghost** [1N3/Sn1per#367]
Hi,

The following apps are not working, in spite of, i manually check and install their dependencies. 
Were tested in a clean Ubuntu 20.04 LTS image  before and after installing their dependencies.

- **_WPSCAN_** (**works fine on Ubuntu** but not in Sn1per: false positive error when Wpscan cannot test a website

![imagen](https://user-images.githubusercontent.com/55670766/137666631-0638ea9c-0416-4138-90b0-a3efb3aa26b2.png)
 
**_Important Note:_** i was checking and In this particular case, the same website tested with WPSCAN app was rejected because of a WAF and then because of a website that was not using Wordpress (is a mistake in the Sn1per message error or a general error?)

- **_Screenshot_** (Doesn't run Webscreenshot and/or Cutycaps)

![imagen](https://user-images.githubusercontent.com/55670766/137666663-0932fa50-4324-4d4f-a096-6cf39ff0f891.png)

- **_Jexboss_**

![imagen](https://user-images.githubusercontent.com/55670766/137666697-fd3224fd-d945-4f64-9f89-ebef70368638.png)
![imagen](https://user-images.githubusercontent.com/55670766/137667756-e202a578-2fde-49d4-9ea5-de97a470fd4e.png)

CMSMAP still working after a day scanning

![imagen](https://user-images.githubusercontent.com/55670766/137668749-7a6fddf4-d467-4c8a-b190-b02c7f55fe89.png)

**_Important Note:_**: I was checking IP scanned by CMSMAP and is possible blocked by WAF because of request of the app

**_OS information_**

![imagen](https://user-images.githubusercontent.com/55670766/137668689-79fdf0c0-3560-438e-be34-4db66f0e285b.png)

**_Openvas installation damages  Sniper web interface  (Kali Linux & Ubuntu)_**

![imagen](https://user-images.githubusercontent.com/55670766/138026108-d0f24416-d67f-4007-821b-e5accda068fd.png)

Thank you for your help!

**Comment by blackstone250** [comment]
Update: In this particular case, the same website tested with Wpscan app was rejected because of a WAF and then because of a website that was not using WPSCAN (is a mistake in the message error or a general error?)

**Comment by blackstone250** [comment]
**_CMSMAP Update_**: I was checking IP scanned by CMSMCMSMAP Update: AP and is possible blocked by WAF because of request of the app

**Comment by 1N3** [comment]
Sn1per has been tested on Ubuntu 20.04 LTS but the preferred OS is Kali Linux. 

Regarding CMSMap getting blocked by WAF, you will need to disable CMSMap in your sniper.conf to get around this or run 'stealth' mode scans only. 

For WPScan, try running the scan manually from the CLI and see if you are prompted to upgrade wpscan to the latest version. If so, upgrade and try re-running WPScan via Sn1per to see if that works. 

For OpenVAS, try stopping the OpenVAS service (openvas-stop), starting Apache (ie. service apache2 start), then re-start the OpenVAS service again after (openvas-start).

**Comment by blackstone250** [comment]
Hi @1N3 

Thank you for response!

**_Regarding CMSMap: Solved_**: 

Regarding WPscan: the error is a false positive when Wpscan cannot scan a website. 

Regard Openvas: Always is a problem, i'm waiting for a plugin from Sn1per and instructions to install it.

Thanks!
