### ISSUE TITLE
CMSMAP blocked by WAF in Stealth Mode

### ISSUE THREAD

**Issue by ghost** [1N3/Sn1per#368]
Hi, 

CMSMAP scanning in Stealth Mode is activating the Firewall and the IP is blocked by a company behind WAF
Note: In Stealth mode should use Passive scan
Suggestion: Can you give us the option to not scan plugins?
![imagen](https://user-images.githubusercontent.com/55670766/137666886-ca4cec43-ad62-451d-b52a-9f9596ff5715.png)

![imagen](https://user-images.githubusercontent.com/55670766/137671406-1a56d619-cf78-411b-9810-e8dc4de108ac.png)

**Comment by blackstone250** [comment]
Hi @1N3 , i noted that i made changes in the web interface, by editing the sniper.conf file but it modified /usr/share/sniper/.sniper.conf  intead of /root/.sniper.conf.
So i also noted that /root/.sniper.conf shoud be modified from an external editor. 
Also notes that after installed Sniper and made an update action, the file /root/.sniper.conf return to default setup. It can be possible?
Thanks!

**_Solved._**
