### ISSUE TITLE
documentation switches ?

### ISSUE THREAD

**Issue by d4op** [1N3/Sn1per#376]
your parameters aren't clear for me.

1. how to run a full scan wit all o re and webscan or will webscan be activated by default ?
2. if I launch o re on a single domain will it automatically test all found subdomains too or does I need to launch sniper with list of targets manually (all subdomains) ?
3. what is airstrike ?
4. what Is nuke ?
5. on the discover module I see I can use CIDR as target parameter is this possible with all target parameters ? like CIDR -o -re  or only discovery module?

I guess you got the points I ask, because its not clear defined or I missed something, if yes sorry.

**Comment by 1N3** [comment]
This is mostly all covered in the README and Wiki pages. Would recommend following the usage examples to start off for the best results.
