### ISSUE TITLE
Nuclei Scanning module

### ISSUE THREAD

**Issue by ch1r0n1n** [1N3/Sn1per#377]
I'm trying to run a web scan on my lab environment, but when Sn1per gets to the Nuclei module it gives the same error. Checking to see if this is a known issue or if there's a fix.
![Capture](https://user-images.githubusercontent.com/87951769/145725155-0c9a740d-c377-44e3-b4e7-775a1073fa8d.JPG)

**Comment by 1N3** [comment]
Haven't seen this yet, but can you provide the following details?

1. Full OS/version
2. Full Sn1per command used to generate the above errors
3. The Nuclei version running on your system (can be obtained by running the 'nuclei' command)

**Comment by ch1r0n1n** [comment]
1. Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-90-generic x86_64)
2. sniper -f [target filename].txt -m masswebscan -w [workspace]
3. Nuclei version 2.5.5 Templates 8.7.2

**Comment by 1N3** [comment]
Thanks. 

Based on the error displayed, my guess is that your target list has a forward slash "/" somewhere in it which is causing the output file to break. 

Can you confirm that the target list only contains either IP's, domains or hostnames and not URL's (ie. https://domain.com/)? 

You can use https://target.com as a target in your target list but it can't have a trailing forward slash at the end.
