### ISSUE TITLE
go install issues - go get needs to be changed to go install ...

### ISSUE THREAD

**Issue by tracyvierra** [1N3/Sn1per#380]
install is having issues with new rev of go:

[*] Installing SubJack...
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
[*] Installing SubOver...
go: downloading github.com/Ice3man543/SubOver v0.0.0-20180830003845-3d258e254ab5
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
[*] Installing FProbe...
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
[*] Installing ASnip...
go: downloading github.com/harleo/asnip v0.0.0-20210319223206-7bf449c1df44
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
[*] Installing GAU...
go: downloading github.com/lc/gau v1.2.0
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

**Comment by GreenPoint-InfoSec** [comment]
using apt install golang also installs go version go1.13.8 but the latest is go1.17.5

**Comment by GreenPoint-InfoSec** [comment]
I have submitted a pull request which should have the correct go commands in the install.sh file. Having go1.17.5 installed is a prerequisite but I plan to add this into the script too.

**Comment by 1N3** [comment]
This is fixed now in the master repo.
