### ISSUE TITLE
How To Enable Sn1per Gui Interface While Using Docker

### ISSUE THREAD

**Issue by Iandavidk** [1N3/Sn1per#383]
I am currently using Sn1per v9.0 on Windows (64bit) and my docker desktop version is 4.4.4. Sn1per works well while using docker-cli but i've been looking through the installation guide and other places for a way to enable the gui interface without much success. Some help please??

**Comment by 1N3** [comment]
Please check our Documentation here under "Getting Started" for help. 

https://sn1persecurity.com/wordpress/documentation/#getting-started
