### ISSUE TITLE
problem for load nmap 

### ISSUE THREAD

**Issue by arefkhodabandeh** [1N3/Sn1per#387]
I show this message for nmap when starting a target:

 RUNNING NMAP SCRIPTS 
====================================================================================•x[2022-04-24](01:13)x•
Starting Nmap 7.92 ( https://nmap.org ) at 2022-04-24 01:13 EDT
NSE: failed to initialize the script engine:
/usr/bin/../share/nmap/nse_main.lua:822: '/usr/share/nmap/scripts/vulners' did not match a category, filename, or directory
stack traceback:
        [C]: in function 'error'
        /usr/bin/../share/nmap/nse_main.lua:822: in local 'get_chosen_scripts'
        /usr/bin/../share/nmap/nse_main.lua:1322: in main chunk
        [C]: in ?

QUITTING!

**Comment by 1N3** [comment]
Try running the following commands as 'root': 

cd /usr/share/nmap/scripts/
rm -f /usr/share/nmap/scripts/vulners.nse
wget https://raw.githubusercontent.com/vulnersCom/nmap-vulners/master/vulners.nse
