### ISSUE TITLE
not creating or opening loot directory

### ISSUE THREAD

**Issue by AnubisTwine** [1N3/Sn1per#397]
/usr/share/sniper/loot/workspace/https:--websitename.co.uk-/scans/websitename/-normal.txt: No such file or directory

and thus it says this all the way thru the scan. seems like its not saving a file to use throughout the entire process. what can i do?
![Screenshot from 2022-10-09 21-57-06](https://user-images.githubusercontent.com/78452945/194779113-ad773947-37a0-4a9d-8729-11c7b3a76ee6.png)

**Comment by 1N3** [comment]
This is due to incorrect syntax. Use ```sniper -t target.tld``` instead of a URL.
