### ISSUE TITLE
FEATURE add HTML reporting output

### ISSUE THREAD

**Issue by glira** [1N3/Sn1per#4]
Add to you project the https://github.com/urbanadventurer/WhatWeb reports.
is a good idea, I already did something like

**Comment by 1N3** [comment]
WhatWeb is already added to the project. Were you looking for something else?

**Comment by glira** [comment]
sorry, I not found in the sample report, in any way the report has a lot of information it would be nice if it were in html with tables and colors to facilitate.
if I some work in this regard inform you.
congratulations is a good job!

**Comment by 1N3** [comment]
I'll look into adding some HTML reporting capabilities. It's a good idea.

**Comment by 1N3** [comment]
This is now implemented via the 'sniper loot' command which will convert all reports to html which can be loaded in a browser from /usr/share/sniper/loot/reports/ directory.
