### ISSUE TITLE
2 Issues

### ISSUE THREAD

**Issue by windmillnl** [1N3/Sn1per#40]
Hi! 

Thank you for your continued support & hard work on this. 2 Small things:
I'm having a problem getting Sn1per to generate a report after it's done scanning, when looking at some videos online, it mostly generates a .txt file containing a full output of the scan. 
I've tried a full Kali/Sn1per reinstall but it's still not working.
Secondly, the install.sh script should add a "chmod +x winshock.sh" since it doesn't have permission to run while running sn1per :)

Any idea what could fix the first problem though?
Thanks again!

**Comment by 1N3** [comment]
Hi, thanks for the heads up.. I'll look into fixing the install.sh script in the next release. 

Regarding the reports, the script saves 2 files under the loot directory under console/ and reports/. Both are just a stored console log from the output generated from the script. To view reports, you can run 'sniper loot' and it will automatically open the loot directory and allow you browse/view the reports from each scan and screenshots. 

If you're looking for something else with the reports, let me know. I have future plans to improve the reporting options to include HTML output/formats, but that will take some time.

Cheers,
1N3
