### ISSUE TITLE
Hie have this error with docker installation

### ISSUE THREAD

**Issue by CyberMatrixxx** [1N3/Sn1per#403]
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: short-name "xer0dayz/sn1per" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"

I dont know if this is a problem with my configuration

**Comment by 1N3** [comment]
Docker CLI install seems to work fine for me. It must be something corrupt with your Docker installation.
