### ISSUE TITLE
ERROR:wafw00f: Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER]

### ISSUE THREAD

**Issue by k0x00** [1N3/Sn1per#406]
Hello brother, what is this? can you help me?

RUNNING ACTIVE WEB SPIDER 
====================================================================================•xx•

                _.._
              .'    '.
             /   __   \ 
          ,  |   ><   |  ,
         . \  \      /  / .
          \_'--`(  )'--'_/
            .--'/()'--.
@xer0dayz  /  /` '' `\  \ 
             |        |
              \      /

 + -- --=[ https://sn1persecurity.com
 + -- --=[ blackwidow v1.3 by @xer0dayz 

HTTPSConnectionPool(host='**.*.*', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))
local variable 'domain' referenced before assignment

**Comment by 1N3** [comment]
This error means it failed to establish and SSL connection to the host.
