### ISSUE TITLE
Error with OWASP

### ISSUE THREAD

**Issue by Bars7878** [1N3/Sn1per#419]
Hi!
After owasp was enabled, when scan may be performed i got error:
 RUNNING OWASP ZAP SCAN 
====================================================================================•x[2023-05-10](12:44)x•

Traceback (most recent call last):
  File "/usr/share/sniper/bin/zap-scan.py", line 20, in <module>
    from zapv2 import ZAPv2
ModuleNotFoundError: No module named 'zapv2'
grep: /usr/share/sniper/bin/zap-report.txt: No such file or directory
[i] Scan complete.

In my case used OWASP 2.12.0

What wrong? owasp is enabled and configured according to the instructions

**Comment by 1N3** [comment]
Hi,

This integration is deprecated in the Community Edition, but the updated integration is available in our Professional and Enterprise versions of Sn1per.
