### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by menzow** [1N3/Sn1per#42]
Hello,

I think the dependencies should be updated.

I'm missing the following:
php5
ruby
rubygems
python

Not everyone has these tools installed. Would be nice to know which versions of python are compatible and which versions of ruby / rubygems.

Also php5 is not available by default in ubuntu 16.

**Comment by 1N3** [comment]
Thanks for the heads up! I will update this in the next release sometime in the next day or so.

**Comment by 1N3** [comment]
Regarding PHP on Ubuntu 16, I'll probably need some time to figure out the best solution but I'll keep around for reference to fix.

**Comment by menzow** [comment]
It's still possible to get php5 from the following repository:
https://launchpad.net/~ondrej/+archive/ubuntu/php

**Comment by 1N3** [comment]
Cool, good to know. I'm working on adding various OS flavors to the install options, so I could probably make an Ubuntu specific install to pull the package and install it automatically for Ubuntu users.

**Comment by menzow** [comment]
Great! Thanks.

If you need any help let me know

**Comment by menzow** [comment]
Some extra notes:

When adding the repository:
`add-apt-repository ppa:ondrej/php`

The package: software-properties-common has to be installed.
`apt-get install software-properties-common`

And the current language has to support UTF-8 `export LC_ALL=C.UTF-8` or you will get errors while adding the repository.

**Comment by menzow** [comment]
I'm making a docker image that will run on ubuntu 16.04 and have a working copy of Sn1per installed.

People can pull this image and instantly run Sn1per in a working container without worrying about dependencies. And you can check out the docker file for all the required dependencies to get Sn1per working in a clean ubuntu 16.04 installation.

Since you use a lot of kali tools, I added the kali-rolling repository found here: http://docs.kali.org/general-use/kali-linux-sources-list-repositories

This did give me some issues with ubuntu 14.04. I'm not entirely sure how this happened, after I finish the 16.04 version I'll start working on 14.04.

I think because the many dependencies this tool has, it's going to be difficult to guarantee a successful installation across different linux distros where you don't know what was already installed.

**Comment by 1N3** [comment]
Cool man. Let me know and I will link it in the main project page for people.

I'm thinking about scaling back the 3rd party tools/dependencies and limiting the core packages to just the main ones make it easier to install across various distros. That will take some time though.

**Comment by menzow** [comment]
Awesome.

Been trying for a few hours building and fixing bugs, almost got the docker image complete.
My current issue is that it's trying to install 1500 MB of dependencies.

I'm going to continue tomorrow, see if I can cut that overhead back one way or another.

Current progress:
https://github.com/menzow/sn1per-docker

Build: 
https://hub.docker.com/r/menzo/sn1per-docker/builds/bqez3h7hwfun4odgd2axvn4/

**Comment by menzow** [comment]
Quick update:
There's now a (almost) working image available on docker hub.

Example usage:
```
menzo@menzo:~$ docker pull menzo/sn1per-docker
menzo@menzo:~$ docker run --rm -ti menzo/sn1per-docker sniper menzo.io
                ____
    _________  /  _/___  ___  _____
   / ___/ __ \ / // __ \/ _ \/ ___/
  (__  ) / / // // /_/ /  __/ /
 /____/_/ /_/___/ .___/\___/_/
               /_/

 + -- --=[http://crowdshield.com
 + -- --=[sn1per v1.8 by 1N3
......
```

**Comment by 1N3** [comment]
Nice man! Will check this out and keep you posted!

**Comment by 1N3** [comment]
Hey man, thanks for your help with this. I was able to test it on a fresh Ubuntu 16.04 install and everything works great but I am getting some errors below. The 'nslookup' thing should be easy to fix. I can add that to the install.sh. 

Not sure what's going on with the Metasploit error but it would be nice to get that working as well. 

The other errors are less critical but I noted them below. I also added the docker links to the README.md file on the main project page. Let me know if you're able to figure out the Metasploit thing though. It might be a bug with Ubuntu but I'm only speculating.


/usr/bin/sniper: line 431: nslookup: command not found


/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt.rb:16:in `require': incompatible library version - /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt_ext.so (LoadError)
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt.rb:16:in `rescue in <top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt.rb:12:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework.rb:9:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework.rb:9:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/inflector/methods.rb:263:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/inflector/methods.rb:263:in `const_get'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/inflector/methods.rb:263:in `block in constantize'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/inflector/methods.rb:259:in `each'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/inflector/methods.rb:259:in `inject'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:73:in `parsed_options_class'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:69:in `parsed_options'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:47:in `require_environment!'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'



Traceback (most recent call last):
  File "bin/samrdump.py", line 159, in <module>
    logger.init()
AttributeError: 'module' object has no attribute 'init'



cutycapt: cannot connect to X server

**Comment by menzow** [comment]
Thanks for the feedback!

Your host environment should not impacting the container environment. So I'll be able to fix these issues within the image for sure.

I'm currently working on a develop branch (unstable) where everything is ordered a bit better.
I'll implement fixes for these issues there, and merge them into master tomorrow.

Metasploit seems to have some conflicting dependency versions, this can be fixed easy I guess.

After I merge this into master, I'll look into decreasing image size.

**Comment by menzow** [comment]
@1N3 I just pushed a new release to master.

Resolves the following issues:

- Conflicting dependencies for metasploit
- nslookup missing
- dig missing

I also cleaned up the Dockerfile so it's more in line with the docker recommendations.
Would be great if you could run through it again.

There's one more issue though, the image size is quite large. Around 2.5GB at the moment.
I'll see if I have some time this weekend to sort that out.

**Comment by 1N3** [comment]
Nice man. I checked again and everything's working good now! 👍

**Comment by menzow** [comment]
Hey @1N3 ,

It would be nice that the Docker version of Sn1per automatically rebuilds when you push changes to your repository.

I have a web hook that you can trigger to start a new build, you can add that web hook in the settings of this repository.
Send me a email at: hello@menzo.io and I'll send you the URL for the webhook.

**Comment by menzow** [comment]
Hey @1N3,

I just updated the docker image to v2.3a, I also decreased the target image size from 2GB to 911 MB 👍

**Comment by 1N3** [comment]
Awesome man! Good stuff!

**Comment by 1N3** [comment]
Hey @menzow, when you have a chance, can you take a look at https://github.com/1N3/Sn1per/issues/55 ? If you're able to assist, that would be great but no worries if you can't... ;)

**Comment by menzow** [comment]
Hey @1N3, sure thing. Changes have been applied and new build will be available in a few hours.

**Comment by 1N3** [comment]
Thanks @menzow. I'll let him know!

**Comment by menzow** [comment]
Hey @1N3, sure thing. New build is being made right now and will be available in a few hours.

**Comment by 1N3** [comment]
Gonna close this out for now to clean up the backlog...
