### ISSUE TITLE
Slurp not found

### ISSUE THREAD

**Issue by abnerrizzi** [1N3/Sn1per#420]
I did a try to run 
sniper -t target.com -o -re
and got the error below during the execution.

 STARTING PUBLIC S3 BUCKET SCAN 
/usr/share/sniper/modes/recon.sh: line 238: cd: /usr/share/sniper/plugins/slurp/: No such file or directory
====================================================================================•x[2023-05-20](20:06)x•
/usr/share/sniper/modes/recon.sh: line 239: ./slurp-linux-amd64: No such file or directory

**Comment by 1N3** [comment]
Removed Slurp in master branch.
