### ISSUE TITLE
Question about scan

### ISSUE THREAD

**Issue by killmasta93** [1N3/Sn1per#425]
HI
Currently ran the scan for the first time and got this alert 

`P1 - CRITICAL, Default Credentials - NMap, mydomain.com, |     root:&lh;empty> - Valid credentials`

im not sure if the password which found is 
`
&lh;empty>`

and the username root

but dont know either if its ftp or sftp or ssh i have tried all outcomes and did not work

Thank you

**Comment by 1N3** [comment]
Hi, you would have to check the scan log found under /workspaces/<workspace>/reports/sniper-*.html or the raw nmap files under /workspaces/<workspace>/output/nmap-*.txt for more details. Also, the root:&lh;empty> combo is just 'root' with no password.
