### ISSUE TITLE
Failed to open XML output file error

### ISSUE THREAD

**Issue by magiclcj** [1N3/Sn1per#47]
When running Sn1per from root I get the following with XML error... (IP Removed)

> root:~# sniper /usr/share/sniper/loot/dvrsvr.txt airstrike
           
 __________________________________________________________
 Bomb raid (contributed by Michael aka SNOOPY@DRYCAS.CLUB.CC.CMU.EDU)

 + -- --=[Launching airstrike: **.*.***.*
 + -- ----------------------------=[Running Nslookup]=------------------------ -- +
Server:		**.*.***.*
Address:	**.*.***.*

Non-authoritative answer:
**.*.***.*.n-addr.arpa	name = static-**.*.***.*.net

Authoritative answers can be found from:

**.*.***.*.in-addr.arpa domain name pointer static-**.*.***.*.net

 + -- ----------------------------=[Running port scan]=------------------- -- +
Failed to open XML output file /usr/share/sniper/loot/nmap/nmap-**.*.***.*.xml for writing
QUITTING!
grep: /usr/share/sniper/loot/nmap/nmap-**.*.***.*.xml: No such file or directory 
grep: /usr/share/sniper/loot/nmap/nmap-**.*.***.*.xml: No such file or directory
 + -- --=[Port 80 closed... skipping.
 + -- --=[Port 443 closed... skipping.
 + -- ----------------------------=[Done!]=-----------------

**Comment by 1N3** [comment]
Hi, which version of sniper are you running? Also, be sure that the contents of dvrsvr.txt contains either a domain or IP address separated by a new line (ie. don't include URL's like http://site.com, etc.).

**Comment by magiclcj** [comment]
Sorry for the delay in posting 1N3. I am using version 2.0. Also I only have the 1 ip when I ran sniper for dvrsvr.txt which is in usr->shr. Should I reinstall?

**Comment by 1N3** [comment]
I would first clone the latest github release: "git clone https://github.com/1N3/Sn1per" and run the install.sh (./install.sh) after. Once complete, just use "sniper <IP_HERE>" to scan a single host. 

The text files should only be used when scanning multiple hosts separated by a new line with airstrike and nuke modes. You'll also need to set the full path to the text file for this to work (ie. sniper /usr/share/sniper/loot/ips.txt airstrike) etc.

Hope that helps.

**Comment by magiclcj** [comment]
I am still getting this: Failed to open XML output file /usr/share/sniper/loot/nmap/nmap-96.4.*.*.xml for writing
QUITTING!
and
+ -- ----------------------------=[Running Intrusive Scans]=----------------- -- +
grep: /usr/share/sniper/loot/nmap/nmap-96.4.*.*.xml: No such file or directory
grep: /usr/share/sniper/loot/nmap/nmap-96.4.*.*.xml: No such file or directory
grep: /usr/share/sniper/loot/nmap/nmap-96.4.*.*.xml: No such file or directory

I appreciate the response so fast. I'm learning to test straight from cmd like you mention on your blog so I just want to make sure I have done things right. Thanks again for suggesting to use sniper IP it did work I just got those errors.

**Comment by 1N3** [comment]
looks like you're missing some directories under the loot dir.... try running the following to fix:

mkdir -p /usr/share/sniper/loot 2> /dev/null
mkdir /usr/share/sniper/loot/domains 2> /dev/null
mkdir /usr/share/sniper/loot/screenshots 2> /dev/null
mkdir /usr/share/sniper/loot/nmap 2> /dev/null
mkdir /usr/share/sniper/loot/reports 2> /dev/null
mkdir /usr/share/sniper/loot/output 2> /dev/null

**Comment by magiclcj** [comment]
That worked. I did not realize just creating those dir would fix it. Thanks again for the response so promptly!

**Comment by 1N3** [comment]
no prob man.

**Comment by Slavajun1417** [comment]
hello problem dsf@Slava:~/BruteX$ sudo brutex target https://es.ciur.ru/auth/login-page
 __________                __         ____  ___
 \______   \_______ __ ___/  |_  ____ \   \/  /
  |    |  _/\_  __ \  |  \   __\/ __ \ \     /
  |    |   \ |  | \/  |  /|  | \  ___/ /     \
  |______  / |__|  |____/ |__|  \___  >___/\  \
         \/                         \/      \_/

 + -- --=[BruteX v1.9 by @xer0dayz
 + -- --=[http://xerosecurity.com


################################### Running Port Scan ##############################
/usr/bin/brutex: line 91: nmap: command not found

################################### Running Brute Force ############################

grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory
grep: /usr/share/brutex/loot/nmap-target.xml: No such file or directory

**Comment by 1N3** [comment]
Hi, currently Brutex only supports brute forcing domains/IP's and hostnames (ie. brutex 10.0.0.1, brutex domain.com, brutex hostnamehere). It does not support full URL's currently, but this is something I'll look at adding in the future.
