### ISSUE TITLE
 Could not find a version that satisfies the requirement arachni (from versions: ) No matching distribution found for arachni

### ISSUE THREAD

**Issue by OMarciano** [1N3/Sn1per#52]
Could not find a version that satisfies the requirement arachni (from versions: )
No matching distribution found for arachni

Distribution directory is incorrect

**Comment by 1N3** [comment]
Which OS are you running?

**Comment by menzow** [comment]
Sn1per depends on archini as provided through the kali repository. Try adding this repository to your sources.list and installing it again.

```
echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" >> /etc/apt/sources.list.d/kali.sources.list
gpg --keyserver pgpkeys.mit.edu --recv-key  ED444FF07D8D0BF6
gpg -a --export ED444FF07D8D0BF6 | apt-key add -
apt-get update
```

**Comment by OMarciano** [comment]
i'm running on Kali 2

**Comment by 1N3** [comment]
@OMarciano were you still having issues with this? Did the suggestions by @menzow help?
