### ISSUE TITLE
Not working in Kali Linux !!

### ISSUE THREAD

**Issue by roothaxor** [1N3/Sn1per#53]
Sample Report after install.sh first run -->>

[91m                ____               [0m
[91m    _________  /  _/___  ___  _____[0m
[91m   / ___/ __ \ / // __ \/ _ \/ ___/[0m
[91m  (__  ) / / // // /_/ /  __/ /    [0m
[91m /____/_/ /_/___/ .___/\___/_/     [0m
[91m               /_/                 [0m
[0m
[93m + -- --=[http://crowdshield.com
[93m + -- --=[sniper v2.3 by 1N3
[0m
[92m + -- ----------------------------=[Running Nslookup]=------------------------ -- +[0m
Server:		209.222.18.222
Address:	209.222.18.222#53

** server can't find http://stsolidergroup.in: NXDOMAIN

Host http://stsolidergroup.in not found: 3(NXDOMAIN)
[92m + -- ----------------------------=[Checking OS Fingerprint]=----------------- -- +[0m

Xprobe2 v.0.3 Copyright (c) 2002-2005 fyodor@o0o.nu, ofir@sys-security.com, meder@o0o.nu

[+] Target is http://stsolidergroup.in
[92m + -- ----------------------------=[Gathering Whois Info]=-------------------- -- +[0m
No whois server is known for this kind of object.
[92m + -- ----------------------------=[Gathering OSINT Info]=-------------------- -- +[0m

*******************************************************************
*                                                                 *
* | |_| |__   ___    /\  /\__ _ _ ____   _____  ___| |_ ___ _ __  *
* | __| '_ \ / _ \  / /_/ / _` | '__\ \ / / _ \/ __| __/ _ \ '__| *
* | |_| | | |  __/ / __  / (_| | |   \ V /  __/\__ \ ||  __/ |    *
*  \__|_| |_|\___| \/ /_/ \__,_|_|    \_/ \___||___/\__\___|_|    *
*                                                                 *
* TheHarvester Ver. 2.7                                           *
* Coded by Christian Martorella                                   *
* Edge-Security Research                                          *
* cmartorella@edge-security.com                                   *
*******************************************************************

[-] Searching in Bing:
	Searching 50 results...
	Searching 100 results...

[+] Emails found:
------------------
No emails found

[+] Hosts found in search engines:
------------------------------------
No hosts found
[92m + -- ----------------------------=[Gathering DNS Info]=---------------------- -- +[0m

; <<>> DiG 9.10.3-P4-Debian <<>> -x http://stsolidergroup.in
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 15976
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;in.http://stsolidergroup.in-addr.arpa. IN PTR

;; AUTHORITY SECTION:
in-addr.arpa.		3600	IN	SOA	b.in-addr-servers.arpa. nstld.iana.org. 2016110956 1800 900 604800 3600

;; Query time: 683 msec
;; SERVER: 209.222.18.222#53(209.222.18.222)
;; WHEN: Sun Feb 19 08:41:53 EST 2017
;; MSG SIZE  rcvd: 134

dnsenum.pl VERSION:1.2.3
[1;34m
-----   http://stsolidergroup.in   -----
[0m[1;31m

Host's addresses:
__________________

[0m[1;31m

Name Servers:
______________

[0m[92m + -- ----------------------------=[Gathering DNS Subdomains]=---------------- -- +[0m
[91m
                 ____        _     _ _     _   _____
                / ___| _   _| |__ | (_)___| |_|___ / _ __
                \___ \| | | | '_ \| | / __| __| |_ \| '__|
                 ___) | |_| | |_) | | \__ \ |_ ___) | |
                |____/ \__,_|_.__/|_|_|___/\__|____/|_|[0m[93m

                # Coded By Ahmed Aboul-Ela - @aboul3la
    
[91mError: Please enter a valid domain[0m

[91m ╔═╗╦═╗╔╦╗╔═╗╦ ╦[0m
[91m ║  ╠╦╝ ║ ╚═╗╠═╣[0m
[91m ╚═╝╩╚═ ╩o╚═╝╩ ╩[0m
[91m + -- ----------------------------=[Gathering Certificate Subdomains]=-------- -- +[0m
[94m
[91m [+] Domains saved to: /usr/share/sniper/loot/domains/domains-http://stsolidergroup.in-full.txt
[0m
[92m + -- ----------------------------=[Checking for Sub-Domain Hijacking]=------- -- +[0m
[92m + -- ----------------------------=[Checking Email Security]=----------------- -- +[0m

[92m + -- ----------------------------=[Pinging host]=---------------------------- -- +[0m

[92m + -- ----------------------------=[Running TCP port scan]=------------------- -- +[0m

[92m + -- ----------------------------=[Running Intrusive Scans]=----------------- -- +[0m
[91m + -- --=[Port 21 closed... skipping.[0m
[91m + -- --=[Port 22 closed... skipping.[0m
[91m + -- --=[Port 23 closed... skipping.[0m
[91m + -- --=[Port 25 closed... skipping.[0m
[91m + -- --=[Port 53 closed... skipping.[0m
[91m + -- --=[Port 79 closed... skipping.[0m
[91m + -- --=[Port 80 closed... skipping.[0m
[91m + -- --=[Port 110 closed... skipping.[0m
[91m + -- --=[Port 111 closed... skipping.[0m
[91m + -- --=[Port 135 closed... skipping.[0m
[91m + -- --=[Port 139 closed... skipping.[0m
[91m + -- --=[Port 161 closed... skipping.[0m
[91m + -- --=[Port 162 closed... skipping.[0m
[91m + -- --=[Port 389 closed... skipping.[0m
[91m + -- --=[Port 443 closed... skipping.[0m
[91m + -- --=[Port 445 closed... skipping.[0m
[91m + -- --=[Port 512 closed... skipping.[0m
[91m + -- --=[Port 513 closed... skipping.[0m
[91m + -- --=[Port 514 closed... skipping.[0m
[91m + -- --=[Port 1433 closed... skipping.[0m
[91m + -- --=[Port 2049 closed... skipping.[0m
[91m + -- --=[Port 2121 closed... skipping.[0m
[91m + -- --=[Port 3306 closed... skipping.[0m
[91m + -- --=[Port 3310 closed... skipping.[0m
[91m + -- --=[Port 3128 closed... skipping.[0m
[91m + -- --=[Port 3389 closed... skipping.[0m
[91m + -- --=[Port 3632 closed... skipping.[0m
[91m + -- --=[Port 4443 closed... skipping.[0m
[91m + -- --=[Port 5432 closed... skipping.[0m
[91m + -- --=[Port 5800 closed... skipping.[0m
[91m + -- --=[Port 5900 closed... skipping.[0m
[91m + -- --=[Port 5984 closed... skipping.[0m
[91m + -- --=[Port 6000 closed... skipping.[0m
[91m + -- --=[Port 6667 closed... skipping.[0m
[91m + -- --=[Port 8000 closed... skipping.[0m
[91m + -- --=[Port 8100 closed... skipping.[0m
[91m + -- --=[Port 8080 closed... skipping.[0m
[91m + -- --=[Port 8180 closed... skipping.[0m
[91m + -- --=[Port 8443 closed... skipping.[0m
[91m + -- --=[Port 8888 closed... skipping.[0m
[91m + -- --=[Port 10000 closed... skipping.[0m
[91m + -- --=[Port 27017 closed... skipping.[0m
[91m + -- --=[Port 27018 closed... skipping.[0m
[91m + -- --=[Port 27019 closed... skipping.[0m
[91m + -- --=[Port 28017 closed... skipping.[0m
[91m + -- --=[Port 49152 closed... skipping.[0m
[92m + -- ----------------------------=[Scanning For Common Vulnerabilities]=----- -- +[0m
#########################################################################################
  oooooo   oooo       .o.        .oooooo..o ooooo     ooo   .oooooo.
   `888.   .8'       .888.      d8P'    `Y8 `888'     `8'  d8P'  `Y8b
    `888. .8'       .88888.     Y88bo.       888       8  888      888
     `888.8'       .8' `888.     `ZY8888o.   888       8  888      888
      `888'       .88ooo8888.        `0Y88b  888       8  888      888
       888       .8'     `888.  oo     .d8P  `88.    .8'  `88b    d88'
      o888o     o88o     o8888o 88888888P'     `YbodP'     `Y8bood8P'
Welcome to Yasuo v2.3
Author: Saurabh Harit (@0xsauby) | Contribution & Coolness: Stephen Hall (@logicalsec)
#########################################################################################

I, [2017-02-19T08:42:00.134434 #12184]  INFO -- : Initiating port scan
I, [2017-02-19T08:42:00.536569 #12184]  INFO -- : Using nmap scan output file logs/nmap_output_2017-02-19_08-42-00.xml
[92m + -- ----------------------------=[Performing Full NMap Port Scan]=---------- -- +[0m
[92m + -- ----------------------------=[Running Brute Force]=--------------------- -- +[0m
[91m __________                __         ____  ___[0m
[91m \______   \_______ __ ___/  |_  ____ \   \/  /[0m
[91m  |    |  _/\_  __ \  |  \   __\/ __ \ \     / [0m
[91m  |    |   \ |  | \/  |  /|  | \  ___/ /     \ [0m
[91m  |______  / |__|  |____/ |__|  \___  >___/\  \ [0m
[91m         \/                         \/      \_/[0m

[91m + -- --=[BruteX v1.5 by 1N3[0m
[91m + -- --=[http://crowdshield.com[0m

[92m################################### Running Port Scan ##############################[0m

[92m################################### Running Brute Force ############################[0m

[91m + -- --=[Port 21 closed... skipping.[0m
[91m + -- --=[Port 22 closed... skipping.[0m
[91m + -- --=[Port 23 closed... skipping.[0m
[91m + -- --=[Port 25 closed... skipping.[0m
[91m + -- --=[Port 80 closed... skipping.[0m
[91m + -- --=[Port 110 closed... skipping.[0m
[91m + -- --=[Port 139 closed... skipping.[0m
[91m + -- --=[Port 162 closed... skipping.[0m
[91m + -- --=[Port 389 closed... skipping.[0m
[91m + -- --=[Port 443 closed... skipping.[0m
[91m + -- --=[Port 445 closed... skipping.[0m
[91m + -- --=[Port 512 closed... skipping.[0m
[91m + -- --=[Port 513 closed... skipping.[0m
[91m + -- --=[Port 514 closed... skipping.[0m
[91m + -- --=[Port 993 closed... skipping.[0m
[91m + -- --=[Port 1433 closed... skipping.[0m
[91m + -- --=[Port 1521 closed... skipping.[0m
[91m + -- --=[Port 3306 closed... skipping.[0m
[91m + -- --=[Port 3389 closed... skipping.[0m
[91m + -- --=[Port 5432 closed... skipping.[0m
[91m + -- --=[Port 5900 closed... skipping.[0m
[91m + -- --=[Port 5901 closed... skipping.[0m
[91m + -- --=[Port 8000 closed... skipping.[0m
[91m + -- --=[Port 8080 closed... skipping.[0m
[91m + -- --=[Port 8100 closed... skipping.[0m
[91m + -- --=[Port 6667 closed... skipping.[0m

[92m################################### Brute Forcing DNS ###############################[0m
dnsenum.pl VERSION:1.2.3
[1;34m
-----   http://stsolidergroup.in   -----
[0m[1;31m

Host's addresses:
__________________

[0m[1;31m

Name Servers:
______________

[0m
[92m################################### Done! ###########################################[0m

[92m + -- ----------------------------=[Done]=------------------------------------ -- +[0m

**Comment by 1N3** [comment]
hi, target definitions can't include protocols (ie. http/https). Instead, just use the hostname/IP. That should solve the issue, but let me know if that doesn't work.

**Comment by roothaxor** [comment]
tried same problem

**Comment by 1N3** [comment]
can you paste the new output?

**Comment by roothaxor** [comment]
my bad problem with installation

**Comment by menzow** [comment]
Hello @roothaxor, 

Could you please report your exact issue and how you resolved it? This will help assisting other users in the future.

**Comment by roothaxor** [comment]
Hello @menzow there is no problem i had problem with my OS not in Sniper
