### ISSUE TITLE
Kali ok.. Ubuntu KO

### ISSUE THREAD

**Issue by Zibri** [1N3/Sn1per#54]
It would be better tho enhance the install script to be able to make a full install also on ubuntu.

As of not this is what happens:

E: Unable to locate package sslyze
E: Unable to locate package uniscan
E: Unable to locate package unicornscan
E: Unable to locate package waffit
E: Unable to locate package dirb
E: Unable to locate package dnsrecon
E: Unable to locate package wpscan
E: Unable to locate package enum4linux
E: Unable to locate package cisco-torch
E: Unable to locate package metasploit-framework
E: Unable to locate package theharvester
E: Unable to locate package dnsenum
E: Unable to locate package smtp-user-enum
E: Unable to locate package amap

Oviously the packages can be installed one by one.. but since Sn1per is an automated script I think it should consider this.

My 2c.

**Comment by menzow** [comment]
Hello Zibri,

I agree that the installer should indeed perform checks and run installs for all required dependencies. 

Until that is implemented however you can opt for using the Docker image available (instructions can be found in the README) or follow the steps I provided here https://github.com/1N3/Sn1per/issues/20#issuecomment-281225074 to install all dependencies on your OS.

**Comment by Zibri** [comment]
Sure. I don't have a problem even installing the prerequisites myself. It was just a heads-up since the nature of the script.
 Glad you agree.

-------- Messaggio originale --------
Da: Menzo Wijmenga <notifications@github.com> 
Data:22/02/2017  16:39  (GMT+02:00) 
A: 1N3/Sn1per <Sn1per@noreply.github.com> 
Cc: Zibri <zibri@zibri.org>,Author <author@noreply.github.com> 
Oggetto: Re: [1N3/Sn1per] Kali ok.. Ubuntu KO (#54) 

Hello Zibri,

I agree that the installer should indeed perform checks and run installs for all required dependencies.

Until that is implemented however you can opt for using the Docker image available (instructions can be found in the README) or follow the steps I provided here #20 (comment) to install all dependencies on your OS.

**Comment by menzow** [comment]
I experimented slightly with implementing this idea. I however stopped this effort and decided to provide a Docker Image that runs Sn1per. 

My concern was the following: Sn1per is not 1 piece of software, but a collection of different tools developed by various authors. All these tools come with a plethora of possibly conflicting dependencies and constant individual updates possibly causing new issues. 

If you look at Kali's bug tracker ( https://bugs.kali.org/view_all_bug_page.php?refresh=true ) you'll see how much constant effort is required in keeping all individual tools up-to-date and stable. Providing a installation script for Sn1per and all of its dependencies covering varying distros and user environments will cause similar issues.

I must admit that I'm by far not an expert on the subject of maintaining the compatibility of multiple tools and their dependencies across distros. Their might be some simple solutions that I'm overseeing or overestimating the possible issues. It would be great to hear @1N3's opinion on the subject. To me it seems as a nice enhancement but must be worth the effort 👍

**Comment by Zibri** [comment]
As a programmer I agree and understand that :)

-------- Messaggio originale --------
Da: Menzo Wijmenga <notifications@github.com> 
Data:22/02/2017  19:10  (GMT+02:00) 
A: 1N3/Sn1per <Sn1per@noreply.github.com> 
Cc: Zibri <zibri@zibri.org>,Author <author@noreply.github.com> 
Oggetto: Re: [1N3/Sn1per] Kali ok.. Ubuntu KO (#54) 

I experimented slightly with implementing this idea. I however stopped this effort and decided to provide a Docker Image that runs Sn1per.

My concern was the following: Sn1per is not 1 piece of software, but a collection of different tools developed by various authors. All these tools come with a plethora of possibly conflicting dependencies and constant individual updates possibly causing new issues.

If you look at Kali's bug tracker ( https://bugs.kali.org/view_all_bug_page.php?refresh=true ) you'll see how much constant effort is required in keeping all individual tools up-to-date and stable. Providing a installation script for Sn1per and all of its dependencies covering varying distros and user environments will cause similar issues.

I must admit that I'm by far not an expert on the subject of maintaining the compatibility of multiple tools and their dependencies across distros. Their might be some simple solutions that I'm overseeing or overestimating the possible issues. It would be great to hear @1N3's opinion on the subject. To me it seems as a nice enhancement but must be worth the effort 👍

**Comment by 1N3** [comment]
hey guys, I think this might be worth the effort to include support for Ubuntu specifically in addition to Kali out of the box. Since Sn1per is now included as part of PTF (Penetration Tester's Framework by TrustedSec), one of their original requests was to have a compatible Ubuntu installer. It also seems to be a common request/issue from various users running Ubuntu specifically, so I think it might be worthwhile (though, I'm a fan of docker for these things as well...). I'll leave this open as a future enhancement request, but  it may take a little time to rewrite it and test since I've been pretty busy lately.

**Comment by white-widow** [comment]
The same for Parrot Security OS would be nice ;) I´m installing, i think it will work fine. Not much different from kali. It seems we can't use tor or proxys. it would be very usefull. sry my english

**Comment by Caner112** [comment]
Check Docker version of Sn1per, its based on Ubuntu, it will give you some guidelines

**Comment by 1N3** [comment]
Gonna close this out for now as sniper runs great in docker and due to dependencies of various OS flavors, it would take away from core development of features to make sniper more effective. Currently, sniper is mainly written for Kali Linux and Debian and docker can be used to run sniper from any other OS which seems like the easiest and best solution.
