### ISSUE TITLE
Double open browser

### ISSUE THREAD

**Issue by MaximoPortal** [1N3/Sn1per#56]
I am using Tor+Privoxy 
From some reason my Kali was freezing time by time, but specially when  sniper working on "Running Web Vulnerability" after this scan it is open many tabs in browser.
After that Kali immateriality freezes .
So I just change things in ---->  
1. open the dconf-editor
2. org > freedesktop > Tracker > Miner > Files
3. set up crawling interval to -2
4.set up enable-monitors to false

after that in console :   traacker-control -r 
Close terminal.

So , after that I have start scanning and after few minutes when Sniper open in browser it is showed me a new Browser which is out of range of Tor and Privoxy !?

Even if my current window is open Sniper opening new browser window which is going out of Tor and Privoxy, which means if I check IP address in current window with some of link its said that I am anon.
But in the other window which NSiper is opened after scaning is my original IP address.

How this could happend and why Sniper open new browser window which bypassed Tor and Privoxy ?

**Comment by 1N3** [comment]
The web vulnerability scan does some google hacking using GooHak (https://github.com/1N3/Goohak/blob/master/goohak). See source code for details on what it's querying. 

I will check in a feature shortly to disable GooHak in the Sn1per options which should help in your case.

**Comment by MaximoPortal** [comment]
Thank you so much for explanation.
Nice work and keep on with good work.
thank you

**Comment by 1N3** [comment]
No prob and thanks for the feedback. I released v2.4 which includes an option to disable Google hacking queries in the main sniper script. Just set GOOHAK = "0" to disable and you should be all set.
