### ISSUE TITLE
discover scan filename mismatch

### ISSUE THREAD

**Issue by ifly53e** [1N3/Sn1per#57]
Discover scan breaks because the sort line at 
https://github.com/1N3/Sn1per/blob/master/sniper#L275
(maybe?)
can't find the file it is looking for...There appears to be a problem with an underscore and a dash mismatching.  I changed the underscore to a dash (or maybe the other way around) and it seemed to work but you will have to verify.

**Comment by 1N3** [comment]
Thanks for the heads up! Fixed in v2.4b which is now pushed to the master branch.
