### ISSUE TITLE
discover scan type

### ISSUE THREAD

**Issue by ifly53e** [1N3/Sn1per#58]
It appears discover just does a stealth scan on each ip it finds.  Any chance of including an option to have it do a normal sniper scan instead?  After a discover scan, if I want to do a full scan on each ip, the scans are going to repeat the tests from the stealth scan, which wastes time.

**Comment by 1N3** [comment]
Thanks for the feedback. I will definitely look into this over the next week or two to implement as I've been meaning to do the same for a while now. I'll keep you posted.

**Comment by menzow** [comment]
I think @ifly53e these lines: https://github.com/1N3/Sn1per/blob/master/sniper#L280-L288 which does seem like a bug.

I think you were planning to add an if/else statement there. Right now a discover scan with reporting on causes these two loops to execute:
```bash
for a in `cat $LOOT_DIR/domains/sniper-ips.txt` 
    do sniper $a stealth report
done
for a in `cat $LOOT_DIR/domains/sniper-ips.txt` 
    do sniper $a stealth
done
```

**Comment by 1N3** [comment]
I changed discovery scans to now do a full sniper scan in v2.5. I will eventually add a configurable option to discovery scans to specify either stealth, normal or web modes but for now, this should do what you want.
