### ISSUE TITLE
Strip protocol from $TARGET

### ISSUE THREAD

**Issue by menzow** [1N3/Sn1per#59]
Hey,

I've noticed that the various tools you're expect different target input formats. Ping for example expects a host as target, but hydra/brutex expect target to include a protocol definition.

I'd suggest we strip the protocol from the $TARGET when it's passed into sniper, and only set the protocol when calling the tools that require it. That way we're always sure what the actual value of $TARGET is.

**Comment by 1N3** [comment]
This is fixed in v2.4c. It should strip all $TARGETS with http:// https://.
