### ISSUE TITLE
Add loot directory integrity check 

### ISSUE THREAD

**Issue by menzow** [1N3/Sn1per#60]
Hey,

In a recent update the loot directory initialisation has ~~been removed~~ _changed_?, this causes fresh installs to break because most of the tools don't create intermediate directories.

I suggest the loot dirs integrity is checked when sniper is initialised and that any missing loot directories are created before continuing.

**Edit:**
Apparently it has not been removed, but I do think it was changed. Can't find the exact commit.

**Comment by 1N3** [comment]
I added an init function at the top of the script to init the loot directory every time sniper runs. Should be fixed now in 2.4c.

**Comment by menzow** [comment]
Great! Encountered the issue while doing a big polish on the docker image.

Biggest changes listed here: https://github.com/menzow/sn1per-docker/commit/5508afc147affef10637f054ee8e2f398f96b0e6

Most important change is that there's a VOLUME which persists the scan reports to your host operating system, and another VOLUME that allows you to add your own wordlists etc. Oh and I added xvfb so cutycapt actually take screenshots.

Right now still running some tests, expect to push the release to hub.docker.com somewhere this week.

**Comment by 1N3** [comment]
Cool man, I'll check it out! 👍
