### ISSUE TITLE
Nmap scans are run without no ping option

### ISSUE THREAD

**Issue by dd1899163** [1N3/Sn1per#61]
Is it possible for me to run nmap in sniper with -Pn flag.

 + -- --=[Launching stealth scan: 192.168.0.70 
 
 + -- ----------------------------=[Running Nslookup]=------------------------ -- +
Server:		192.168.0.1
Address:	192.168.0.1#53

** server can't find 70.0.168.192.in-addr.arpa: NXDOMAIN

Host 70.0.168.192.in-addr.arpa. not found: 3(NXDOMAIN)

 + -- ----------------------------=[Running TCP port scan]=------------------- -- +

Starting Nmap 7.40 ( https://nmap.org ) at 2017-05-17 15:51 IST
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 0.54 seconds
 + -- --=[Port 80 closed... skipping.
 + -- --=[Port 443 closed... skipping.
 + -- ----------------------------=[Done]=------------------------------------ -- +

**Comment by 1N3** [comment]
Will look into changing this in the next release.

**Comment by 1N3** [comment]
This is fixed in v2.4e which is pushed to the master branch.
