### ISSUE TITLE
rpcinfo not found in kali 2017.1

### ISSUE THREAD

**Issue by ifly53e** [1N3/Sn1per#62]
In latest release of Kali when running rpcinfo from the command line, the prompt claims that rpcinfo is not found.  One fix is to replace "rpcinfo -p $TARGET" in both occurrences where appropriate with:

**replace https://github.com/1N3/Sn1per/blob/master/sniper#L979 with
nmap -p 135 --script=rpcinfo $TARGET

replace https://github.com/1N3/Sn1per/blob/master/sniper#L1235 with
nmap -p 2049 --script=rpcinfo $TARGET

**Note in the line right below 979 the code is: https://github.com/1N3/Sn1per/blob/master/sniper#L980
nmap -A -p 135 -T5 --script=rpc* $TARGET
which may already run rpcinfo so replacing line 979 may technically not be necessary but if it were not there, then the error would go away as well.

**Comment by ifly53e** [comment]
Ugh....nevermind.....
"apt-get install rpcbind" will install rpcinfo if it is missing....
Maybe this is something the install script can solve for us?
Add rpcbind to this line?
https://github.com/1N3/Sn1per/blob/master/install.sh#L39

**Comment by 1N3** [comment]
This is fixed in 2.4d which is now in the master branch.
