### ISSUE TITLE
report option when using slashes in filename

### ISSUE THREAD

**Issue by ifly53e** [1N3/Sn1per#64]
running:  sniper ~/scanme.txt nuke report 

causes:  tee: /usr/share/sniper/loot/sniper-/root/scanme.txt-nuke-201705190854.txt: No such file or directory

on line https://github.com/1N3/Sn1per/blob/master/sniper#L624
replacing $TARGET with ${TARGET///} removes the slashes and allows the file to be found.  

Maybe someone can come up with a more elegant solution that keeps the file structure or replaces the slash with a dot...

Probably have to do this on lines 257, 307, and 315, as well as 624.

**Comment by 1N3** [comment]
Will look into this but currently sniper only supports the full report path, so you would have to type out or tab complete /home/user/scanme.txt for now.
