### ISSUE TITLE
install script folder location for iis-buffer-overflow.nse

### ISSUE THREAD

**Issue by ifly53e** [1N3/Sn1per#65]
It appears this line:
https://github.com/1N3/Sn1per/blob/master/install.sh#L69
cp $PWD/bin/iis-buffer-overflow.nse /usr/share/nmap/scripts/iis-buffer-overflow.nse

is giving this result on my Kali 2017.1

"cp: cannot stat '/usr/share/sniper/plugins/bin/iis-buffer-overflow.nse': No such file or directory"

The nse file is in my bin directory but the $PWD is giving the location as /usr/share/sniper/plugins when it should be one level higher in the sniper directory...probably because of this:
https://github.com/1N3/Sn1per/blob/master/install.sh#L49
cd $PLUGINS_DIR

changing line 69 to this:

cp $INSTALL_DIR/bin/iis-buffer-overflow.nse /usr/share/nmap/scripts/iis-buffer-overflow.nse
appeared to work for me

**Comment by 1N3** [comment]
Thanks for the heads up! I will definitely fix this in the next release.

**Comment by 1N3** [comment]
This is fixed 2.5a which is currently released.
