### ISSUE TITLE
add unattended support

### ISSUE THREAD

**Issue by anniesbbs** [1N3/Sn1per#68]
while leaving sn1per to scan many targets over the weekend, i returned to find nikto had paused the scan to ask about sending unknown headers to devs. unless this is a nikto specific issue, please add an option for suppressing prompts for better unattended support.

thank you for all your hard work

**Comment by anniesbbs** [comment]
solved: https://github.com/sullo/nikto/issues/444

in /etc/nikto.conf
change "UPDATES=yes" to desired setting

**Comment by 1N3** [comment]
cool, thanks for the heads up. I may put this in the install.sh going forward to prevent this.
