### ISSUE TITLE
nmap, proxychains!

### ISSUE THREAD

**Issue by Indeserpen** [1N3/Sn1per#7]
Hello!
Sn1per have some problems when I,m using it with proxychains, does not work with it!
When I use it without tor it seems nmap is not procceding scan , because all the ports are always closed! 
And when it starts hydra , i'm getting error about ssl!

**Comment by 1N3** [comment]
Hi, will look into how to add support for this in future releases.

**Comment by 1N3** [comment]
I recommend using VPN over proxychains and proxychains has issues across multiple tools used and not everything is supported.
