### ISSUE TITLE
define custom user input directory

### ISSUE THREAD

**Issue by anniesbbs** [1N3/Sn1per#70]
i have my own collection of usernames, passwords, subdomains, etc that i would like sn1per to use when auditing. i'd like to define these locations in sn1per for use. can this be done?

**Comment by menzow** [comment]
Currently there's a 2 fixed locations for user and password files. 
```
USER_FILE="/usr/share/brutex/wordlists/simple-users.txt"
PASS_FILE="/usr/share/brutex/wordlists/password.lst"
```
https://github.com/1N3/Sn1per/blob/master/sniper#L96-L98

**Comment by 1N3** [comment]
As @menzow suggested, there's some variables in the sniper script to set the users, passwords and domains referenced below:

USER_FILE="/usr/share/brutex/wordlists/simple-users.txt"
PASS_FILE="/usr/share/brutex/wordlists/password.lst"
DNS_FILE="/usr/share/brutex/wordlists/namelist.txt"

You can change these to whatever you want to use. 

Also in BruteX which installs by default when installing sniper, you can set the following variables in /usr/share/brutex/brutex:

FTP_USER_PASS="/usr/share/brutex/wordlists/ftp-default-userpass.txt"
MYSQL_USER_PASS="/usr/share/brutex/wordlists/mssql-default-userpass.txt"
ORACLE_USER_PASS="/usr/share/brutex/wordlists/oracle-default-userpass.txt"
POSTGRES_USER_PASS="/usr/share/brutex/wordlists/postgres-default-userpass.txt"
WINDOWS_USER_LIST="/usr/share/brutex/wordlists/windows-users.txt"
USER_FILE="/usr/share/brutex/wordlists/simple-users.txt"
PASS_FILE="/usr/share/brutex/wordlists/password.lst"
DNS_FILE="/usr/share/brutex/wordlists/namelist.txt"
SNMP_FILE="/usr/share/brutex/wordlists/snmp-strings.txt"

**Comment by 1N3** [comment]
Closing this out for now, but let us know if this works or not.
