### ISSUE TITLE
aha pip install error

### ISSUE THREAD

**Issue by ifly53e** [1N3/Sn1per#71]
Trying to install v2.5 in the latest rolling updated kali 2017.1, I get an error when aha is installed via pip (see below). However, "apt-get install aha" appears to work...

root@kali:~# pip install aha
Collecting aha
  Using cached aha-0.85adev.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/dist-packages/setuptools/dist.py:333: UserWarning: Normalizing '0.85a' to '0.85a0'
      normalized_version,
    running egg_info
    creating pip-egg-info/aha.egg-info
    writing requirements to pip-egg-info/aha.egg-info/requires.txt
    writing pip-egg-info/aha.egg-info/PKG-INFO
    writing namespace_packages to pip-egg-info/aha.egg-info/namespace_packages.txt
    writing top-level names to pip-egg-info/aha.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/aha.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/aha.egg-info/SOURCES.txt'
    error: Namespace package problem: aha is a namespace package, but its
    __init__.py does not call declare_namespace()! Please fix it.
    (See the setuptools manual under "Namespace Packages" for details.)
    "
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-MfTg48/aha/

root@kali: apt-get install aha
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  aha
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 20.4 kB of archives.
After this operation, 66.6 kB of additional disk space will be used.
Get:1 http://repo.kali.org/kali kali-rolling/main amd64 aha amd64 0.4.10.3-1 [20.4 kB]
Fetched 20.4 kB in 6s (3,297 B/s)
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend requires a screen at least 13 lines tall and 31 columns wide.)
debconf: falling back to frontend: Readline
Selecting previously unselected package aha.
(Reading database ... 440123 files and directories currently installed.)
Preparing to unpack .../aha_0.4.10.3-1_amd64.deb ...
Unpacking aha (0.4.10.3-1) ...
Setting up aha (0.4.10.3-1) ...
Processing triggers for man-db (2.7.6.1-2) ...
root@kali:~ which aha
/usr/bin/aha
root@kali:~ aha --help
Ansi Html Adapter Version 0.4.10.3
aha takes SGR-colored Input and prints W3C conform HTML-Code
use: aha <options> [-f file]
     aha (--help|-h|-?)
aha reads the Input from a file or stdin and writes HTML-Code to stdout
options: --black,      -b: Black Background and White "standard color"
         --pink,       -p: Pink Background
         --stylesheet, -s: Use a stylesheet instead of inline styles
         --iso X,    -i X: Uses ISO 8859-X instead of utf-8. X must be 1..16
         --title X,  -t X: Gives the html output the title "X" instead of
                           "stdin" or the filename
         --line-fix,   -l: Uses a fix for inputs using control sequences to
                           change the cursor position like htop. It's a hot fix,
                           it may not work with any program like htop. Example:
                           echo q | htop | aha -l > htop.htm
         --word-wrap,  -w: Wrap long lines in the html file. This works with
                           CSS3 supporting browsers as well as many older ones.
         --no-header,  -n: Don't include header into generated HTML,
                           useful for inclusion in full HTML files.
Example: aha --help | aha --black > aha-help.htm
         Writes this help text to the file aha-help.htm

Copyleft Alexander Matthes aka Ziz 2016
         ziz@mailbox.org
         https://github.com/theZiz/aha
This application is subject to the MPL or LGPL.

**Comment by 1N3** [comment]
This is fixed in 2.5a which is now public.
