### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by nfguide** [1N3/Sn1per#73]
Installing on Kali 4.9.25-1kali1 (2017-05-04)

Is this to be expected?

Collecting tldextract
  Using cached tldextract-2.1.0-py2.py3-none-any.whl
Requirement already satisfied: urllib3 in /usr/lib/python2.7/dist-packages
Requirement already satisfied: ipaddress in /usr/lib/python2.7/dist-packages
Collecting aha
  Using cached aha-0.85adev.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/dist-packages/setuptools/dist.py:333: UserWarning: Normalizing '0.85a' to '0.85a0'
      normalized_version,
    running egg_info
    creating pip-egg-info/aha.egg-info
    writing requirements to pip-egg-info/aha.egg-info/requires.txt
    writing pip-egg-info/aha.egg-info/PKG-INFO
    writing namespace_packages to pip-egg-info/aha.egg-info/namespace_packages.txt
    writing top-level names to pip-egg-info/aha.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/aha.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/aha.egg-info/SOURCES.txt'
    error: Namespace package problem: aha is a namespace package, but its
    __init__.py does not call declare_namespace()! Please fix it.
    (See the setuptools manual under "Namespace Packages" for details.)
    "

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0Rg5w8/aha/
 + -- --=[Installing gem dependencies...
Successfully installed rake-12.0.0

Thanks in advance.

**Comment by 1N3** [comment]
This is fixed in 2.5a which is now public.
