### ISSUE TITLE
Less intrusive auto update notifications?

### ISSUE THREAD

**Issue by menzow** [1N3/Sn1per#76]
Hey,

Just ran into the auto update notification for the first time. Although this is a great feature, would a less intrusive implementation maybe be an option? Right now everytime the sniper command is ran it requires an active TTY with STDIN. This is annoying in automated setups or when running the NUKE command. 

I'd suggest just printing a message notifying the user that there's an update available and letting them run `sniper --update` or something to start the update process.

**Comment by 1N3** [comment]
yeah, I totally agree. I'll work on implementing this in the next release. Thanks for the feedback!

**Comment by 1N3** [comment]
I changed the update function in the latest version (2.5e) to display a message to inform the user if an update is available and users can now update sniper via the 'sniper update' command.
