### ISSUE TITLE
Suggestions: Print out the command that's being delegated

### ISSUE THREAD

**Issue by chrisbward** [1N3/Sn1per#77]
This would be handy for manual runs on the tools?

**Comment by 1N3** [comment]
hey, thanks for the feedback. I like the idea and will work on this in a future release.

**Comment by 1N3** [comment]
Unfortunately, this takes way more time/effort than I can give to add it for all tools and will add more complications when there's updates which happen often. Going to close out for now, but if anyone wants to submit a PR for this, you are more than welcome and thanks for the feedback.
