### ISSUE TITLE
Dynamic detection of Web services

### ISSUE THREAD

**Issue by Themercee** [1N3/Sn1per#78]
When reading the result of the nmap scan, I suggest you to build an array containing all the ports where HTTP/HTTPS services are found. From there you could iterate the array and use the same scan function for each port. Something like (in python):
for port in web_ports:
  web_scan(port)

This way, if a web service is running on unusual port (like 21 for exemple), you would detect it and run the necessary scan without forgetting any scan tool.

**Comment by 1N3** [comment]
This is definitely on my list of things to do eventually, so I will leave this open to track this. Thanks for the feedback.

**Comment by 1N3** [comment]
Hi, I added two new modes to sniper called 'webporthttp' and 'webporthttps' to run full web application scans against non-standard ports (ie. sniper 127.0.0.1 webporthttp 8080). This is a shorter term workaround but it should get the job done until there is more dynamic detection of web services. Closing out for now but this is definitely something I will be looking at in the future.
