### ISSUE TITLE
3128 missing in default ports and default tcp ports variable definitions

### ISSUE THREAD

**Issue by ifly53e** [1N3/Sn1per#80]
There is code to execute if 3128 is open https://github.com/1N3/Sn1per/blob/master/sniper#L806 but that port is not listed to be checked here
https://github.com/1N3/Sn1per/blob/master/sniper#L100

or here
https://github.com/1N3/Sn1per/blob/master/sniper#L101

**Comment by 1N3** [comment]
Thanks for the heads up! This is fixed in the v2.5e which is now public.
