### ISSUE TITLE
sniper should be able to do multiple IP's

### ISSUE THREAD

**Issue by pentester123** [1N3/Sn1per#81]
Sniper should be able to read from a .txt or .doc/docx list of ip addresses that it will run though instead of having to run a new instance for each IP address. Like how nmap -iL will read off a text list.

**Comment by 1N3** [comment]
sniper nuke and airstrike modes were created to scan a list of IP's from a text file (ie. sniper /full/path/to/target.txt nuke). Just create a new .txt with IP's or domains separated by a new line and it should work.

**Comment by pentester123** [comment]
@1N3 Thank you for the info. I just tried both of them and it does not look like to me that they go though the whole thing like how it is when you do it just one IP address at a time. they also seem to finish very fast.

**Comment by 1N3** [comment]
airstrike mode runs a stealth scan which is basically a simple surface scan.
nuke mode will run all standard sniper tests for each IP/domain in the text file. 

Have you tried nuke mode?

The only thing nuke mode doesn't currently do is the 'web' mode scan of websites. However, it still does the nikto/whatweb scans, etc. that the normal sniper scan does. 

Let me know if that works or if you're looking for something more for this.

**Comment by pentester123** [comment]
@1N3 I did try both of them but I think they might be broken because they are finishing up way to fast and giving me very little read out compared to when I do a single IP at a time.

I also noticed that it is not dumping the reports into the folder it is claiming. I am not sure where it is putting the reports because I can't find them.

Also I am not sure if it is possible but if it is I would suggest that anything of interest like if sniper happens to RDP or finds any usernames and passwords or really comes back with anything other then not being able to find anything that it should be reported at the bottom when all tools are done. Instead of having to scroll though the whole scan.

**Comment by 1N3** [comment]
I believe there was some minor bugs with the airstrike mode that may have caused this. My suggestion is to try downloading the latest version (3.0) from github and try again (ie. sniper /path/to/targets.txt airstrike or sniper /path/to/targets.txt nuke) to scan multiple IP's/hosts. 

Regarding the report output, I'm looking at better ways to format reporting and findings but at this time, it is difficult to parse various tool outputs for consistent report so this may be difficult. Perhaps over time as sniper matures, new features will be added for better reporting of vulnerabilities discovered.

**Comment by kawaxi** [comment]
I wonder why I can use web mode with targets.txt? seems Im only interedted in the web part of them I wouldnt like to run nuke or airstrike.
