### ISSUE TITLE
nmap --append-output discussion

### ISSUE THREAD

**Issue by ifly53e** [1N3/Sn1per#82]
Consider adding --append-output after every -oX  for each nmap scan so that the previous scan information is not lost / over written upon subsequent nmap scans i.e. 
-oX $LOOT_DIR/nmap/nmap-$TARGET.xml --append-output

Also, this mod needs to be added to line 775 to add udp scan info to the file
https://github.com/1N3/Sn1per/blob/master/sniper#L775
(unless the logic is that the script does not use the udp info ever again so there is no need to add to the nmap data.  I am more inclined to append every nmap scan into the nmap file so that all nmap info is available for the metasploit database import at https://github.com/1N3/Sn1per/blob/master/sniper#L203 .)

Following this reasoning, lines containing an nmap scan at every port such as lines https://github.com/1N3/Sn1per/blob/master/sniper#L838 , https://github.com/1N3/Sn1per/blob/master/sniper#L850 , 
etc would need to have 
"-oX $LOOT_DIR/nmap/nmap-$TARGET.xml --append-output" added to them.

What do you think?

**Comment by ifly53e** [comment]
On second thought, db_import probably won't like an xml file with multiple top roots.  For getting everything into metasploit, will probably have to give each output xml file a unique name (probably just add the port number to the filename) and then let the wildcard do it's thing in the db_import call...
db_import $LOOT_DIR/nmap/nmap*.xml;
https://github.com/1N3/Sn1per/blob/master/sniper#L203

**Comment by ifly53e** [comment]
I have code that implements my second comment.

**Comment by 1N3** [comment]
I believe this has been implemented/pushed  to the main branch already so closing out for now. Thanks for the pull request btw.
