### ISSUE TITLE
iis-buffer-overflow.nse issue

### ISSUE THREAD

**Issue by ifly53e** [1N3/Sn1per#87]
Getting this error from line 965
https://github.com/1N3/Sn1per/blob/master/sniper#L965

Starting Nmap 7.50 ( https://nmap.org ) at 2017-07-13 11:58 PDT
NSE: failed to initialize the script engine:
/usr/bin/../share/nmap/nse_main.lua:259: /usr/share/nmap/scripts/iis-buffer-overflow.nse:165: unexpected symbol near '='
stack traceback:
	[C]: in function 'assert'
	/usr/bin/../share/nmap/nse_main.lua:259: in upvalue 'loadscript'
	/usr/bin/../share/nmap/nse_main.lua:601: in field 'new'
	/usr/bin/../share/nmap/nse_main.lua:825: in local 'get_chosen_scripts'
	/usr/bin/../share/nmap/nse_main.lua:1312: in main chunk
	[C]: in ?

QUITTING!

In order for this nse script to run properly, the commas need to be taken out of lines 165, 168, and 172 of the nse script.

**Comment by 1N3** [comment]
Changes merged.
