### ISSUE TITLE
Sniper probs after update

### ISSUE THREAD

**Issue by psychomad** [1N3/Sn1per#95]
Hi
I update sniper using git pull origin
everything fine until i try to launch the command: sniper <target> nuke report  <--- of course on target i put the ip target

what i have as response is:

cat: /usr/share/sniper/192.168.1.99: File o directory non esistente

I tried:
sniper <target> nuke

no luck
it work if i invoke only  sniper <target> but doesn't make any report...
Any hint?

In one of my try i tri to launch again build and install.sh

same effect

**Comment by 1N3** [comment]
Hi, the 'sniper nuke' is used to scan multiple IP's or domains so the $TARGET value is actually the full path to a file that contains multiple IP's or domains separated by new lines. If you want to run all tests, sniper <IP> will do the job. For web applications, sniper <IP> web will do a full web scan.

Hope that helps.

-1N3

**Comment by psychomad** [comment]
Hi
Thanks for answer, the problem is not with nuke option but directly invoking sniper.
Even if i invoke 
# sniper 192.168.1.99 report
/usr/bin/sniper: riga 324: /sniper: File o directory non esistente
basically after update i can't add any options

**Comment by 1N3** [comment]
hey, sorry for the delay here.. I've published a new release of sniper to fix the syntax errors you noted and others that I found. Can you try running 'sniper update' to see if that resolves the problem?

**Comment by psychomad** [comment]
Hey
i tried....

 sniper update
 + -- --=[Sn1per v2.6 is available to download... To update, type "sniper update"
                ____
    _________  /  _/___  ___  _____
   / ___/ __ \ / // __ \/ _ \/ ___/
  (__  ) / / // // /_/ /  __/ /
 /____/_/ /_/___/ .___/\___/_/
               /_/

 + -- --=[http://crowdshield.com
 + -- --=[sniper v2.6c by 1N3

 + -- ----------------------------=[Running Nslookup]=------------------------ -- +
Server:         192.x.x.x
Address:        192.x.x.x#53

** server can't find update: NXDOMAIN

Host update not found: 3(NXDOMAIN)
--------------------------

No luck.

**Comment by 1N3** [comment]
I located the issue with the 'update' command which is fixed in 2.7. To fix, you will need to do a git clone of sniper into a fresh directory and run install.sh to update. That should fix a lot of errors in the previous version but let me know if you run into anything else.

**Comment by psychomad** [comment]
Hey
Great job, now everything work fine... thanks a lot!

**Comment by 1N3** [comment]
awesome man, glad to hear it!
