### ISSUE TITLE
minor update issue

### ISSUE THREAD

**Issue by mpkosewski** [1N3/Sn1per#96]
The past couple times I've been notified there's an update for Sniper, it says to type "sniper update" to update. But when I do, it takes the "update" cmd as a website to enumerate. I've been updating manually instead as a workaround which is fine but figured I'd let you know.

Again, brilliant program btw! =]

Running Kali 4.12.0

**Comment by 1N3** [comment]
This was an issue in one of the last releases which has since been fixed. To fix, you'll need to git clone sniper into a new directory and re-run ./install.sh to re-install the latest version. Thanks for the feedback! 👍

**Comment by mpkosewski** [comment]
That's pretty much what I've been doing to update it. 

I did have a couple general questions but I'll post them later when I have a bit more time. =)
