### ISSUE TITLE
VPN connection breaks during nikto scan

### ISSUE THREAD

**Issue by Jinovas** [1N3/Sn1per#97]
Not sure why this happens and it happens most of the time I run `sniper <site> web`. I'm using openvpn for the PIA VPN service. I have to use openvpn for PIA because their regular app won't run as root. 

Just was curious if you or anyone has ran into similar issues? So far its consistently been when I run it with the 'web' option. I am currently running it again but as a different option to see if same issue happens. 

running: kali 4.12.0 

Also I was curious if there was a way to ad an option in the script to skip or cancel a currently running test/scan? I'm still learning bash/python scripting lol 

UPDATE: running nuke also breaks the VPN connection after a while during the nikto scan =/

**Comment by mpkosewski** [comment]
UPDATE2: ran nikto scan separately and it didn't break the connection. @_@

**Comment by 1N3** [comment]
hmm.. yeah, it might be causing some instability due to the amount of traffic/packets being sent. Hard to say what's causing this... I use VPN as well but don't have this.

**Comment by menzow** [comment]
Hey @mpkosewski ,

It might help to run sniper as a background task and use tail to view the output. This will keep the scan running even if your terminal gets disconnected.

Example:
```
sniper <target> <report> &> /tmp/sniper.scan.log &
tail -f /tmp/sniper.scan.log
```

**Comment by Jinovas** [comment]
Ok I'll give it a shot today. 

I'm still not sure if it's possibly my VPN (pia)  or what. But I know running nikto separate it doesn't break. I'll play around with it some more =)

**Comment by Jinovas** [comment]
It looks like it might actually be the VPN itself after looking at a few error logs. I'm waiting to hear back from PIA support to verify and see what they say.

**Comment by Jinovas** [comment]
Sorry, forgot to update this a while ago. But turns out it was a miss-configuration with OpenVPN and PIA. Now it works without disconnecting :)
