### ISSUE TITLE
Help Command

### ISSUE THREAD

**Issue by gbiagomba** [1N3/Sn1per#99]
Hello,

This is an amazing tool and I love using it. However I think one thing that it is missing is a "help" function. Granted I know I can at the read me file or go to the GitHub but I think it could be more convenient if the application had a help function (e.g. sniper help). Or if you want to keep up with the military lingo, may call it sniper support ;)

P.S this is more of a request, not so much of an issue

**Comment by 1N3** [comment]
Hi, this is actually already built into the latest sniper version 2.8 but I like the idea of the sniper 'support' command too. I may add a new alias for that but let me know if that doesn't work for you. The syntax is either sniper help or sniper --help.

**Comment by gbiagomba** [comment]
Ya it works, thank you! But ya i thought you would like that
